### ISSUE TITLE
Watch and fix Travis build

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#1]
[Currently failing at OWL to OBO conversions](https://travis-ci.org/FoodOntology/foodon#L314-L322). Perhaps due to a null OWL artefact. Will check back and fix if needed.

**Comment by cmungall** [comment]
Also: add a badge to the README.md

**Comment by cmungall** [comment]
I can replicate this

```
$ make foodon.obo
robot convert -i foodon.owl -o foodon.obo
java.lang.IllegalArgumentException: An input ontology must be specified
        at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:352)
        at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:314)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:127)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:48)
usage: robot [command] [options] <arguments>
 -h,--help             print usage information
 -noprefixes           do not use default prefixes
 -p,--prefix <arg>     add a prefix 'foo: http://bar'
 -P,--prefixes <arg>   use prefixes from JSON-LD file
 -v,--version          print version information
commands:
 help            print help for command
 annotate        annotate ontology
 convert         convert ontology
 diff            find the differences between two ontologies
 export-prefixes export prefixes to a file
 extract         extract terms from an ontology
 filter          filter ontology axioms
 merge           merge ontologies
 reason          reason ontology
 template        build an ontology from a template
make: *** [foodon.obo] Error 1
```

I think there may be a robot issue

But note that this will fail in any case until we have a catalog file available

**Comment by pbuttigieg** [comment]
> Also: add a badge to the README.md

Done

> But note that this will fail in any case until we have a catalog file available

@cmungall resolved this in 63e089b6dd4093572c00db1b1651769f90de6f55

Still and error possibly related to OBO - OWL conversion as shown [here](https://travis-ci.org/FoodOntology/foodon#L392-L413)

**Comment by Public-Health-Bioinformatics** [comment]
I've revised the Makefile process, and at moment no .obo products are produced.  Let me know if anyone wants the .obo fileset as part of the make process.

**Comment by cmungall** [comment]
You can skip .obo. See https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/ for replacement details.

Note that even if you don't use the obo, the obo conversion can serve as a lint check. E.g. make sure no classes have >1 label. But we aim to have the same functionality in robot in a way that isn't tied to obof

**Comment by Public-Health-Bioinformatics** [comment]
Ok. I'll close this now then.  A lint check would be welcome but will have to come later.  I'll carry on some discussion about duplicate labels on a separate thread focusing on the SIREN set of food products as they may arise with respect to that.
