### ISSUE TITLE
SDGIO remnants in Makefile

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#10]
[This line](https://github.com/FoodOntology/foodon/blob/master/src/ontology/Makefile#L33) references a variable, ``,  that is not defined. Probably a remnant from SDGIO defined [here](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/Makefile#L61-L62). 

Need to remove remnants

**Comment by Public-Health-Bioinformatics** [comment]
This is now archaic due to new Makefile.
