### ISSUE TITLE
NTR: hen egg (raw)

### ISSUE THREAD

**Issue by LCCarmody** [FoodOntology/foodon#100]
Currently, 2 terms exist, hen egg yolk (raw)  FOODON:03301439 and hen egg white (raw)  FOODON:03310155, however the whole raw egg isn't in FOODON. 
Could you add this term?  MAXO term would be to 'Avoid raw egg'. [#112](https://github.com/monarch-initiative/MAxO/issues/112)
Suggested structure
hen egg substance FOODON:03315102
 --hen egg (raw)
 ----egg yolk (raw)  FOODON:03301439
 ----hen egg white (raw)  FOODON:03310155

**Comment by ddooley** [comment]
Whole raw egg is tucked away under 
![image](https://user-images.githubusercontent.com/4000582/81742796-8142ef80-9455-11ea-9352-55846e14cba6.png)
will that work?

**Comment by LCCarmody** [comment]
Sure, is that there already and I missed it?!  Yes, that's fine.

**Comment by LCCarmody** [comment]
Egg on my face! :)  Don't know how I missed it except that I was using OLS and sometimes I can't immediately find the right term.  Thanks!
