### ISSUE TITLE
Deadly axiom in latest Foodon release

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#103]
In the latest Foodon release, `part of plant or animal` is a superclass of `anatomical entity` in CARO. It would be much appreciated if this axiom was removed because it breaks all sorts of things downstream (for starters: anatomical entities can be both material and immaterial). Thanks  :)

**Comment by ddooley** [comment]
Hmm.  Ok, will fix asap!  FoodOn actually isn't using that CARO term as far as I can tell so I will see about jettisoning it altogether.

**Comment by ddooley** [comment]
Ah, we are importing all of RO axioms for terms by way of OntoFox, and one of its relations "has developmental potential involving" has domain CARO "anatomical entity".  So I'll move anatomical entity under independent continuent then?!  Or should I make more of an effort to excommunicate it?

**Comment by matentzn** [comment]
I think it’s best not to change axiomatisation of non foodon terms.. there must be something said about the ‘part of plant or animal’ class that causes it to be a superclass of that CARO class.. the domain restriction alone can’t do that I think.

**Comment by ddooley** [comment]
What I meant was, a FoodOn curator (probably me) was looking for a place to put CARO "anatomical entity" - which was brought in automatically as a result of importing RO relations - and so manually subclassed it under 'part of plant or animal'.  Easiest solution if viable is we subclass it instead up to 'independent continuant'. Will that solve the problem?
Or do we try to block it altogether from FoodOn, by stopping import of the RO relation that triggered it to come in in the first place?

**Comment by matentzn** [comment]
I think if you can’t live with the caro class dangling around in the top level (which is IMO a perfectly viable option, my preferred) you could 1) delete the class (using robot remove) as part of the release process or 2) as a last resort, classify it under bfo entity. However, I am a strong advocate of never ever classifying terms that don’t “belong to you” :) I would be though fine with bfo entity as that is essentially Unconstrained..

**Comment by ddooley** [comment]
Ok, well, toward objective of not having anything we don't really use in FoodOn, I'll try to get the class out of FoodOn.  Will do today.

**Comment by ddooley** [comment]
done, and published live, along with a number of other updates!

**Comment by matentzn** [comment]
Great, thanks @ddooley
