### ISSUE TITLE
NTR: brassica vegetable food product

### ISSUE THREAD

**Issue by LCCarmody** [FoodOntology/foodon#105]
NTR: brassica vegetable food product

Parent term: vegetable food product (FOODON_00002142)
Child terms: 
- Brussels sprout vegetable food product (FOODON_00001670)
- cabbage vegetable food product (FOODON_00001677)
- broccoli vegetable food product (FOODON_00001666)
- cauliflower vegetable food product (FOODON_00001703)
- rapeseed vegetable food product (FOODON_00002187) (note: rapeseed meal (FOODON_03310043) is child under this term, but maybe move rapeseed oil (FOODON_03310482) as also a child under rapeseed vegetable food product.)

There may be additional plants that fall under this category as well.

**Comment by ddooley** [comment]
We have included this now in our foodon-edit.owl draft.

**Comment by ddooley** [comment]
loaded up to live!
