### ISSUE TITLE
Improve definitions for sake and beer

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#11]
:sake: Greetings! :beer: 
Moved from https://github.com/EnvironmentOntology/envo/issues/310
@pmidford suggested some good patterns!

**Comment by pbuttigieg** [comment]
From @pmidford 

> sake - Fermented rice beverage resulting from the fermentation of rice with the mold Aspergillus oryzae and, in parallel, with the yeast Saccharomyces cerevisiae [wikipedia:sake].
> 
> beer - Fermented cereal beverage resulting from the fermentation most commonly of malted barley (though wheat, corn, or rice may included), by a yeast, most commonly Saccharomyces cerevisiae, and flavored by dried flowers of hops, Humulus lupulus [wikipedia:beer].

**Comment by Public-Health-Bioinformatics** [comment]
I'm putting these definitions into FoodOn now.  Pier, how would you like to see wikipedia def. sources annotated?  IAO_0000119 annotating the definition annotation itself?  Or a http:wikipedia link right in the definition?  Chris advises not to apply IAO_0000119 to the class.

**Comment by Public-Health-Bioinformatics** [comment]
One other thing has come up - I just noticed 'bottled beer' as a subclass of beer, and I was going to indicate that this term "has 2d boundary" some "bottle or jar", but just realized "has 2d boundary" is a boundary that is supposed to be an immaterial entity, i.e. not a bottle. Looks like I have to swap this out for PATO:0005016 "surrounded by", doing that now.

**Comment by Public-Health-Bioinformatics** [comment]
completed
