### ISSUE TITLE
Help with allergens and taxonomy ( I tried to find a discussion section but I didnt find it)

### ISSUE THREAD

**Issue by esuarezz** [FoodOntology/foodon#111]
Hi! 

I joined some weeks ago to the tastermonial team,

I was working in a nutrition application in Spain, creating custom diets using AI and I delivered into the spanish mobile stores but then I met this project and I loved so I joined to the team.

I already joined to the google group,

Firstly, I am using javascript, I thought you have api for this, but I am not sure now,

I am working right now -> Get a list of ingredients and need to get an algorithm to know if they are mustard free, or if they can have the same allergen than nuts... for example,

you can see an example here(
#ALLERGENFRIENDLY, #DAIRYFREE, #GLUTENFREE, #KETO, #LACTOSEFREE ,#LOWTRANSFAT,#NOARTIFICIALADDITIVES, #NOCRUSTACEAN, #NOEGG, #NOFISH, #NOHONEY ,#NOMOLLUSK ,#NOPEANUT, #NOSESAME, #NOSULFITE, #NOTREENUT, #VEGAN,#VEGETARIAN)

we are getting the ingredients from our shopify store and we want to apply an algorithm to get the allergens in a top level to identify them and start to add the right tags,

what is the best approach for this? Thanks! so perhaps you dont have api, but you can tell me where is this core in the open source project and I can try to "extract it",

So to do something as you have here: https://www.ebi.ac.uk/ols/ontologies/foodon, are you using a rdf parser of the owl and writing the relations?

So would it be write a sparql query against your owl document and would I get that information? or do you have already set in the project some queries?
Can I get the sparql query that is matching in the best way the "answers" I want to get? 
Thanks!
Elio Suárez

**Comment by ddooley** [comment]
Some Food Allergy information is currently outside FoodOn, sitting in http://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_3044 , where FoodOn product branches are referenced.

You can see for example, egg allergy: http://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_4377 has a (subClassOf) axiom "has allergic trigger some egg food product".  One could construct a list of all food allergies that DOID knows of, and all related food product lines, by querying DOID and retrieving all the axioms.  One way to do this is with OntoFox: http://ontofox.hegroup.org/ which allows you to select an ontology like DOID:, ask for a term like food allergies, and retrieve all children and related axioms into an owl file.  Here's the configuration file for that:

[URI of the OWL(RDF/XML) output file]
http://purl.obolibrary.org/obo/anonymous/

[Source ontology]
DOID

[Low level source term URIs]
http://purl.obolibrary.org/obo/DOID_3044 #food allergy
includeAllChildren

[Top level source term URIs and target direct superclass URIs]


[Source term retrieval setting]
includeNoIntermediates

[Source annotation URIs]
includeAllAxioms

[Source annotation URIs to be excluded]
_____________

The config file can be loaded into form in part "2. Data input using local text file:" to retrieve a .owl file that you can play with in protege.  As well there is a javascript library for opening and working with RDF data structures such as this owl file.  I don't have time to create any educational materials on this now but a working example of querying an OWL file in javascript is buried within this code: http://genepio.org/ontotrek/ , namely: https://github.com/GenEpiO/ontotrek/blob/master/js/owl.js  which uses a 3rd party rdflib.min.js script.

--




_____________
But how you query th

**Comment by esuarezz** [comment]
Hi! I could make it work partially, but when I am running process_ontology I get "TypeError: Cannot read property 'uri' of undefined" Because "**subject**.uri" (subject). is undefined, but that is how you have implemented there, I see many comments, so not sure if this is not working properly also there,

this is the stack before doing the shift():

```
stack  [
  undefined,
  NamedNode {
    termType: 'NamedNode',
    classOrder: 5,
    value: 'http://www.w3.org/2002/07/owl#Thing'
  }
]

```

I see  const root = rdflib_url("owl:Thing"); but root is not used in any place,

Do you know what is happening? thanks!

**Comment by ddooley** [comment]
Whichever ontology you are looking at hopefully has a top-level node/entity?  Can you tell me what that is?

The script has this line:

  stack.push(store.sym(rdflib_url("owl:Thing") ))

Which should point to the top-level entity. You can change that to some other entity id if looking at a different ontology?  You would need to add the prefix ("owl:", etc.) to  '@context' if it isn't listed there already.  (I'm assuming the code works but if it doesn't I'll get to the bottom of it).

**Comment by esuarezz** [comment]
this is my resource:

```
const  resource = {
    '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'dc-terms': 'http://purl.org/dc/elements/1.1/',
        'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
        'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
        'owl': 'http://www.w3.org/2002/07/owl#',
        'oboInOwl': 'http://www.geneontology.org/formats/oboInOwl#',
        'IAO': 'http://purl.obolibrary.org/obo/IAO_',
        'BFO': 'http://purl.obolibrary.org/obo/BFO_',
        "doid": "http://purl.obolibrary.org/obo/doid#",
        "obo": "http://purl.obolibrary.org/obo/",
        "base": "http://purl.obolibrary.org/obo/anonymous/",

    },
    'reverse_c': {},
    'term': {},
    'metadata': {}
};


```
I took from the top of: [URL to excel with the file I got from the Ontofox](https://drive.google.com/file/d/14XwF1zIyMyeZWlkkxepZXFyym6EBRq5r/view?usp=sharing)



THanks!

**Comment by ddooley** [comment]
And can you answer this: 
"Whichever ontology you are looking at hopefully has a top-level node/entity? Can you tell me what that is?"

**Comment by esuarezz** [comment]
This is giving me null :         var focus = store.any(undefined, multi_property.subClassOf, undefined)

so 
```
 while (focus) {
            var top_node = focus
            focus = store.any(focus, multi_property.subClassOf)
        }
        console.log("Found owl root: " + top_node)
```

Top_node is undefined, that is also quite confusing, because the variable is being created in runTime and being asked after that.

Also not sure, where shall I write the word I am looking for?

**Comment by ddooley** [comment]
You are supplying the script with a URL to an ontology, right?  So if you fetch that ontology separately, and download it, and look at it with Protege, (or in a text editor but that might be harder to see) it should show a top node under which all your ontology's other terms are organized?

**Comment by esuarezz** [comment]
I dont think I am supplying the script with a URL to an ontology, how can i get that url to the ontology and where shall I introduce it?

THanks, I didnt work with ontologies before and its quite hard to understand all of this because its like a new world in the software development life

**Comment by ddooley** [comment]
The call to process_ontology() is in common.js , inside function load_data(URL, callback) 

Provide that function with the URL to an owl ontology.  This script doesn't have any ontologies "hard wired" into it.

              // Good tips here: https://github.com/solid/solid-tutorial-rdflib.js/issues/4
              $rdf.parse(this.responseText, store, URL, 'application/rdf+xml');
              data = process_ontology(store);

the above "data" variable contains a decent data structure containing key annotations like label and definition for each term.
Check out the "good tips" link. It may be more to the point of what you need.  I'm afraid I don't have time to create more of a tutorial about this though.

**Comment by esuarezz** [comment]
I will check it out , thanks! 

Dont worry about the tutorial! this part rdf/ontology its more about data science I guess, but I will manage with my questions and your nice projects =')  THanks for your help !

**Comment by ddooley** [comment]
Ok, I'll close this then.
