### ISSUE TITLE
Creation of FOODON: plant material (or similar) Robot Template

### ISSUE THREAD

**Issue by kaiiam** [FoodOntology/foodon#114]
As per ongoing discussion in the Crop Dietary Nutrition Ontology (CDNO), (xref https://github.com/Southern-Cross-Plant-Science/cdno/issues/4), we have decided to create a new Robot template in FOODON for the generation of `plant material` terms. 

Many such terms already exist within FOODON, e.g., [apple (whole)](http://purl.obolibrary.org/obo/FOODON_00002473). In order to supplement these terms, we (in the above mentioned CDNO thread) had decided that this new Robot template would contain an equivalence axiom that would link such FOODON term (new and existing) to terms from both the Plant Ontology (PO) and NCBITaxon in the form: `(PO:X and ('develops from part of' some NCBITaxon:Y))`.

@ddooley had suggested:

> Lets make it [the template] work off of a (tsv download of a) google sheet so that editors can collaboratively advance the content easily.

As such I've created [this google sheet for the FOODON:plant_materials](https://docs.google.com/spreadsheets/d/1VJtz4m67tdUNDqRe3m1Okdxll64nTR46GSvCOmb0APE/edit?usp=sharing). @ddooley I can transfer you ownernship if you'd like. 

I'll prepare the terms in scope for CDNO that we've discussed with @LilyAndres and @CropStoreDb. @ddooley let me know if there are changes needed to the robot template or if you'd like me to move forward with a pull request to add this into FOODON in the [/src/ontology/imports/robot](https://github.com/FoodOntology/foodon/tree/master/src/ontology/imports/robot) directory.

**Comment by kaiiam** [comment]
I've gone ahead and added all of @LilyAndres's terms (ID's and Equivalence class axioms) to the above mentioned sheet. However, in order to get it to compile, we'd need to add `develops from part of` to the FOODON's `ro_import.owl` file.

**Comment by ddooley** [comment]
That's great.  In latest FoodOn src/ I've converted all "develops from part of" relations into "derives from", so no need to include that relation anymore.  I think we can count on the robot file to provide the label, definition etc. so I'll get one of our people to copy over the static stuff.
One other thing - I think the same pattern applies to both plant and animal stuff, so we could generalize the sheet name to "organism material" ?  (Or we keep a separate one for animal stuff but I don't think there will be any field differences so I'd advocate for just having one).

**Comment by LilyAndres** [comment]
Thanks @kaiiam, I would like to go through the file with you if that's possible? I had a look into the ROBOT repository and guideline but I don't understand all the columns in this file. I also send a request to edit it, I hope you receive it soon. Thanks.

**Comment by kaiiam** [comment]
@ddooley 

> I've converted all "develops from part of" relations into "derives from"
👍 

> so we could generalize the sheet name to "organism material" ?

Totally up to you, I can change it if you'd like. 

>  I think we can count on the robot file to provide the label, definition etc. so I'll get one of our people to copy over the static stuff.

Since it'll work either way totally up to you as well how you want to handle this, if you want those static fields in the foodon edit owl or in the robot template. Upon import they'll be joined, but I guess the idea would be to keep all the provenance information in one place aka the Robot template rather than in the individual owl classes. I hope this is helpful to FOODON in the long run (and worth the short term changes).

@LilyAndres both your emails should now have access, we can organize a meeting via email.

**Comment by LilyAndres** [comment]
Thanks @kaiiam. I changed all 'develops from part of' to 'derives from' in the doc.

**Comment by kaiiam** [comment]
@ddooley looks like you and you team have done a good job filling in the template. Do you still need more time to finish it, or can I try making the PR with a tsv export as it is now?

**Comment by kaiiam** [comment]
I went ahead and added periods at the end of the sentences for the definitions. I see there are just a couple of sticking points left in the text definitions for the terms `barley seed (whole)`, `common wheat kernel`, and `broccoli floret (whole)`. @ddooley let me know when you get that resolved and I'll go ahead with the PR. 

Also would you like me to transfer ownership of the  the google sheet for the [FOODON:organism_materials](https://docs.google.com/spreadsheets/d/1VJtz4m67tdUNDqRe3m1Okdxll64nTR46GSvCOmb0APE/edit#gid=0) sheet to you? If so to which email?

**Comment by kaiiam** [comment]
@ddooley I see in the [imports/robot/README.md](https://github.com/FoodOntology/foodon/blob/master/src/ontology/imports/robot/README.md) that you run these ROBOT commands individually and that they are not in the Makefile. Would you be interested in having me try to add these to the Makefile? That way we could set it up have a single step e.g. `./run make all_modules` which would compile the latest on all the Robot templates. I just managed to make a working Robot Template in [this PR to SRPDIO](https://github.com/UA-SRC-data/srpdio/pull/7), which has an ODK generated makefile similar to that in ENVO. Let me know if that would be helpful for FOODON.

**Comment by ddooley** [comment]
Sounds good. i presume make all_modules  would trigger a robot on a .tsv file only if make detected a change in that file?

We have some definitions to revise in organism materials - I'll have Anoosha do that today.  As well after you get a version of it compiled and I edit the redundant axioms out of foodon once it is an include, then we'll be massively adding to that table.  We realize its a priority in order to add ELK inferencing that we want for lots of related terms.

**Comment by ddooley** [comment]
I guess all the robot commands could be boiled down into a single one that enables references using the "--input ..." command.  For more general referencing of term label to ids, we probably need a "--input ../../foodon_merged.owl" \ line.

Thanks so much for your help!

**Comment by kaiiam** [comment]
> Sounds good. i presume make all_modules would trigger a robot on a .tsv file only if make detected a change in that file?

It looks to me like it runs everything again regardless. Would that be an issue? 

> I guess all the robot commands could be boiled down into a single one that enables references using the "--input ..." command. For more general referencing of term label to ids, we probably need a "--input ../../foodon_merged.owl" \ line.

I presume so as well I'll try and play with it, I want to make sure that what I did for SRPDIO is correct before I try it here. I'll keep at it and let you know how it goes.

**Comment by ddooley** [comment]
Its not particularly an issue if everything is run again, but make does have a built-in ability to detect when files change and only do stuff then - that's how the ontofox imports/ file handling is done, only when a timestamp change in one of those files occurs does ontofox get involked on it to generate a new .owl file.  So the same thing for robot processing should be straightforward.

**Comment by kaiiam** [comment]
> but make does have a built-in ability to detect when files change and only do stuff then

That's what I though but here it was re-running them, in the past I've seen make state that there is nothing to do and won't run anything again. 

I have another question for you @ddooley , when you do a direct import in protege, which of the options did you use?


<img width="505" alt="image" src="https://user-images.githubusercontent.com/12255688/94283418-40a1c980-ff51-11ea-97dd-96ae5aa0bb62.png">

Was it perhaps the second for document on the web? Because when I try it with the first option, the local file isn't found when I try to run make all imports. Thoughts on this?

**Comment by ddooley** [comment]
Always the first.  If you run into wierdness there, first thing to do is delete the catalog.xml file in the src/ontology folder, and perhaps one in the src/ontology/imports folder.  Its protege's cache reference file and sometimes it points to unhelpful things as files are changed.

**Comment by kaiiam** [comment]
@ddooley thanks for the feedback! I removed and re-added the catologue.xml file but now running make imports is having a parsing error when trying to load the direct import robot template owl file. I've seem something like this before when trying to get protege to load an ontology file I'd created from scratch. Last time it was a missing RDF tag in the xml, but not now it's being loaded in protege but it's having a parsing error with that new owl file  when I run `./run.sh make all_imports`. For reference this is in https://github.com/UA-SRC-data/srpdio/pull/7 not here. I'll pick this again later it's weekend hours here in Europe.

**Comment by kaiiam** [comment]
Ok the issue in https://github.com/UA-SRC-data/srpdio/pull/7 seems to be fixed now. Thanks again @ddooley  for the feedback about the catalog file it helped me figure things out.

> As well after you get a version of it compiled and I edit the redundant axioms out of foodon once it is an include, then we'll be massively adding to that table. We realize its a priority in order to add ELK inferencing that we want for lots of related terms.

Great, I'm glad this equivalence class reasoning/inferencing is useful to the project! it totally makes sense to me to use inferencing to place terms when possible. 

>  For more general referencing of term label to ids, we probably need a "--input ../../foodon_merged.owl" \ line.

Looking at the FOODON makefile you have the following ODK style lines:

```
 Merge ontology and imports into one file, and commment out imports tags
	$(ROBOT) merge --input $(ONT).owl --xml-entities --output $(ONT)-merged.owl
	sed -i '.bak' 's/<owl:imports[^>]*\/>/<!-- & -->/' $(ONT)-merged.owl
```
That make the foodon_merged.owl file. My thinking would be that we would just add all complied ROBOT files as direct imports (like you have now). The change I'm proposing would be to add code to the Makefile which would automatically compile the robot templates as part of the `prepare_release` target, or upon command (as needed) with a `./run make all_modules`. I see, that the FOODON prepare_release is a bit different than a standard ODK generated makefile, for example it doesn't have targets broken down by ASSETS. I'm not sure if that would affect Make's ability to detect and not run targets that "have nothing to be done". 

@ddooley I'm rambling a bit but let me know what you'd like me to try, I can try to:


1) simply create the new robot template and add lines to compile it manually to the robot readme (as you currently have the other robot files)

2) Add those ROBOT instructions to compile the templates to the Makefile, as well as try to get it run when we call make prepare releas

3) Do 2 and try to update the Makefile to be more like a standard ODK generated template. 

Let me know, perhaps I start with option 1 or 2?

**Comment by ddooley** [comment]
How about we start with option 1.  I realize now that compilation of a robot file doesn't always work - it often requires a bit of manual iteration to get the labels to be matched and as well they can be works in progress with new records being added all the time that aren't necessarily ready when a curator does "make".  Later perhaps we can designate some robot files that are ripe for automation.

**Comment by kaiiam** [comment]
Sounds reasonable, if you want, I could still add the lines to the makefile to compile the individual robot files a one liners to run with something like `./run.sh make modules/organismal_material.tsv` (without adding it to the release process) instead of having to paste all the robot code, but I guess it's not really that much of a time saver relative to how it is now. 

When you guys are ready, would it be OK if I were to proceed with a pull request to add and compiling the Template to get the terms needed for CDNO? @LilyAndres is on a tight timeline to finish her thesis. I take it in such a PR it'd also use protege to directly import the new owl file into into foodon-edit.owl? Later we could make subsequent PRs to refresh the tsv as more terms are ready in the google sheet. 

Finally just another thought, I had originally proposed this be a `plant material` or similar template because that way all the terms could have equivalence axioms of the same form: `(PO:X and ('derives from' some NCBITaxon:Y))`. If this template were to include non-plant food terms, e.g. animal products the equivalence axiom would need to draw from a different ontology, e.g. uberon. Not that you couldn't have both in the same template, but if it makes it easier to split them out, I could help setup a parallel template(s) for `animal material` or similar. Up to you just a suggestion.

**Comment by ddooley** [comment]
Ok, if there's a make command that we could have that would test any/all the robot files for a regeneration that would be good since it would eliminate the need for users to cut/paste robot commands directly.  I guess the outputs could be stored in the src/ontology/imports/robot/ folder, and manually moved up a level as desired.

Let me push the latest foodon-edit.owl & some other files to master, and then if you can do your pull request off of those that would work well.

I suppose we could separate plants and animals, its just that I can't see for this class that there would be anything different in terms of columns/attributes.  The table will always reference only the plant and animal organism parts that are already in FoodOn under "part of organism" so that encompasses both PO and UBERON.  So lets keep them together for now, and I can make the change later if I've missed something obvious.

**Comment by ddooley** [comment]
Pull request against current master should be fine now.

**Comment by ddooley** [comment]
Note that in the organismal material table in equivalency axiom table one can mention component terms by their names rather than their ids, so e.g. for pineapple one can say " 'fruit multiple' and 'derives from' some 'Ananas comosus' ".

**Comment by kaiiam** [comment]
So far so good it's working! But a few things to note:

1) In order to get the template to compile on my system I added the ODK generated `run.sh` executable to run ROBOT from the ODK docker image. Otherwise I'd get a `/bin/sh: robot: command not found` error which I presume is where @ddooley you have Robot installed locally. I think it'd be better practice to follow what's done with ODK and have docker desktop (easy enough on mac/linux not as much on windows) with the `obolibrary/odkfull` image pulled. See the instructions on the odk page [here](https://github.com/INCATools/ontology-development-kit#instructions-create-a-new-ontology-project). Once that's installed this can be run with `./run.sh make imports/robot/organismal_materials.owl`. It should be able to work without docker and with a local install of robot with a command like `make ./run.sh make imports/robot/organismal_materials.owl`. If we're going to be adding more to the makefile it'd be good to decide on if we expect people to have the ODK docker image or not. 

2) I had to set the import ontology (specified by the --input or -i flag) to be `foodon-edit.owl` instead of `imports/ro_import.owl` (like in the other FOODON Robot template examples). Otherwise it woudln't compile because this prevents Manchester syntax errors like `MANCHESTER PARSE ERROR the expression ''pome fruit'' at row 3, column 3`. By doing this, curators can add any label that matches a term imported into foodon, like `pome fruit`, which should make these sheets easier to work with. 

3) We'll need to import `ear infructescence` PO:0025597. I just changed it to the ID in the template for now to get it to compile, that was the only PO term missing from FOODON in the template. 

The next thing I'll try is to see what happens when I import the new owl file into foodon-edit.owl (after making a release copy of the robot file `robot_organismal_materials.owl` in `/src/ontology/imports`. I'll make sure there aren't any issues prior to committing these last steps.

**Comment by kaiiam** [comment]
OK, I've tested out importing `robot_organismal_materials.owl` into foodon-edit.owl. When I run the ELK reasoner nothing breaks sot that's good news. I haven't tried to run make all_imports just incase, but I don't think I'll run into the same issue with the catolog that I did with https://github.com/UA-SRC-data/srpdio/pull/7 as the modules are a subdirectory to the ontology/src/ontology dir. 

A few things I notice when examining the merged product and reasoning:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/12255688/94561232-080d3300-0264-11eb-9326-978f0771ec9a.png">

Classes like `barley seed (whole)` and `durum wheat kernel` are now placed under PO:`caryopsis fruit`. In both these cases the reasoner didn't infer it because we are asserting it in the `parent class`  column in the template which manually asserts the super class relationship with `SC %`. If we didn't have this it would still be there but instead inferred by the reasoner like how barley is inferred to be a seed by the axiom shown here:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/12255688/94561832-d9438c80-0264-11eb-8047-1c2a90c3236a.png">

I think doing it either way is fine, I just to bring it to your attention @ddooley. Which also brings up the point that many of these classes already have axioms and annotations from other sources such as the `foodon_product_import.owl` which in the case of barley brings in the equivalence axiom with `seed and derives from some barley plant`. I'm guessing it's not necessarily bad or wrong to have two equivalence axioms? But maybe one of them could be asserted higher up in the hierarchy? I'm no expert on the relationship between `caryopsis fruit` and `seed`, but maybe in this case it's just both. [caryopsis fruit](http://purl.obolibrary.org/obo/PO_0030104) in PO is defined as: 

> A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are fused to a seed coat (PO:0009088).

This relationship between the two, however, isn't reflected in the axiom. Maybe in the future this kind of relationship between seed and caryopsis fruit could be encoded so that downstream ontologies like FOODON can benefit from this linkage? For now, according to @cmungall we shouldn't fear multiple inheritance but instead embrace it see his [ontotips post](https://douroucouli.wordpress.com/2019/05/10/ontotip-single-inheritance-principle-considered-dangerous/). 

I take it there is a plan to do something with those FOODON plant terms, such as `grain or seed-producing plant` or `barley plant` now that we have links to NCBI terms like `Hordeum vulgare subsp. vulgare`?

Finally some of these same terms are also included in `foodon_product_import.owl`, which we are also importing from, so we get a duplication of labels, definitions, synonyms,  and sometimes equivalence axioms. 

<img width="414" alt="image" src="https://user-images.githubusercontent.com/12255688/94563032-6a673300-0266-11eb-927b-a7bb6aa8d1e3.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/12255688/94563371-ebbec580-0266-11eb-9342-75e70c99368e.png">

**Comment by kaiiam** [comment]
@ddooley let me know if I should add these last steps of importing the first version of the new robot template, or if you want to hold back to tackle some of these things I've mentioned.

**Comment by ddooley** [comment]
Hi, 
Indeed with the adoption of this robot_organismal_materials.owl file, there are duplicate axioms and some outdated axioms on existing materials that need to be phased out manually.  I will do that, so **if possible I'll accept the pull request WITHOUT the actual import of this file in foodon-edit.owl** , then organize some time today/tomorrow to add the import link into foodon-edit.owl, and look at the 59 CDNO-related terms in it to cull out old axioms.

I'm actually poised to hit the button on another script that deprecates about 1,782 plant and animal FoodOn organisms to their NCBITaxon equivalents.  So that will create quite a polyhierarchy too of NCBITaxon items now also positioned under the remaining foodon more general plant and animal organism hierarchy.  It also shouldn't lead to any issues.  This also means tweaking or dropping a number of axioms that said 'fillet and 'scientific name for herring' etc.

**Comment by kaiiam** [comment]
> if possible I'll accept the pull request WITHOUT the actual import of this file in foodon-edit.owl

@ddooley Done see latest message https://github.com/FoodOntology/foodon/pull/116#issuecomment-700789985 on the PR.

**Comment by ddooley** [comment]
robot_organismal_material.owl is now an include in src/ontology/foodon-edit.owl

**Comment by ddooley** [comment]
And now posted to /foodon.owl

**Comment by kaiiam** [comment]
@ddooley do you ever sleep :P ?

**Comment by ddooley** [comment]
This is now integrated into live foodon release!  Congratulations Liliana, Graham and Kai for contributing so much to this. This table will be growing massively in the next few months.

**Comment by kaiiam** [comment]
Glad we could help

**Comment by LilyAndres** [comment]
Amazing, thanks a lot for all the effort!
