### ISSUE TITLE
NTR: branched chain amino acid-free formula

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#115]
Hi, I am interested in a term such as this for a project. Please feel free to recommend any alterations

Term: branched chain amino acid-free formula
Definition: A dietary supplement formulated to contain little to no branched chain amino acids (BCAA), typically recommended for individuals with Maple Syrup Urine Disease
Parent term: dietary or therapeutic formulation food product(FOODON:00001809), open to recommendations for a preferred parent class, this term denotes it may get merged with ‘dietary supplement’ in the future
Synonyms: BCAA-free medical formula, BCAA-free formula 

An example of a product like this is: https://www.hcp.meadjohnson.com/products/metabolic-products/bcad-1/

**Comment by ddooley** [comment]
Sounds good. I'll leave it open for comment for a week, and then add it in.

**Comment by ddooley** [comment]
Do I call you my definition source?
New term id in foodon draft is: 
http://purl.obolibrary.org/obo/FOODON_00003450

**Comment by laurenechan** [comment]
@ddooley Thanks for getting that started. Here's a source that describes a little more of formula design and composition if you'd like to include that. I can also be the definition source if preferred. 
https://www.sciencedirect.com/science/article/pii/S1096719209005289?casa_token=11OFs4JGaf0AAAAA:vtFdNggBf2dMMPFs-atz6Ezqr5RqB48WUIFp_6nm328MQ2i7Bq7OIpYhL4t0ctmI_sPy9U8uhA
