### ISSUE TITLE
Broken release: robot_organismal_materials does not parse

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#117]
```
<http://purl.obolibrary.org/foodon/imports/robot_organismal_materials.owl> Cause: Problem parsing http://purl.obolibrary.org/foodon/imports/robot_organismal_materials.owl
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
```

Currently breaking pipelines relying on foodon! Thanks for looking into it.

**Comment by ddooley** [comment]
Hmm. The github accessible /imports/robot_organismal_materials.owl (https://github.com/FoodOntology/foodon/blob/master/imports/robot_organismal_materials.owl) seems to open fine in Protege?  Should I test it against robot validate or something?
I'll be able to look into this more at about 4:30 pacific.

**Comment by matentzn** [comment]
Check the purl referenced in foodon.owl:

http://purl.obolibrary.org/foodon/imports/robot_organismal_materials.owl

That does not open in Protege!

**Comment by ddooley** [comment]
That is a redirect to a default page.  And yet Foodon has /imports/robot_organismal_materials.owl tucked alongside all its other import files in github in master, which does open in protege.  Isn't the issue about some kind of cache issue?

**Comment by ddooley** [comment]
Ok, perhaps what is going on is purl.obolibrary.org is using the github foodon latest release file zip?  I'll check if its missing from there.

**Comment by matentzn** [comment]
If you open foodon owl in a text editor, you will see that this import looks a bit different than all the others..

**Comment by ddooley** [comment]
Argh - I see, its the import tag in foodon.owl thats amiss.  Will fix shortly.  Thanks for the debug.

**Comment by ddooley** [comment]
So this should be resolved now.  Thanks for spotting.

**Comment by matentzn** [comment]
Cheers. :)
