### ISSUE TITLE
align with foodie

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#12]
From @Public-Health-Bioinformatics is issue #4 

 http://foodie-project.eu/ 

And they've started their OWL 2 application ontology as FOODIE" https://git.man.poznan.pl/stash/projects/FOOD/repos/model/browse/ Its NOT designed to be compatible with OBOFoundry however, and is focused on agri-sector data gathering as far as I can tell, so we shall persevere with our pure OBOFoundry effort!

**Comment by cmungall** [comment]
OK, this seems more like a schema design for a very particular purpose

These are the classes defined:

```
foodie:Plot
foodie:DoseUnit
foodie:TreatmentPlan
foodie:NutrientsType
foodie:Intervention
foodie:SoilNutrients
foodie:Alert
foodie:PropertyType
foodie:Product
foodie:CropSpecies
foodie:CropType
foodie:Treatment
```

**Comment by Public-Health-Bioinformatics** [comment]
I see what you mean about the schema design.  The ontology link I got off of this [FOODIE slideshow](http://www.capsella.eu/wp-content/uploads/2016/06/CAPSELLA_workshop_FOODIE_1.pdf) .  It may be that only one of the parties in the project has OWL ontology in mind for its work at this point.  Those folks may appreciate FOODON then as a more general resource.
