### ISSUE TITLE
NTR 'High mercury food'

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#126]
Hi, we are interested in a 'high mercury food' term to use as part of an exposure term in ECTO. As this is not a standardized claim, I am open to any recommendations for improving this term!

Term: 'high mercury food'
Parent: somewhere in the 'dietary claim or use' branch? 
Definition: A food product with substantial mercury content which may pose a risk of mercury toxicity in consumers.
Synonyms: 'high mercury containing food', 'mercury rich food' 

FDA does denote that it considers food choices with >0.46 mcg/g methylmercury to be within the 'Choices to Avoid' category if that would be something to include in the definition. This number does appear to be just for pregnant individuals.
https://www.fda.gov/food/metals-and-your-food/technical-information-development-fdaepa-advice-about-eating-fish-women-who-are-or-might-become 

EnvironmentOntology/environmental-exposure-ontology#141

I have some initial concern with trying to use labels like 'abnormal'. I do not know if users will identify the abnormality as "this is an abnormal amount of methylmercury as compared to how much humans should consume" or "this is an abnormal amount of methylmercury compared to how much is typically present in a specific food".

**Comment by ddooley** [comment]
Ok, sounds good.  We'll see if others have any comment on this, and then enter into FoodOn.  We can have the FDA food choices information present in a rdfs:comment note.

**Comment by ddooley** [comment]
Discussed on March 3 call.  - FDA has hazards guide that could be a reference.  Discussing how this could be defined without necessarily committing to what would be a hazardous threshold - which would vary amongst legislative jurisdictions.

**Comment by maweber-bia** [comment]
To address the issue of defining the hazardous threshold, what reusing the PATO:0000069 quality "deviation (from_normal) " and food content range FOODON:03530176 specific to mercury contents which are found in different juridictions ?

**Comment by ddooley** [comment]
I see the 2018 "Hazard Analysis and Risk-Based Preventive Controls for Human Food: Guidance for Industry - Draft Guidance" section 3.4.1.3 mentions heavy metal contamination, and specifically lead, cadmium, arsenic, and mercury. From this, a "**heavy metal contaminated food**" class would be apparent, and under that "**mercury contaminated food**".  A high level "contaminated food" class could exist too, which encompasses other things like dioxins (environmental contaminants).  This leaves open the source of contamination - either a food contact surface, or soil contamination for example, and the concentration of the contamination - so even avoids relative terms like "high".  It seems like a better starting point, and that one could then have a subclass of mercury contaminated food called "high mercury food (FDA reg. ...)" or "high mercury food (EFSA reg. ...)".

**Comment by ddooley** [comment]
And to pick up your comment Magalie, I think yes we could use PATO:0000069 quality "deviation (from_normal) " or more specifically a subclass http://purl.obolibrary.org/obo/PATO_0001162 "increased concentration" which is implicitly from "normal". So "high mercury food (FDA reg. ...)" would have axioms that would state basically 'has quality' some ('increased concentration' and 'concentration of' some mercury).

In ENVO "concentration of" is a class of quality with a pattern, e.g.

    'concentration of carbon dioxide in air' equivalent to: 'concentration of' and ('inheres in' some ('carbon dioxide' and ('part of' some air)))

So

    'mercury concentration in food' equivalent to: 'concentration of' and ('inheres in' some (mercury and (part of' some 'food product')))

Then we could express

    **high mercury food** equivalent to: 'has quality' some ('mercury concentration in food' and 'increased concentration')

I'd have to verify with PATO whether I could make the two qualities a disjunction.

**Comment by laurenechan** [comment]
@ddooley I like your proposition here to include PATO qualities, but I worry with qualities like 'increased concentration', is it going to be clear whether the increased concentration is compared to other foods, as opposed to one piece of tuna has more/less mercury than another piece of tuna? I guess the question is what is the "normal" we are comparing to here.

**Comment by ddooley** [comment]
Working on this in a [google sheet](https://docs.google.com/spreadsheets/d/1NPg1mWzhKbmCCJrCcLkbqMzWwhXy3t7rRxIMsSD0xRU) . Thinking that we can probably use **'has modifier' some abnormal** to mark that something is actually abnormal - which implicitly means with respect to other things of the same kind, right?  Whereas to mark that something is high in potassium in a good way, we can leave abnormal out of it?

**Comment by ddooley** [comment]
Following our discussion this morning, I've left an inquiry on CDNO issues about their 'plant structure' domain and how a more general concentration of X in organism might fit: https://github.com/Southern-Cross-Plant-Science/cdno/issues/51

**Comment by ddooley** [comment]
Damion will follow up with whether CDNO wants to take on toxic substances like mercury.

**Comment by ddooley** [comment]
So it turns out CDNO already has mercury!  I realized as well on the google sheet that FoodOn doesn't really need "high concentration of X in material entity" intermediary terms.  So that leads to patterns like the following (which incorporates an upcoming CDNO change to reference material entities rather than more specific plant structure in its axioms):

![image](https://user-images.githubusercontent.com/4000582/117199001-8a337c00-ad9e-11eb-9a0f-da67b0a59cd0.png)

**Comment by laurenechan** [comment]
@ddooley  Sorry for such a long delay in follow up on this, but did we ever get these terms into food on? Was I supposed to do PRs for this? If so, I'm sorry!!! I can request these now if they haven't already been in the works.

**Comment by ddooley** [comment]
If you are ok with the spreadsheet organization of terms above I can go ahead and mint the three terms shown.  I'll move this sheet to a tab in FoodOn Robot tables spreadsheet too for further management.

**Comment by laurenechan** [comment]
Yes, I think these look great. Thank you for adding them to the Robot tables!

**Comment by ddooley** [comment]
Terms are minted and in foodon draft.

FOODON:00004101 | food material by component concentration | high mercury food material
-- | -- | --
FOODON:00004102 | food material by component concentration | high fructose food material
FOODON:00004103 | food material by component concentration | high fibre food material

**Comment by ddooley** [comment]
I've added the above concentration terms to a new tab called "concentrations" of [FoodOn Robot Tables](https://docs.google.com/spreadsheets/d/1VJtz4m67tdUNDqRe3m1Okdxll64nTR46GSvCOmb0APE). They'll be included in next FoodOn release.
