### ISSUE TITLE
Avoid more than one logical definition on a class

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#127]
I saw this recently:
https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_00003206

This is a bit of an antipattern, because it has some potentially undesirable consequences.. Is a double definition necessary here? ROBOT report actually flags this as an `ERROR`..

**Comment by ddooley** [comment]
It looks like that's a problem with live FoodOn file but which has been fixed in /src folder. I'll update live shortly. 
Thanks for spotting!
