### ISSUE TITLE
Including simple synonyms for X food product e.g. Coriander for Coriander food product

### ISSUE THREAD

**Issue by griffie** [FoodOntology/foodon#132]
Sometimes we will have food descriptions like "Coriander" where we don't know whether it is the coriander leaves, or seeds, or powder that are being used. The logical term would then to be to use "coriander food product" (FOODON:00001763), but that's really wordy for food safety and public health users (they object to the seemingly redundant "food product" bit). 

Can we make simple synonyms (particularly narrow synonyms) for these general food product terms? i.e. corander food product would have a simple synonym "coriander".

Also, the gs1 gpc term "10006054 - coriander (gs1 gpc)" could be linked as a synonym if a FoodOn term was created to mirror the gs1 gpc term.

**Comment by ddooley** [comment]
I think "coriander" can be a narrow synonym for "coriander food product" in the sense that when someone references "Coriander" alone, we're not sure if they mean the plant, the spice, the leaf, etc.  But others can weigh in...!  Similarly "coriander" could be a broad synonym for the seed, the leaf, etc.  Its informatically vague.

**Comment by ddooley** [comment]
Discussed on Foodon curation call: choices:
A) add **narrow synonym** (e.g. coriander) should be narrow synonym for "[organism] food product" class
 - pro: simple; informatically correct if we assume that coriander isn't an informatively concise reference. 
 - con: doesn't necessarily restrict semantic reference to most common uses of the term (coriander = plant, seed or leaf, or powdered coriander, dried, ... ).
B) add broad synonym to organism as a whole, and to any part of that organism.
 - pro: lists off conventional possible references
 - con: complicated visa vis text mining. likely not exhaustive esp. botanicals
 
C) attach "coriander" to "coriander whole or parts" as a synonym.
 - con: different case from other food vegetable references where anatomical part is most likely being referenced (not e.g. plant as whole).

Cucumber case we know organism x part.

Call participants decided to go with A!  Will add to foodon website curation section.
