### ISSUE TITLE
Adding "whole or parts" for foods when it's not clear if they have been cut up

### ISSUE THREAD

**Issue by griffie** [FoodOntology/foodon#133]
Often we have food safety/public health descriptions of food that say something like "Cucumber", where we don't know if they are referring to a whole cucumber of its parts (e.g. slices).

Right now FoodOn has cucumber (whole) and cucumber (whole, raw), but does not offer a term that contains any uncertainty regarding whether the cucumber is intact. It would help to have a class for foods that could be whole or in parts (that could be a synonym for food substance....as long as I can use the "whole or parts" label with the ontology ID).

**Comment by ddooley** [comment]
I had started to use "**[organism X] substance**" rather than "**[organism X] whole or parts**" but I guess the "substance" version is not so attractive?  The whole or parts semantic is equivalent - since the parts could be pureed, chopped, liquified, split, crushed, etc. though this stretches the conventional meaning of "part".  Anyone else have opinions?

**Comment by griffie** [comment]
I think food safety people won't understand what "cucumber substance" means.

But if you make "cucumber (whole or parts)" some kind of synonym, I can use that label instead even if "cucumber substance" is the primary term.

**Comment by maweber-bia** [comment]
I don't understand what a "substance" is in the food processing context

@ddooley what do you mean whith "The whole or parts semantic is equivalent" ? is it equivalent to "substance" ? In this case, why not using "whole or parts" as a preferred label ?

**Comment by ddooley** [comment]
Foodon curation meeting decided to normalize to "[organism part] whole or parts". Damion will implement change for existing substance references.  Understood that whole or parts may involve some degree of mechanical processing.

**Comment by ddooley** [comment]
Additional topic is whether to have a "[organism part] whole or parts" precomposed term for every taxon mentioned in organismal materials?  This covers vague references to food items.

**Comment by ddooley** [comment]
For now we won't precompose "[x] (whole or parts)" for every taxon, we'll just add the term as the need arises.  But we need to formalize the definition to allow all the varieties of food substance (like apple substance) that could be generated by applying processes to some plant or animal as a whole, or to some "whole part":

**food from organism (whole or parts)**
draft definition: a food which is a part of or a mixture of parts of a particular type of organism.
axiom: equivalentTo: 'food (whole, raw)' or 'derives from some 'food (whole, raw)' and derives from only 'food (whole, raw)'

The hierarchy involving "whole or parts" would typically look like this:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/4000582/163239280-291fe06c-9a5f-457b-9e1b-501f1a5ceb78.png">

Feedback appreciated!

**Comment by ddooley** [comment]
This diagram gets at relationship between a sample and the FoodOn product category:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/4000582/163250733-6f518c88-761b-4dcc-b644-ea864daa8237.png">
In red dotted lines show there is a choice of what one can type a sample as, by pointing to more and more specific FoodOn categories.  Alternately one could create a "derives from" object property between a sample and a FoodOn category if the sample doesn't quite fit the category directly.

**Comment by cmrn-rhi** [comment]
## 2022/04/20 - CIDGOH Ontology Curation/Research Meeting
Using the example of `apple` we decided to refer to this generic name in the following way.

`apple` **`exact synonym`** of `apple (whole or parts)`
`apple` **`related synonym`** of `apple (whole, raw)`

We went this way because with many other examples where we wouldn't be referring to `(whole, raw)` and some of us felt it was important that the `exact synonym` was associated with the broadest term, and `related synonym` used in narrower / cognitively biased terms.

But are we referring to "an apple" or "apple"? Usually just "apple". Even the Wikipedia definition isn't so specific as to refer to a whole raw apple, but rather "An apple is an edible fruit produced by an apple tree" (https://en.wikipedia.org/wiki/Apple). But there's that "an" again.

**We'll bring it to the next Joint Food Ontology meeting to see if others in the community agree with this interpretation.**

_For now,_ we'll create `(whole or parts)` versions of terms as they come up in requests, and integrate eventually this into a template that relates it to the other classes like `food product` and smaller parts.

**Comment by ddooley** [comment]
Updated diagram.  I was thinking we could be a bit stronger than "has related synonym" apple.  How about "has broad synonym" apple ?

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4000582/164470027-7f16476f-99f3-435f-b290-d77e98e48001.png">

**Comment by ddooley** [comment]
This would allow us to attach synonyms like "granny smith apple" consistently as shown below.  But an alternative could be to say "**An apple**" is exact synonym for "apple (whole, raw)" ?

<img width="561" alt="image" src="https://user-images.githubusercontent.com/4000582/164473970-d10ec50a-9225-4c62-9e83-c64376ab75a6.png">

**Comment by cmrn-rhi** [comment]
> But an alternative could be to say "An apple" is exact synonym for "apple (whole, raw)" ?

My gut still doesn't like to add the "raw" connotation to "an apple" via exact synonymy (I understand why you feel differently), but I think it's another example worth bringing to the JFO meeting to hear what others think.

Perhaps slightly off-topic, but is it normal/recommended to include indefinite articles (`a`,`an`) in OBOF labels/synonyms? Or even definite (`the`) outside of referencing an ontology name? Quickly reviewing OBOF naming convention documentation I didn't come across any discussion on the matter. 

References:
- https://obofoundry.org/principles/fp-012-naming-conventions.html
- https://doi.org/10.1186/1471-2105-10-125

**Comment by ddooley** [comment]
So I was toying with attaching an "an apple" phrase as an attempt to send a message to users and/or create a computational hook to show which specific concept most likely matches to the cognitive, every day specific term.  Totally open to discussion on how to do this.  Maybe its external to ontology.  But I thought it would be a kind of synonymy.  I.e. recognizing what a phrase points to.  BTW "raw" leaves it open whether apple is fresh, overripe, rotten.  But I suppose "an apple" could be attached to "apple (whole)".

**Comment by ddooley** [comment]
Alternately, we encourage a linguistic parsing.  "an" => whole, "apple" => apple (whole or parts).  "an apple" maybe is a linguistic transform: whole + "apple (whole or parts)" => look for subclass of "apple (whole or parts)" which is a whole thing.

**Comment by ddooley** [comment]
**The curation team decided to have under X food product, a term X which in its definition indicates that it is a whole single fruit or vegetable or mushroom body of that food product category.  This allows us to cleanly connect it to an anatomical part x taxa, which is the fundamental building block on which all other material food term entities can be built.**

We have renamed all "X (whole)" entries to just be labeled "X", e.g. "apple (whole)" is now "apple", implicitly singular, i.e. "an apple".

FoodOn's legacy entries for "plant (whole or parts)" (now renamed "plant (whole or pieces)") will be kept, but into the future to describe part-hood of a sample or ingredient as being in pieces or the ambiguous "whole or pieces", we'll recommend a separate field that focuses on sample or ingredient composition and which uses "animal (whole or pieces)", or "animal piece(s)", and "plant (whole or pieces)" or "plant piece(s)".  This prevents a term combination bomb.

Technically the piece(s) terms imply a BFO "object aggregate" collection with "has member" being a relation to connect any particular piece to the collection, for those who need a precise knowledge graph representation (for robotics, say).
