### ISSUE TITLE
Vegegarian burger: spelling error?

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#134]
Hi, 
I just noticed what I think was a spelling error in the term FOODON:00003177, vegegarian burger. 
I presume this was intended to be vegetarian burger? 
https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_00003177

**Comment by ddooley** [comment]
Thanks!  That's an easy one, and I have fixed in draft!
Cheers,
Damion
