### ISSUE TITLE
NTR: Multiple dietary supplement terms

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#137]
Hello,
I am interested in having a variety of dietary supplement terms added to FoodOn. I've tried to give my best shot at all of these definitions from the lens of what their "traditional/functional" goals for supplementation are, but I did not include any statements on their current status as therapies in research nor their contraindications. Please let me know if adding those would be beneficial. Thank you in advance for any feedback!

Term: Black cohosh supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306), Or please recommend if there is a better location!
Definition: A botanical dietary supplement composed primarily of the root or rhizome of the Actaea racemosa plant, which has been used in functional medicine for management of menopausal symptoms.
Synonyms: black bugbane supplement, black snakeroot supplement, Cimicifuga racemosa supplement
Xrefs: DRON:00020995, DRON:00024242
Logical definition: ‘dietary supplement, herbal or botanical’ and has part some ‘rhizome (PO:0004542)’ and derives from some ‘Actaea racemosa (NCBITaxon:64040)’ 
Sources: https://www.nccih.nih.gov/health/black-cohosh, https://en.wikipedia.org/wiki/Actaea_racemosa 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Coenzyme Q10 supplement
Parent: dietary supplement, metabolite, constituent, extract or isolate (FOODON_03401309), Or please recommend if there is a better location!
Definition: A dietary supplement composed primarily of the ubiquinone coenzyme Q10, which has been used in functional medicine for a wide range of ailments including heart disease and cancer. 
Synonyms: ubiquinone-10 supplement, CoQ10 supplement
Xrefs: DRON:00021427, DRON:00021428, DRON:00024311, DRON:00751502, DRON:00032484, DRON:00024309
Logical definition: ‘dietary supplement, metabolite, constituent, extract or isolate’ and has part some coenzyme Q10 (CHEBI:46245)
Sources: https://www.nccih.nih.gov/health/coenzyme-q10, https://en.wikipedia.org/wiki/Coenzyme_Q10 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Fish oil supplement
Parent: fatty acid or fat/oil supplement (FOODON_03401310)
Definition: A dietary fat supplement composed primarily of fish oil, which has been used in function medicine to reduce cardiovascular disease risk and reduce inflammation.
Logical definition: ‘fatty acid or fat/oil supplement’ and has part some ‘fish oil (FOODON:03306123)’
Sources: https://www.health.harvard.edu/blog/fish-oil-friend-or-foe-201307126467 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Flaxseed oil supplement
Parent: fatty acid or fat/oil supplement (FOODON_03401310)
Definition: A dietary fat supplement composed primarily of flaxseed oil, which has been used in function medicine for a variety of ailments including gastrointestinal complaints and cardiovascular disease. 
Logical definition: ‘fatty acid or fat/oil supplement’ and has part some ‘flaxseed oil (FOODON:00001088)’
Sources: https://www.nccih.nih.gov/health/flaxseed-and-flaxseed-oil 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Ginkgo biloba supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306)
Definition: A botanical dietary supplement composed primarily of the leaf of the Ginko biloba plant, which has been used in functional medicine for a variety of ailments including peripheral artery disease and dementia.
Synonyms: ginkgo leaf supplement
Xref: DRON:00030691, DRON:00022022, , DRON:00022023, DRON:00024375, DRON:00025240
Logical definition: ‘dietary supplement, herbal or botanical’ and has part some ‘leaf (PO:0025034)’ and derives from some ‘Gingko biloba (NCBITaxon:3311)’ 
Sources: https://www.nccih.nih.gov/health/ginkgo, https://en.wikipedia.org/wiki/Ginkgo_biloba 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Ginseng supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306), and ginseng plant food product (FOODON:00001905)
Definition: A botanical dietary supplement composed primarily of the root of the Panax ginseng plant, which has been used in functional medicine to stimulate immune function, improve well-being, and a variety of other health problems.
Synonyms: Asian ginseng supplement
Logical definition: ‘dietary supplement, herbal or botanical’ and has part some ‘rhizome (PO:0004542)’ and derives from some ‘Panax ginseng (NCBITaxon:4054)’ 
Sources: https://en.wikipedia.org/wiki/Ginseng, https://www.nccih.nih.gov/health/asian-ginseng 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Glucosamine supplement
Parent: dietary supplement, metabolite, constituent, extract or isolate (FOODON_03401309), Or please recommend if there is a better location!
Definition: A dietary supplement composed primarily of the amino sugar glucosamine, which has been used in functional medicine for arthritis and pain. 
Logical definition: ‘dietary supplement, metabolite, constituent, extract or isolate’ and has part some glucosamine (CHEBI:5417)
Sources: https://www.nccih.nih.gov/health/glucosamine-and-chondroitin-for-osteoarthritis, https://en.wikipedia.org/wiki/Glucosamine#Manufacturing 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Melatonin supplement
Parent: dietary supplement, metabolite, constituent, extract or isolate (FOODON_03401309)
Definition: A dietary supplement composed primarily of the hormone melatonin, which has been used in functional medicine for circadian rhythm disruption and insomnia.
Xref: DRON:00024422, DRON:00025242, DRON:00751358, DRON:00751109, DRON:00034351, DRON:00034121, DRON:00022387
Logical definition: ‘dietary supplement, metabolite, constituent, extract or isolate’ and has part some melatonin (CHEBI:16796)
Sources: https://www.nccih.nih.gov/health/melatonin-what-you-need-to-know, 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Milk thistle supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306)
Definition: A botanical dietary supplement composed primarily of extract from the seeds of the Silybum marianum plant, which has been used in functional medicine for a variety of ailments including hepatitis, cirrhosis, and diabetes.
Synonyms: silymarin supplement, milk thistle extract supplement
Xref: DRON:00024676, , DRON:00022555, DRON:00022554, DRON:00024434
Logical definition:  ‘dietary supplement, herbal or botanical’ and derives from some ‘Silybum marianum (NCBITaxon:92921)’
Sources:https://www.nccih.nih.gov/health/milk-thistle, https://en.wikipedia.org/wiki/Silybum_marianum, 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Omega-3- fatty acid supplement
Parent: fatty acid or fat/oil supplement (FOODON_03401310)
Definition: A dietary fat supplement composed primarily of omega-3 fatty acids eicosapentaenoic acid (EPA) and docosahexaenoic acid (DHA), which has been used in function medicine for a variety of ailments including hypertriglyceridemia and rheumatoid arthritis.
Narrow synonyms: eicosapentaenoic acid (EPA) supplement, docosahexaenoic acid (DHA) supplement
Xref: NCIT:C120042
Logical definition: ‘fatty acid or fat/oil supplement’ and has part some ‘omega-3-fatty acid (CHEBI:25681)’
Source: https://www.nccih.nih.gov/health/omega3-supplements-in-depth, 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Red yeast rice supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306)
Definition:  A botanical dietary supplement composed primarily of red yeast rice (rice fermented with the mold Monascus purpureus), which has been used in functional medicine to aid in digestion and reduce blood cholesterol.
Synonyms: red fermented rice supplement, red koji rice supplement, angkak supplement
Xref: DRON:00024498, DRON:00032781
Logical definition: ‘dietary supplement, herbal or botanical’ and has part some rice grain food product (FOODON:03301641) and has part some ‘Monascus purpureus (NCBITaxon:5098)’
Sources: https://en.wikipedia.org/wiki/Red_yeast_rice, https://www.nccih.nih.gov/health/red-yeast-rice 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: Resveratrol supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306)
Definition: A botanical dietary supplement composed primarily of resveratrol, which has been used in functional medicine to reduce blood pressure and improve cognition.
Xref: DRON:00033450, 
Logical definition: ‘dietary supplement, herbal or botanical’ and has part some resveratrol (CHEBI:27881)
Sources: https://en.wikipedia.org/wiki/Resveratrol 
Attribution: https://orcid.org/0000-0002-7463-6306

Term: St. john’s wort supplement
Parent: dietary supplement, herbal or botanical (FOODON_03401306)
Definition: A botanical dietary supplement composed primarily of the flower of the Hypericum perforatum plant, which has been used in functional medicine for a variety of ailments including insomnia and depression. 
Synonyms: hypericum supplement
Xref: DRON:00023439, DRON:00023442, DRON:00023441, 
Logical definition: ‘dietary supplement, herbal or botanical’ and has part some ‘flower (PO:0009046)’ and derives from some ‘Hypericum perforatum (NCBITaxon:65561)’ 
Sources: https://www.nccih.nih.gov/health/st-johns-wort, https://en.wikipedia.org/wiki/Hypericum_perforatum 
Attribution: https://orcid.org/0000-0002-7463-6306

**Comment by ddooley** [comment]
Appreciate the additions to FoodOn.   The only thing I suggest is that we move the "which has been used ..." part of your definitions into a separate rdfs:comment annotation.

Also are there ways to reduce shorten the labels of some parents? They were brought in from LanguaL:
"fatty acid or fat/oil supplement"
"dietary supplement, metabolite, constituent, extract or isolate"

Could 
"dietary supplement, herbal or botanical" be covered by "dietary supplement, botanical" or is taking herb out of that not good?

**Comment by laurenechan** [comment]
Agreed, moving the functional medicine descriptors for each to comments sounds good. 
I think we can also likely shorten some of the parent labels:
"fat or oil supplement" seems appropriate. I think it's reasonable to assume that fats and oils includes fatty acids.

"dietary supplement, metabolite or precursor" might be an option. I am uncertain what is intended by the inclusion of constituent. Also, extract or isolate could be terms that refer to botanicals which might lead to misclassification. Does this seem like a reasonable compromise to align specifically with the definition ("Includes hormone precursors; steroid precursors; 7-dehydrocholesterol, lutein, omega-3's, CoQ10")? 

"dietary supplement, botanical" sounds good to me, as it appears [herbs are considered a subclass of botanicals](https://ods.od.nih.gov/factsheets/BotanicalBackground-Consumer/#:~:text=A%20botanical%20is%20a%20plant,%2C%20botanical%20products%2C%20or%20phytomedicines.)

**Comment by laurenechan** [comment]
Per FoodOn meeting June 2: I will put this together as a ROBOT import, take a first pass at the initial template and will post for review. Look at organismal table for examples of headers. Will also make sure to add lipid as a synonym within the fat or oil supplement parent class, can update parent classes in PR. Will move the pieces of the functional use to the comment parts.

**Comment by laurenechan** [comment]
I put together a preliminary ROBOT template for this set of terms and future dietary supplement terms. I had a few questions regarding this template as well, 1) do FoodOn editors have a range of Term IDs? How do I see those/request my own range? 2)What column do I include information about xrefs? 3) I removed the variety of columns for translations to make it easier to handle the spreadsheet size, but should I add them back in now? 4)I did not include a curation status, but can if there is a preferred approach to doing that. 

One other note, I will try to get a PR open for the small changes to the parent class names. They are in the 'new' version in this spreadsheet and will need to be updated in master prior to merging this file. 

spreadsheet is [here](https://docs.google.com/spreadsheets/d/1KYjblhfESO39PgMuAyAjlOewP_w2e0E54i_2_E_krTQ/edit?usp=sharing)

**Comment by ddooley** [comment]
Hi,
- Yes we can set up a range of editing IDs for you.
- can use the http://www.geneontology.org/formats/oboInOwl#hasDbXref annotation for xrefs or http://www.w3.org/2000/01/rdf-schema#seeAlso for "see also" urls
- its fine not to have translation columns.
- Usually in this process we'd have a curation status, and with a big batch of terms that we finesse on the spreadsheet, would just give them all IAO "ready for release" after reviewing each definition.  Then for additional terms added later they can have the IAO 'requires discussion'.

**Comment by laurenechan** [comment]
@ddooley I've made edits to the ROBOT template spreadsheet linked above based on your comments and thank you for merging in the label changes for the parent classes. I think that was all we needed prior to moving forward with this spreadsheet? Are there any other tidbits we wanted to change before we set up ingesting this template? I am unfamiliar with this workflow so guidance in doing so would be much appreciated!

**Comment by laurenechan** [comment]
Hi @ddooley just checking back on this issue, did you have a chance to check out the revised ROBOT template? Thank you!

**Comment by ddooley** [comment]
Just incorporating the robot file now.  Sorry for delay - paper and grant writing maelstrom!

**Comment by ddooley** [comment]
About "dietary supplement, botanical’ and 'has part' some ‘rhizome’ and 'derives from' some ‘Panax ginseng’" . There are several kinds of Ginseng.  Did you want to reference just the Chinese/Korean root?  Also is PO "root" better than "rhizome" or is root too general?  I can change the organismal materials reference to point to rhizome rather than root if necessary. I looked up "is a rhizome a root" on google and it pointed to rhizome being more of a horizontal form of root.

**Comment by ddooley** [comment]
I've added the necessary CHEBI and NCBITaxon terms; but left one other question about Ginkgo balboa in there: "should we have a ginkgo bilboa leaf" organismal material?  Also is this supplement ground leaf, or is it a liquid extract?

**Comment by laurenechan** [comment]
Awesome, thank you @ddooley! 
For ginseng, I think 'root' is suitable for this purpose. I believe Asian ginseng is the most commonly used in alternative medicine so I think that would be appropriate for us to just reference to that. 

As for Ginkgo biloba supplement, the supplements currently used have extract from ginkgo leaves. Would having 'ginkgo biloba leaf' as an organismal material be helpful in speaking to what the source of the extract is?

**Comment by ddooley** [comment]
Maybe we should qualify "ginseng supplement" as "ginseng supplement (from Panax ginseng)"; and give it a broad synonym "Panax ginseng".  Or is that too persnickety?

**Comment by laurenechan** [comment]
@ddooley I think that's fine. Maybe then we can/should also include a 'ginseng supplement (from Panax quinquefolius)' term and a 'ginseng supplement (from Eleutherococcus senticosus)'? Then we would have Asian, American, and Siberian all represented

**Comment by laurenechan** [comment]
@ddooley Thanks for meeting today, I've updated all of the terms that include extract components and added a few organismal materials to the spreadsheet you shared. Please let me know if anything else looks out of place!

**Comment by ddooley** [comment]
This has been implemented now in a dietary supplement robot file!

**Comment by mateolan** [comment]
Just seeing and reading through this chain now--I wanted to alert you that, regarding comment on May 21, 2021, 

>I think we can also likely shorten some of the parent labels: "fat or oil supplement" seems appropriate. I think it's reasonable to assume that fats and oils includes fatty acids.

Although the FAs in the supplements in the linked spreadsheet seem fine, fatty acid supplements are not always in an oil form, and are often in a salt form that spilt into cations and carboxylates when metabolized (no oil involved). This impacts the definition of fatty acid supplement. For examples see https://efsa.onlinelibrary.wiley.com/doi/full/10.2903/j.efsa.2018.5180
Cheers,
~Matthew

**Comment by laurenechan** [comment]
Hi @mateolan , thanks for the thoughts. I'm wondering with the fatty acid soaps, would you still consider them to be a fat? would you consider them to be a fatty acid? or are they actually better suited for a more specific subclass that speaks to them being a soap/salt form? If they are considered a fat/fatty acid, I'm not certain I see the issue with the current label being that it's fat OR oil supplement and broadly I would categorize a fatty acid as a fat (although we could get into further semantics on that as well).

**Comment by mateolan** [comment]
I would suggest linking to the lipidmaps.org classification system, like in
this case:
https://www.lipidmaps.org/data/structure/LMSDSearch.php?Mode=ProcessClassSearch&LMID=LMFA01

**Comment by ddooley** [comment]
What is the actionable change to FoodOn to do here?

**Comment by laurenechan** [comment]
Hi @ddooley I believe from the Aug 23 message from @mateolan  it sounds like the particular supplements described in the spreadsheet are ok, but there may be some considerations for future fat salt based supplements. I do not have any further supplements to suggest adding to FoodOn at this time, so unless Matthew has specific changes to be made then I think this is a future recommendation, but not an action item.

**Comment by Shaen-12** [comment]
Top 10 Seeds for diabetes patients- Freedom from Diabetes
The most commonly used food items are grains, vegetables, fruits, and animal products.  All of us will agree that seeds fall into a much neglected and underused category. But it should not be so... Actually they are a "powerhouse" of lots of vitamins, minerals, and antioxidants and should be included in the daily dietary regimes. In this article, we will discuss some of the best seeds for diabetes patients.
https://www.freedomfromdiabetes.org/blog/post/top-10-seeds-for-diabetes-patients--freedom-f/2568

**Comment by ddooley** [comment]
@Shaen-12 we have an upcoming foodon plant x anatomical part module that covers seeds better than the add-hock curation table or foodon-product-import.ofn file right now.  However, that will take some time to finish, so if you would like to have particular seeds added that FoodOn is currently missing, then you are welcome to set up a new issue naming each seed and hopefully the scientific taxon it is from. Note we would not put these in the category of dietary supplements directly although I recognize supplement products can be made from seeds.
