### ISSUE TITLE
Which open source license should be adopted?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [FoodOntology/foodon#14]
I was doing the OBOFoundry submission for this, and I see they want licence info on file.

d.

**Comment by mcourtot** [comment]
http://www.obofoundry.org/principles/fp-001-open.html

Most resources are CC-by, though a few are CC0, and the former can always be 'relaxed' into the latter.

**Comment by Public-Health-Bioinformatics** [comment]
We are now officially CC-BY (possibly in the future we'll switch to CC-0 if feasible considering that Foodon draws on CC-BY ontologies.)
