### ISSUE TITLE
Change class name "european grape plant" to "common grape plant"

### ISSUE THREAD

**Issue by DianeKEPR** [FoodOntology/foodon#141]
Propose changing the name of class "european grape plant" to "common grape plant". 
Wikipedia uses "common grape plant" in as the title when looking up "vitus vinifera.
https://en.wikipedia.org/wiki/Vitis_vinifera
The term "european grape plant" is not found in a Wikipedia search, and also implies a geographic reference that does not fit many instances of Wine.  Wikipedia text:
Vitis vinifera, the common grape vine, is a species of flowering plant, native to the Mediterranean region, Central Europe, and southwestern Asia, from Morocco and Portugal north to southern Germany and east to northern Iran.
"european grape plant" was imported from langual.org; propose the term be made a synonym.

**Comment by DianeKEPR** [comment]
For consistency, this class should be renamed "Vitis vinifera"  with use of Latin names for whole organisms in Foodon.   "common grape plant" should be added as a synonym, "european grape plant" should become a synonym.

**Comment by ddooley** [comment]
Ok, I see in this case we need to deprecate our "european grape plant" entry and replace it with NCBITaxon "Vitis vinifera".  Then as you say we'll add those two exact synonyms! Then all the wine varietals will appear below Vitis vinifera that were under European grape plant.  I'll do that on next release.

**Comment by ddooley** [comment]
There is a separate wine varietal robot template file which will need to be updated a bit for the change in parent class.  Term is now deprecated in foodon-edit and replaced with NCBITaxon. 
Robot file needs refresh and change will be available in next release.

**Comment by ddooley** [comment]
Robot file is updated, so I think this can be closed now!
