### ISSUE TITLE
Change class name "Vitis amerensis" to "Amur grape plant"

### ISSUE THREAD

**Issue by DianeKEPR** [FoodOntology/foodon#143]
Proposed: Change class name "Vitis amerensis" to "Amur grape plant"   be consistent with use of Latin and common names
The Amur grape plant is a species native to the Asian continent.  Its name comes from the Amur Valley in Russia and China.  The Amur grape is hardy in climates too cold for most grape plants.  It is very resistant to frost, but not tolerant of drought.
https://en.wikipedia.org/wiki/Vitis_amurensis

**Comment by ddooley** [comment]
In FoodOn draft we now have Amur grape plant as synonym and alternative term on Vitis amerensis!

Thanks,

Damion
