### ISSUE TITLE
modeling relative intakes of different types of food

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#15]
We need an OWL design pattern and possible materialized pre-composed classes representing relative intakes, e.g. reduced fruit/vegetable in diet, increased sugar from carbonated beverages. This is for https://github.com/cmungall/environmental-conditions/

The food classes would themselves come from foodon. But I would suggest that the intakes are represented as activities and live somewhere else. These may naturally cluster with activities in a physical activity ontology (e.g. sedentary activity, exercise activity, cc @mateolan )

**Comment by mateolan** [comment]
Agreed, definitely have been working on including eating and eating
patterns in the physical activity ontology . We just need to get Physical
Activity ontology pushed up to GitHub to make this more seamless. Love your
help with that. ;-)

**Comment by ddooley** [comment]
This issue may have resolution now in the Ontology for Nutritional Studies (ONS) which handles dietary pattern.  See: https://github.com/enpadasi/Ontology-for-Nutritional-Studies
