### ISSUE TITLE
NTR: a variety of food terms

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#153]
Hello,
I've created a ROBOT template for my proposed terms [here](https://docs.google.com/spreadsheets/d/1Pfds0H40mT6XgXdUSKirQmPpI5E-eLJ2ZqDmo0sfKsA/edit?usp=sharing) and am very open to any feedback you have. These are requested terms that stem from alignment efforts between an NIEHS survey about food and exposures and FoodOn terms. I know these foods are also not all aligned with one another, so if they should be organized in a different fashion please let me know. Thanks!

**Comment by ddooley** [comment]
Seems like these are all sorted!
