### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#16]
There has been no release since we moved ENVO foods into FOODON. This makes FOODON look rather sad in OLS, OntoBee etc.

Who is release manager? @Public-Health-Bioinformatics? Shall I cut an interim release?

**Comment by Public-Health-Bioinformatics** [comment]
I'm on vacation for 1 week, till next monday.  I haven't actually studied the release cycle setup on this. I'm fine with you cutting an interim release - as long as Pier has deemed the export of ENVO terms into it to be a success?  
Q for your Chris - do we need to get OntoBee to import FOODON, or is this now done automatically via its entry in OBOFoundry?

**Comment by cmungall** [comment]
On 8 Aug 2016, at 17:18, Damion Dooley wrote:

> I'm on vacation for 1 week, till next monday. I haven't actually 
> studied the release cycle setup on this. I'm fine with you cutting an 
> interim release - as long as Pier has deemed the export of ENVO terms 
> into it to be a success?

I'll check

> Q for your Chris - do we need to get OntoBee to import FOODON, or is 
> this now done automatically via its entry in OBOFoundry?

Not sure exactly what you're trying to do but you shouldn't need OntoBee

If you want to import all of food on, just add an imports directive to 
the ontology PURL, http://purl.obolibrary.org/obo/foodon.owl

If you want to make a module and import that, you can use ROBOT or 
OntoFox

**Comment by Public-Health-Bioinformatics** [comment]
Oh, I meant by "do we need to get OntoBee to import FOODON" that I wonder how to get OntoBee to list FOODON as one of the ontologies one can search for terms?  You mentioned FOODON looks rather sad in OntoBee - I couldn't even find it there.

When I return I'll focus on how to get FOODON to contain all Langual Food Source terms and their NCBI_Taxon related entries.

**Comment by cmungall** [comment]
On 8 Aug 2016, at 17:28, Damion Dooley wrote:

> Oh, I meant by "do we need to get OntoBee to import FOODON" that I 
> wonder how to get OntoBee to list FOODON as one of the ontologies one 
> can search for terms? You mentioned FOODON looks rather sad in OntoBee 
> - I couldn't even find it there.

May be a lag, or it got stuck. In theory it picks it up automatically. 
Sometimes you have to email them. OLS is more reliable that way

> When I return I'll focus on how to get FOODON to contain all Langual 
> Food Source terms and their NCBI_Taxon related entries.

OK!

**Comment by mateolan** [comment]
@Public-Health-Bioinformatics are we any closer to a release of your LanguaL integration stab that we can look at?

**Comment by Public-Health-Bioinformatics** [comment]
Just working on it now.  Probably another day, so tuesday morning I expect a candidate which I'll post to: https://github.com/Public-Health-Bioinformatics/foodon-langual

**Comment by Public-Health-Bioinformatics** [comment]
Chris, I did a make on a local copy of the foodon repo to see how the process works (I did have to clear out the old foodon.owl file in order to have it create a new version with foodon-edit.owl changes.)
**What I found was that "make release" didn't work** - at least on my brand of make/bash.  It was the $RELEASE instead of $(RELEASE) .  New code for this below; do you want me to do a pull request?

```
release: $(ONT).owl
# $(ONT).obo # disabled for now
        cp $^ $(RELEASEDIR)/.
        mkdir -p $(RELEASEDIR)/imports/ && cp imports/* $(RELEASEDIR)/imports/
```

**Comment by Public-Health-Bioinformatics** [comment]
Question: I see the food product terms coming from ENVO now often have a "hasDbXref" annotation on their obo:IAO_0000115 definitions indicating the source of the definition.  Any objection to simplifying this to be an IAO_0000119 "definition source" directly on the term class?  (The annotation on the definition is basically doubling the size of the ENVO term import).

**Comment by cmungall** [comment]
> Any objection to simplifying this to be an IAO_0000119 "definition source" directly on the term class

This would affect the obo translation, see line 2:
http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.6

IAO_0000119 is intended as a class annotation, not an axiom annotation

you can use the obo plugin to make editing of text defs etc

**Comment by cmungall** [comment]
> What I found was that "make release" didn't work - at least on my brand of make/bash. It was the $RELEASE instead of $(RELEASE) . New code for this below; do you want me to do a pull request?

yes let's follow up on the starter kit tracker, I don't follow the issue here. Note that you can just go ahead and do everything on a branch here for now & we can sort things out there

**Comment by Public-Health-Bioinformatics** [comment]
Thx for quick feedback.  About IAO_0000119, I meant what you say, that it would annotate the term class (e.g. milk FOODON_00001217), rather than the term's definition (IAO_0000115).  But I see now from your OBO doc link that "Note we have no cognate of IAO:definition_source - we would have a generic xref annotation on the definition annotation assertion"  So I guess OBO shies away from use of IAO_0000119 in order to accommodate a situation where there could be more than one definition for a class?  So no IAO_0000119 allowed in FoodOn?

**Comment by cmungall** [comment]
On 26 Sep 2016, at 9:08, Damion Dooley wrote:

> Thx for quick feedback. About IAO_0000119, I meant what you say, that 
> it would annotate the term class (e.g. milk FOODON_00001217), rather 
> than the term's definition (IAO_0000115). But I see now from your OBO 
> doc link that "Note we have no cognate of IAO:definition_source - we 
> would have a generic xref annotation on the definition annotation 
> assertion" So I guess OBO

OBO as in syntax here, yes

> shies away from use of IAO_0000119 in order to accommodate a situation 
> where there could be more than one definition for a class? So no 
> IAO_0000119 allowed in FoodOn?

we don't expect >1 def per class, but IMO it's good to be uniform, we 
annotate all other axioms such as synonyms in the same way

**Comment by Public-Health-Bioinformatics** [comment]
Ok.  I'm using Protege 5 beta ... is that why I don't see any OBO plugin option?  

One last basic question: Paraphrasing, I was using <hasDbXref>ITIS:173444</hasDbXref> to make a reference to what isn't quite a URI resource record, the "european frog" record in www.itis.gov which has id 173444 and a more obscure search URL to get to it.  Am I misusing hasDbXref in this way? For references that aren't quite URI's, wouldn't it be better to have something like a 

```
<Class about="&obo;FOODON_03413462"> 
   ...
   <hasDbId>
      <dataSource>ITIS</dataSource>
      <dataId>173444</dataId>
   </hasDbId>
</Class>
```

 class annotation?

**Comment by Public-Health-Bioinformatics** [comment]
Closing this now.  A few Alpha releases have been committed at this point.
