### ISSUE TITLE
Is diet a material entity, process, or quality? 

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#160]
Hello,
I was on a call with ECTO curators this morning and we were discussing the use of diet within one of our exposure terms. We were having some difficulty identifying if 'diet' in ONS is considered a material entity, process, or quality. And in particular, with COB in mind, is there a specific upper level for COB that diet may fall under?

**Comment by FrancescoVit** [comment]
Hello! 
Damion reported to me this issue which basically refers to how ONS model the diet.

In ONS the diet has always be seen as an "information content entity" [IAO:0000030] under the _generically dependent continuant_ . 

The idea is that the diet is hardly something material or tangible, but rather is defined as the succession of eating and drinking in a certain period of time, hence connected and defined by a "dietary pattern" concept (which both is and information content entity). Having a look at COB, using the same conceptualization, would be under the "_information_" upper level

The most appropriate term (also depending on your specific needs), could be "dietary pattern"; but not in its current definition. I also discussed this during IFOW in Bolzano, and probably will create a second, "companion", class for dietary pattern not resulting from observation, but general as a reference (that is, not a dependent continuant). Will have an issue short about this, that I could also link here.

We are open and very interested in discussion on those concepts, which are becoming central for ONS. Eventually the [ONS issue tracker](https://github.com/enpadasi/Ontology-for-Nutritional-Studies/issues) or even the [JFOW](https://github.com/FoodOntology/joint-food-ontology-wg/issues) one, could be a more adequate place for this discussion in detail.

**Comment by ddooley** [comment]
@laurenechan does this answer/resolve your question?

**Comment by laurenechan** [comment]
Hi @ddooley and @FrancescoVit thank you for this information and my apologies for the delayed response. I believe this does answer my question, and I think ECTO will be interested in continuing more conversation on the ONS tracker as we get closer to modeling exposure to diet in the future. 
In the meantime, did we ever get the IFOW videos posted somewhere for viewing?

**Comment by ddooley** [comment]
I just heard the videos should be ready tomorrow. I'll post them at https://github.com/FoodOntology/joint-food-ontology-wg/tree/master/presentation along with the accepted paper list link.
