### ISSUE TITLE
CHEBI:alcohol SubClassOf 'alcoholic beverage'

### ISSUE THREAD

**Issue by balhoff** [FoodOntology/foodon#161]
FOODON includes an axiom stating `CHEBI:alcohol SubClassOf FOODON:'alcoholic beverage'`. Shouldn't this instead be something like: `FOODON:'alcoholic beverage' SubClassOf 'has part' some CHEBI:alcohol` (and probably more specifically ethanol)?

The current axiom injects semantics into CHEBI by asserting that all kinds of alcohols are beverages.

**Comment by cmungall** [comment]
linking to seperate injection ticket: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1443

**Comment by ddooley** [comment]
Thanks for raising this.  I've made the correction with your suggestion, using ethanol, and this is now in latest foodon draft.

**Comment by balhoff** [comment]
Thanks @ddooley!
