### ISSUE TITLE
incorrect equivalence axiom for hominy

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#163]
Discovered by @wdduncan in ENVO build: https://github.com/EnvironmentOntology/envo/pull/1240

http://purl.obolibrary.org/obo/FOODON_03310226 hominy
equivalentTo
'corn food product' or 'corn (on-the-cob, kernel or parts)'

this is clearly incorrect and is causing equivalence between named classes:

![image](https://user-images.githubusercontent.com/50745/142055591-38efe44e-9570-48dc-8061-61d098e1b9d4.png)

My immediate recommendation is that after fixing this, use robot to fail fast if equivalencies detected

See
http://robot.obolibrary.org/reason#equivalent-class-axioms

Also https://douroucouli.wordpress.com/2018/09/04/debugging-ontologies-using-owl-reasoning-part-2-unintentional-entailed-equivalence/

My next recommendation would be to very careful with equivalence axioms. Only use them if the term conforms to a documented DP

If the term doesn't have an or in the label, be suspicious of any class forming to a A or B equiv axiom

See also

 - https://douroucouli.wordpress.com/2019/07/29/ontotip-dont-over-specify-owl-definitions/
 - https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/, specifically S11

it is a red flag if text and logical definitions don't match

_Hominy is a food produced from dried maize (corn) kernels that have been treated with an alkali, in a process called nixtamalization (nextamalli is the Nahuatl word for "hominy")._

!=

'corn food product' or 'corn (on-the-cob, kernel or parts)'

Consider a DP for produced-by-process

remember it's better to have no equivalence axiom than an incorrect one

**Comment by ddooley** [comment]
I think this is a case of two errors - the "or" is supposed to be an "and", and the equivalency mistakenly got applied to the wrong entity.  This equivalency is removed; I'll get it rolled out to OntoBee etc.

Thx for robot tip. I'll explore what the equivalency report yields.  I'm thinking we want inferred equivalencies but not explicit ones - which I presume occur when one accidentally puts a disjunction between atomic entities in the equivalency expression.

**Comment by ddooley** [comment]
Also, I've run the robot equivalency report and found a number of other equivalency errors related to the new plant_part_import.owl file we did, so thanks for that tip.  Going forward releases will be tested against this report.
