### ISSUE TITLE
Add obsolete property to all obsolete terms

### ISSUE THREAD

**Issue by janelomax** [FoodOntology/foodon#164]
Hi - there are a number of classes e.g. 
```
obsolete: sorghum plant
http://purl.obolibrary.org/obo/FOODON_03411448 
```
that are obsolete, but only have a replaced_by property assigned, not the obsolete property (`http://www.w3.org/2002/07/owl#deprecated`). 

In addition, there are several classes where the derived_from points to one of these obsolete classes e.g `http://purl.obolibrary.org/obo/FOODON_03301849` points to `http://purl.obolibrary.org/obo/FOODON_03411448 
`

Would it be possible to assign obsolete properties to all these terms, and update the derived_from relations?

**Comment by ddooley** [comment]
Hmm.  When I look at sorghum plant in protege I see:
![image](https://user-images.githubusercontent.com/4000582/142732428-fa1b5b51-a9d8-4c5d-a95d-28b4460316bd.png)

Now I do recall one inconsistency - that a number of these have data type xsd:boolean, while others have none (when I found that Protege didn't care about the boolean datatype).  What is the correct data type for that, or do your import systems care?

I'll definitely fix the derives from issue!  Thanks for spotting that.

Thx,

d.

**Comment by janelomax** [comment]
Oh yeah it looks like a bug something at our end - when you check in the file the `owl:deprecated` tags are all in there they're just not showing up in centree so don't worry about that. 

If you could fix the derives from thing that would be great though - thanks!

Jane

**Comment by janelomax** [comment]
In addition, these 4 classes are showing up as orphans, looks like it's because their only superclass is now obsolete:

http://purl.obolibrary.org/obo/FOODON_03411072
http://purl.obolibrary.org/obo/FOODON_03401012
http://purl.obolibrary.org/obo/FOODON_03412038
http://purl.obolibrary.org/obo/FOODON_03400994

**Comment by ddooley** [comment]
The above orphan cases should be fixed now in foodon-edit.owl 
We have tasked one of our staff to develop a SPARQL set of queries to recognize and replace reference to deprecated terms, so that should be resolved before end of January.

**Comment by ddooley** [comment]
In foodon-edit.owl the deprecated terms should now have related axioms replace their references with the replacement terms.  This will be included in next release.  I'll close this now.
