### ISSUE TITLE
Some classes below "food product" have disappeared in Ontobee.

### ISSUE THREAD

**Issue by cmchien** [FoodOntology/foodon#167]
Apologies if this is not the right place to open the issue. I'd be happy to be redirected.

The class "food product" ([Ontobee]( http://www.ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_00001002)) previously had multiple children visible in Ontobee that matched what is shown in the documentation [here](https://foodon.org/food-facets/food-product/).

At least as of 11/22/2021 links like this: http://www.ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_00002381 worked. 

But many of these, including "food product by organism", seem to have disappeared as of 11/30/21

Have these classes/terms been removed from FoodOn?

**Comment by ddooley** [comment]
Thanks for reporting that!  I'll check with OntoBee. It looks like they did a partial load of FoodOn and then something failed. You can get the complete view as a workaround at: https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_00001002

Cheers,

Damion

**Comment by cmchien** [comment]
Thanks @ddooley! We suspected that something like that might be the case, but (being rather new to FoodOn) were concerned that perhaps FoodOn had decided not to support those terms anymore--which would have been a big loss for us.  Thanks for pointing us to the ebi.ac.uk site. You all have done amazing work here!

Chi-Ming

**Comment by ddooley** [comment]
This is resolved with an ontobee update!

**Comment by cmchien** [comment]
Thanks @ddooley!
