### ISSUE TITLE
long grain rice kernel wrong superclass

### ISSUE THREAD

**Issue by marieALaporte** [FoodOntology/foodon#189]
'long grain rice kernel' is currently classified under 'maize kernel'. It should rather be placed under 'rice food product' or one of its subclasses.

**Comment by marieALaporte** [comment]
The class has dual parentage, so the 'maize kernel' superclass should be removed. Thanks !

**Comment by ddooley** [comment]
Thanks for finding that.  I see it was a data entry error in our robot table. Its fixed now and in foodon-edit.owl so will be fixed in next foodon publish.
