### ISSUE TITLE
green bean pod

### ISSUE THREAD

**Issue by marieALaporte** [FoodOntology/foodon#198]
Looking at the definition of the class 'green bean pod' (http://purl.obolibrary.org/obo/FOODON_03305806), I believe the class name should mention whole and raw, as other classes.

**Comment by ddooley** [comment]
You will be happy to know that we have that as a new term in the foodon draft! 
 "green bean pod (whole, raw)".  Here's the id for it: http://purl.obolibrary.org/obo/FOODON_00004236 . It will be in live version in a few weeks.
