### ISSUE TITLE
Transfer ENVO classes

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#2]
The [Environment Ontology](https://github.com/EnvironmentOntology/envo/) currently hosts quite a few food related classes that should be transferred to FoodOn. They are in the import chain as of a0cd4c18cb68c6448e50106575c9d37dc2eb8848 and their PURLs are listed in the pre-release [envo_terms.txt](https://github.com/FoodOntology/foodon/blob/master/src/ontology/imports/envo_terms.txt).

@cmungall - should these be left as imports or should we 'move' them to FoodOn? I'm leaning towards the latter as they should probably be under the control of FoodOn rather than EnvO. Is there an up-to-date best practice on doing such an operation?

**Comment by cmungall** [comment]
The cleanest thing to do is to obsolete the food classes in ENVO, and add corresponding classes in FOODON (with replaced_by links). This could be done automatically. The disadvantage is that this would cause some churn if people have used those ENVO IDs.

What I wouldn't do is transplant the existing classes unaltered into FOODON. Technically OK, but a massive headache.

I think go for the clean route. Not sure how much churn this would cause as it's hard to tell which ENVO IDs are in use out there

**Comment by pbuttigieg** [comment]
I'm for the clean route too. The churn is something that will come sooner or later and ontology consumers should be ready to act on `replaced_by` links. 

I suppose the `replaced by` links will be inside ENVO, as it will import the obsoleted ENVO classes from FOODON. Is this right?

**Comment by cmungall** [comment]
> I suppose the replaced by links will be inside ENVO

correct

> as it will import the obsoleted ENVO classes from FOODON. Is this right? 

We could do it this way. At the moment many ontologies have dangling replaced-bys.

Note the default behavior for the 'basic' subset is to remove classes with non-ENVO ID spaces, e.g. CHEBI. This would extend to FOODON too. So even if we keep a subset in via imports in the main one, the basic subset (which many obo users use) would omit this.

I think I am in favor of not importing FOODON even in the main. FOODON could grow to be large, and the current subset of foods is semi-arbitrary. It's a bit simpler if the consumer simply decides for themselves if they want food, and if so, what portion.

**Comment by cmungall** [comment]
I'll write this and we can do it this way: https://github.com/ontodev/robot/issues/65

**Comment by Public-Health-Bioinformatics** [comment]
I have a few basic questions as I get up to speed.  Are terms marked obsolete by a particular annotation?  I see "depreciated" in my annotation properties list but can't find anything else pertinent except 'has obsolescence reason' in an ontology Melanie set up for us.  Similarly is 'replaced_by' an annotation?

ciao,

**Comment by cmungall** [comment]
I recommend getting the obsoletion plugin, it will do this for you within Protege: http://wiki.geneontology.org/index.php/Ontology_editor_plugins

But note for this case we're doing a mass sweep via script, not in Protege
