### ISSUE TITLE
NTR: multiple packaging terms

### ISSUE THREAD

**Issue by KaylaPenn** [FoodOntology/foodon#203]
# NTR: no container

## Parent Term/Class:
‘food packaging’ FOODON:03490100

## Definition: 
lack of container, packaging or wrapping

# NTR: consumer-ready packaging

## Parent Term/Class:
‘food packaging’ FOODON:03490100

## Definition: 
container, packaging or wrapping intended for the consumer to remove or open to access food material

# NTR: in bulk, intended for repackaging

## Parent Term/Class:
‘food packaging’ FOODON:03490100

## Definition: 
container, packaging or wrapping intended to be removed for partitioning of food material before the food is obtained by a consumer

**Comment by ddooley** [comment]
Thanks for these.  I'll tweak the labels to include "food" in them, to constrain to food related stuff ok?  So:

"consumer-ready food packaging"

Now the "food in bulk, intended for repackaging" term seems to be referring to the food, not the package?  Or should this term refer to the bulk packaging? So perhaps:

"wholesale food bulk packaging" ?

In FoodOn so far we have refrained from defining negated term classes such as "no packaging", but I imagine you want this for a code in a database picklist?

**Comment by KaylaPenn** [comment]
Those modifications sound good! I'll get back to you on the 'no packaging'.

**Comment by cbarcl01** [comment]
Hi Kayla, following your new term requests we've added the following terms to FOODON:

- no container = **unpackaged or non-packaged food** FOODON:03601004
- consumer-ready packaging = **consumer-ready food packaging** FOODON:03601005
- bulk, intended for repackaging = **wholesale food bulk packaging** FOODON:03601006

We have also added the following subclasses to unpackaged and non-packaged food:
- **unpackaged food** FOODON:03601007
- **non-packaged food** FOODON:03601008

These will be available in the next foodon release, or alternatively you can view them now in the latest [foodon-edit.owl](https://github.com/FoodOntology/foodon/blob/master/src/ontology/foodon-edit.owl)

**Comment by KaylaPenn** [comment]
Thank you!
