### ISSUE TITLE
NTR: multiple packaging integrity terms

### ISSUE THREAD

**Issue by KaylaPenn** [FoodOntology/foodon#204]
# NTR: food packaging integrity

## Parent Term/Class:
‘food object quality’ FOODON:0002470

## Definition: 
quality of the stability and completeness packaging material

# NTR: food packaging intact

## Parent Term/Class:
'food packaging integrity' (above)

## Definition: 
container, packaging or wrapping in original form and undisturbed

# NTR: food packaging not intact

## Parent Term/Class:
'food packaging integrity' (above)

## Definition: 
container, packaging or wrapping not in original form and/or noticeably disturbed

# NTR: food packaging opened by consumer

## Parent Term/Class:
'food packaging not intact' (above)

## Definition: 
container, packaging or wrapping opened by consumer

**Comment by ddooley** [comment]
For "food packaging not intact" how about "food packaging compromised" to line up with "food packing medium compromised"?

**Comment by KaylaPenn** [comment]
Yep!

**Comment by cbarcl01** [comment]
Hi Kayla, following your new term requests we've added the following terms to FOODON:

- food packaging integrity = **food packaging integrity** FOODON:03601000
- food packaging intact = **food packaging intact** FOODON:03601001
- food packaging not intact = **food packaging compromised** FOODON:03601002
- food packaging opened by consumer = **food packaging opened by consumer** FOODON:03601003

These will be available in the next foodon release, or alternatively you can view them now in the latest [foodon-edit.owl ](https://github.com/FoodOntology/foodon/blob/master/src/ontology/foodon-edit.owl)

**Comment by KaylaPenn** [comment]
Thank you!
