### ISSUE TITLE
Irregular/incorrect hierarchies

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#206]
Hello, we are ingesting FoodOn into ECTO and are seeing some strange hierarchy assertions in our patterns. These are the current issues we are facing:

Some items are being classified under 'is_a exposure to butter (unsalted)', which I presume should not be. These include:
ECTO:0070007 - exposure to heavy cream
ECTO:0070017 cottage cheese, (Make sure not a child of butter exposure)
ECTO:0070018, cream cheese
ECTO:0070020 low-fat cheese
ECTO:0070199 cow milk cheese nonfat
ECTO:0070204 cow milk liquid
ECTO:0070176 - exposure to butter (salted) via ingestion

Additionally, I am seeing now with the updated imports the the previous term 'exposure to banana via ingestion' is now labeled 'exposure to Cavendish banana via ingestion' (using FOODON:03316257), but there is now a different 'banana' term in FoodOn as well (FOODON:00004184)?

I am also seeing ECTO:0070158, 'exposure to mayonnaise via ingestion' (using FOODON_03301440), has the assertion of exposure to salad dressing via ingestion.

[ECTO#227](https://github.com/EnvironmentOntology/environmental-exposure-ontology/pull/227)

**Comment by ddooley** [comment]
Thanks for spotting these issues.  I've just looked into the unsalted butter issue but can't see anything odd at our end.  There are no equivalency axioms attached to "butter (unsalted)", and no references anywhere else in FoodOn to it. How are you importing foodon?  Direct from github, or via ontofox? Are there other problematic "is_a" parents at the same time for those given terms?

So previously FoodOn was calling "banana" what was actually a specific cavendish banana subspecies (the most popular north american retail variety), but the label didn't reflect that.  The new banana hierarchy recognizes that cavendish is only one of a variety of bananas.  If appropriate, could you adjust your import script to recognize the new more general banana term? The new generic term is ["banana (whole)"](http://purl.obolibrary.org/obo/FOODON_00004183) and it will have an axiom on the next update "'berry fruit' and 'derives from' some Musa" if that is the term you would most like to use?

**Comment by laurenechan** [comment]
Hi again, I think I figured out the butter issue, it was a misplaced curie within our pattern file. Sorry for the alarm, totally my fault on that one!

Thanks for the insight on the banana changes!

Also, as we were running the reasoner we were seeing some issues arise with the ObjectProperty 'is quality measurement of' that I think is being imported into ECTO from foodon. It looks like there are some violations with 'is quality measurement of' being used with a process as opposed to a measurement datum, which is the specified domain. 
![Screen Shot 2022-06-01 at 9 49 15 AM](https://user-images.githubusercontent.com/49169837/171439144-bdc21447-2a64-4be5-a1c6-752d507ac3ab.png)

**Comment by ddooley** [comment]
I don't thing that is coming from FoodOn!!!  Maybe from PO2?  FoodOn doesn't have the 'is quality measurement of' object property in it.  I'd like to know which ontology that is from!

**Comment by cmungall** [comment]
https://github.com/EnvironmentOntology/environmental-exposure-ontology/blob/6152787736defee4d2a7cb9b0eb94d8e56b107e4/src/ontology/imports/ons_import.owl#L7982-L8000

**Comment by maweber-bia** [comment]
Hi! PO2 is not involved because we have not been integrated so far in OBO foundry, but we are committed to reuse concepts or align with! and also happy to contribute 

Thanks to @cmungall for the file

**Comment by ddooley** [comment]
Thanks for determining source.  I have moved this over to an ONS issue https://github.com/enpadasi/Ontology-for-Nutritional-Studies/issues/35 I can close this?

**Comment by laurenechan** [comment]
Thanks all for helping identify the source and getting an issue on the ONS tracker!
