### ISSUE TITLE
Usage: Fruits and Vegetables

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [FoodOntology/foodon#21]
Matthew comments:

> 1. Yet another issue to think about (last one on this thread, promise)
>    revolves around is the notion that we need to define foods differently
>    depending on the context which they occur. A simple example of this is
>    the tomato https://en.wikipedia.org/wiki/Nix_v._Hedden. Botanically,
>    it is a fruit, yet for legal purposes in the United States and elsewhere,
>    it is considered a vegetable, legally. The reason for this is that
>    fruits--those sweet fruiting bodies from a plant--were generally considered
>    a delicacy, and taxed at a higher rate. tomatoes were considered to be
>    eaten with the meal, and therefor not taxed as heavily.

So the multiple categorizations of a particular food source arise in this case from "bending the rules", a colloquial usage in this case in favour of vegetable over fruit.  I've taken a peek at what ENVO has to say:
[vegetable](http://purl.obolibrary.org/obo/ENVO_01000756) and [fruit](http://purl.obolibrary.org/obo/ENVO_01000757), and see the provisio:

> editor note: This class represents a somewhat arbitrary grouping of plant products which varies along various axes (socio-political, economic, cultural, etc). It's likely we'll need to create more informative subclasses and use synonomy to tie them together.

So we're looking at annotating a [food item] "member of" ["vegetable"] relation probably, along taxonomic, cultural, legal etc. dimensions?

**Comment by leechuck** [comment]
> https://en.wikipedia.org/wiki/Nix_v._Hedden. Botanically, it is a
> fruit, yet for legal purposes in the United States and elsewhere, it
> is considered a vegetable, legally. The reason for this is that
> fruits--those sweet fruiting bodies from a plant--were generally
> considered a delicacy, and taxed at a higher rate. tomatoes were
> considered to be eaten with the meal, and therefor not taxed as
> heavily.

I believe for this, the best way will be to have two separate classes,
"vegetable (sensu botany)" and "vegetable (sensu law)" which will be
different. GO used to have these "sensu" classes a lot but mostly got
rid of them (no idea why), but we will likely need them or at least a
similar mechanism.

Rob.

## 

BitMessage: BM-2cXWLPcqKLrdfGNHpBDgTxDNHKGTGb2mhz
PGP: 50D0 AF17 F0D1 873A 94B7  B232 81C3 CFA7 E090 F6A2

**Comment by Public-Health-Bioinformatics** [comment]
Sounds good!

**Comment by Public-Health-Bioinformatics** [comment]
I have added "vegetable (sensu law)" http://purl.obolibrary.org/obo/FOODON_03000000, and offer up this definition: A vegetable (sensu law) is a plant food source which is botanically categorized as a fruit, but which has been legally categorized by a given jurisdiction's lawmakers as a vegetable, usually for taxation purposes.

I seeAlso the Nix_vs_Hedden case above.

I think that does it for now.  (Animal feed has its own related subclasses which can be developed further later).
