### ISSUE TITLE
Zucchini not categorized under squash

### ISSUE THREAD

**Issue by laurenechan** [FoodOntology/foodon#213]
Hi!
I was looking at the classification of zucchini and it appears to currently be living under 'vegetable food product', whereas I think zucchinis botanically are considered a fruit. I know culinarily it can be considered a vegetable though. Is there a way we currently approach that delineation? Additionally, zucchini is a type of squash, but it does not live under 'squash (whole)', which is a child of 'pepo fruit' in the fruit branch. Can and should zucchini be a child of 'squash (whole)'?

**Comment by mateolan** [comment]
This highlights the need for multiple forms of classification. Culinary
definitions are important because they result, in some cases, the way the
food is taxed. Look no further than Nix v Hedden--that went all the way to
the supreme court, in order to classify tomato as a vegetable. (
https://en.wikipedia.org/wiki/Nix_v._Hedden)
Culinary classification is every bit as important as botanical--both should
be represented.

**Comment by maweber-bia** [comment]
Hi! I would like to point out that in the FoodEX2 classification Courgettes and similar are  classified as "fruiting vegetables  "

![image](https://user-images.githubusercontent.com/64576528/175021235-0226e733-582d-4b8a-b722-d2f14532b593.png)

**Comment by ddooley** [comment]
Ah, "Fruiting vegetables" - that's a funny twist.

FoodOn has [vegetable (by legal status)](http://purl.obolibrary.org/obo/FOODON_03000000), so far an empty class but we could add that as a subclass of "Fruit", putting it over in the anatomy hierarchy.  Open to changing name, e.g. "**fruit legislated as vegetable (whole)**" I think it needs its definition tweaked to not reference a plant as a whole but rather a fruit part of a plant. Issue is different countries may have different legislation about this, so we wouldn't want to add subclasses to it unless there was some universal thing to say.  

The only "scientific" basis for calling a fruit a vegetable is sensory, organoleptic. A kind of taste, a kind of texture, that maybe yields a certain transformation when cooked.  Very fuzzy.  I don't think we could find any processes that would be exclusively vegetable or exclusively fruit processes (chopping, ripening, peeling, etc.)?

Do we need a "fruit product legislated as vegetable product" class? e.g. diced zucchini etc. Interestingly we can't literally put anything zucchini-ish under "vegetable food product" if it is defined botanically.  We'd have to back off of a biological definition of vegetable to meet grocery store catalog expectations!

FoodOn does have LanguaL's [fruit plant used as vegetable](http://purl.obolibrary.org/obo/FOODON_03411006) term, and similarly "floret plant used as vegetable"(http://purl.obolibrary.org/obo/FOODON_03411036), but this only applies to the plant as a whole, which is awkward.  Nevertheless I did just add zucchini plant to "fruit plant used as vegetable". I see FoodOn's zucchini equivalency points to too general a plant.  I've corrected this to point to "zucchini plant" as well.

**Comment by ddooley** [comment]
Or FoodOn accepts that "vegetable food product" is a flexible class that does not necessarily exclude fruit in the first place, since vegetable spans so many kinds of plant part.

**Comment by ddooley** [comment]
And I have fixed "an and should zucchini be a child of 'squash (whole)'?"  It now is in foodon-edit.owl draft.

**Comment by mateolan** [comment]
Indeed, a fruit is a vegetable (an edible part of a plant), but a vegetable
is not necessarily a fruit.
...akin to the way that a square is a rectangle...

**Comment by ddooley** [comment]
Discussed on June 23 call:
* Group was considering / comfortable with moving "plant fruit food product" under "vegetable food product".
* Agreed to rename "vegetable (by legal status" to "fruit legislated as vegetable (whole)".

**Comment by ddooley** [comment]
I have made the above changes to foodon-edit.owl
