### ISSUE TITLE
Adding synonyms to freeze-drying

### ISSUE THREAD

**Issue by marieALaporte** [FoodOntology/foodon#214]
Would it be possible to add the terms lyophilization and cryodesiccation as exact synonyms of the term freeze-drying?
Should I create a PR for it?

**Comment by ddooley** [comment]
I have added them directly to FoodOn draft since I have the file open! They should be live within a week or so.

**Comment by marieALaporte** [comment]
@ddooley I still cannot find the synonyms. I am looking at foodon_merged.owl and the OLS. Could you check that this is in please? thanks

**Comment by ddooley** [comment]
It looks like they are in Ontobee: https://ontobee.org/ontology/FOODON?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_03470130

But OLS hasn't updated to the latest FoodOn yet.  They were having problems loading ontologies apparently.
