### ISSUE TITLE
FOOD: FOod in Open Data

### ISSUE THREAD

**Issue by mcourtot** [FoodOntology/foodon#22]
Maybe of interest: https://iswc.lodac.nii.ac.jp/files/resource_28.pdf

**Comment by Public-Health-Bioinformatics** [comment]
I'm not getting a response on that domain at this point. Is there an updated reference to this resource?
Thx.

**Comment by ddooley** [comment]
Found link for this: https://link.springer.com/chapter/10.1007/978-3-319-46547-0_18
Will add to FoodOn.org other resources page.

**Comment by ddooley** [comment]
Also: http://www-kasm.nii.ac.jp/iswc2016/papers/paper_R28_.pdf
