### ISSUE TITLE
Deprecation Incomplete:  calyx, petal, stigma

### ISSUE THREAD

**Issue by cmrn-rhi** [FoodOntology/foodon#224]
We have the following terms in FoodOn:
`obsolete: calyx` http://purl.obolibrary.org/obo/FOODON_03420276
`obsolete: petal` http://purl.obolibrary.org/obo/FOODON_03420303
`obsolete: stigma`http://purl.obolibrary.org/obo/FOODON_03420277

They haven't had the deprecation process completed as they still have the "Subclass of: [floret or flower](http://purl.obolibrary.org/obo/FOODON_03420237)" term relation and additional term annotations (which we usually remove).

**Comment by ddooley** [comment]
Done!
