### ISSUE TITLE
'meat food product' definition is limited to mammals

### ISSUE THREAD

**Issue by johnwjudkins** [FoodOntology/foodon#225]
I have been working on a list of diet-based terms used by VEuPath projects to submit here. I noticed the textual definition and axiom for [meat food product](http://purl.obolibrary.org/obo/FOODON_00001006) refers to only mammals, even though it has poultry products as subclasses. I think birds should be included (maybe also amphibians and reptiles).

**Comment by ddooley** [comment]
Hi John, thanks for the feedback.  Besides what you point out, I'm looking at the hierarchy and see a few problems we can adjust this week!
- We already have categories for fish meat food product as separate from "meat food product", so I think the "meat food product" label should be expanded to "**mammalian meat food product**". (This term was imported from ENVO originally).
- I think the "vertebrate" and "mammal" subclasses should be pulled out of there so they exist in 'food product organismal source' exclusively, and make no commitment to whether organism was harvested.  (Same with 'fish' under 'fish food product').

**Comment by ddooley** [comment]
I think we need an 'avian meat food product', too, under 'avian food product'.  @Anoosha-Sehar could you pursue this issue?

**Comment by Anoosha-Sehar** [comment]
Hi Damion, 
Yes, I'm looking at the branch and I completely agree that we need to adjust the 'meat food product' branch. I think one of the ways is to have a separate class ''mammalian meat food product' underneath a general class 'meat food product' (by updating def & axiom)so we don't need to move 'amphibians or reptiles meat food product' or poultry meat food product or other meat products (which are not only derived from mammals). And another may be more optimum way is to expand the label and pull out categories other than mammals. 

- And yes, 'amphibian' and' mammal' classes should be pulled out of there so they only exist in 'food product organismal source'.

Let's first discuss these problems tomorrow in our regular FoodOn meeting.

**Comment by Anoosha-Sehar** [comment]
Reg`avian meat food product'` class; Yes, we should have that class, I'm adding that to the robot table right now. 
I've recently added some new classes to the FoodOn robot table to adjust this branch like 'quail food product', quail meat food product' so as to move quail meat (raw) there. Similarly pigeon food product, pigeon meat food product, pheasant meat food product, etc. But it requires some more work. Let's have a look at it too tomorrow.

**Comment by ddooley** [comment]
Foodon draft now has "mammalian meat food product" renamed from above.  As well adjustments to the hierarchy include a new "animal food product" superclass.  We have tweaked a few other classes to include the avian and separate amphibian / reptile food classes, and a few more adjustments are coming.
