### ISSUE TITLE
Update relations: 'derives from' some mammal

### ISSUE THREAD

**Issue by cmrn-rhi** [FoodOntology/foodon#226]
Discussed in FoodOn Curation Meeting (2022/09/01):

We should change existing mammal derivation term relations to a more specific defining food product ingredient. Arose from discussion of moving `mammal` [FOODON:03411134] to no longer be a `food product by organism` subclass, along with the renaming of `meat food product` to `mammalian meat food product` [FOODON:00001006] to better fit with the current definition and subclass relations.

**EXAMPLE:** infant formula whey-based

`'derived from' some mammal` replaced with `'had defining ingredient' some 'mammalian milk whey'`

**Terms that still need to be reviewed/addressed:**

- [x] infant formula casein-based
- [x] infant formula milk-based ready-to-feed
- [x] mozzarella cheese (made with whole milk, natural)
- [x] pasteurized process cheese
- [x] processed cheese sliced
- [x] meat food product
- [x] animal product sausage
- [x] animal product sandwich
- [x] blancmange powder
- [x] dripping from food
- [x] grated cheese (italian-style)
- [x] animal based salad food product
- [x] mozzarella cheese (low-moisture, part-skim)
- [x] mozzarella cheese
- [x] spiced cheese
- [x] cheese with added ingredients processed
- [x] cheese spread with added ingredients processed
- [x] butter or margarine extender (artificially sweetened)
- [x] bone meal wafer
- [x] bone marrow broth
- [x] mozzarella cheese (part-skim)
- [x] cheese varietal (pressed)
- [x] sausage (semi-dried)
- [x] pasta filata cheese
- [x] pastirma
- [x] cheese unripened
- [x] beverage (dairy based)
- [x] pepper pot soup with meat
- [x] meat fat shortening
- [x] burger meat (minimum vegetable and/or cereal content of 4%)
- [x] burger meat (starch content of more than 6%)
- [x] gelatinous coating for meat products edible
- [x] capsules based on gelatin
- [x] gelatin dessert mix low sodium sugar-free
- [x] meat goulash
- [x] ice cream (commercial, packed)
- [x] cheese (rennet, hard, salted, maturing in brine)
- [x] cheese preparation processed
- [x] game meat stock
- [x] meat stock
- [x] grated cheese (lowfat)
- [ ] game soup
- [x] infant formula (meat-based)
- [x] cheese (extra hard, grating)
- [x] cheese (ripened)
- [x] meat pie (frozen)
- [x] pimiento cheese spread
- [x] spiced cheese (part-skim)
- [ ] brown gravy
- [ ] gravy (country-style)
- [x] meat stew (canned)
- [x] stew (meat-based)
- [x] gelatin dessert (artificially sweetened)
- [x] teleme cheese
- [x] gelatin dessert mix artificially sweetened
- [x] gelatin product
- [x] sausage made from meat and poultry (raw)
- [x] irish stew
- [ ] brown gravy mix
- [x] meat stew (frozen)

**Comment by ddooley** [comment]
The "soup food product" and "broth or stock" (+gravy) classes have various subclasses like "animal soup food product" and "soup animal component", which need to be sorted out as they mention broths that aren't directly derived from "piece of animal meat", but rather are a product of some boiling process.  So we shouldn't be using "derives from" to connect broth to meat or animals directly.

**Comment by ddooley** [comment]
Note "meat food product" is now "animal meat food product".
