### ISSUE TITLE
Misspelling: `definition source: wikipedia:Shrimp_pastse` 

### ISSUE THREAD

**Issue by hrshdhgd** [FoodOntology/foodon#229]
The correct 'definition source' is `Shrimp paste` and the [Ontobee page](http://purl.obolibrary.org/obo/FOODON_03309823) has a typo (an extra 's')

cc: @cmungall

**Comment by ddooley** [comment]
Ok this is fixed now in FoodOn draft (a URI pointing straight to wikipedia now). Thanks for spotting it.
Damion
