### ISSUE TITLE
NCBITaxon changed identifiers for some fish species.

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/foodon#231]
These need to be updated in the foodon seafood list (then they will dissapear from root node of FoodOn ontology):

DELETED IN NCBITaxon http://purl.obolibrary.org/obo/NCBITaxon_30478 # Raja rhina
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_218804 # Leiognathus equulus
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_1428164 # species:Sorghum X drummondii (Nees ex Steud.) Millsp. & Chase 
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_302770 # Hermosilla azurea
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_341241 # Raja binoculata
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_50905 # Rhacochilus vacca
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_740706 # Raja inornata

I have commented out their entry in ncbitaxon_ontofox.txt

**Comment by Anoosha-Sehar** [comment]
Hi Damion,,
Yes, it looks like NCBI has replaced the above IDs with the new ones and the previous labels are now added as synonyms.
I've updated the seafood list on the FoodOn Robot table with new labels and IDs. These NCBItaxons need to be added in NCBI_ontofox.txt. Once you close my already opened pull request; I can push these new IDs into a new pull request.

[http://purl.obolibrary.org/obo/NCBITaxon_2838338](http://purl.obolibrary.org/obo/NCBITaxon_2838338)  # Beringraja rhina (Synonym: Raja rhina, Alternative ID->NCBITaxon:30478)
[http://purl.obolibrary.org/obo/NCBITaxon_2893490](http://purl.obolibrary.org/obo/NCBITaxon_2893490) # Leiognathus equula (Alternative ID-> NCBITaxon: 218804)
[http://purl.obolibrary.org/obo/NCBITaxon_2838349](http://purl.obolibrary.org/obo/NCBITaxon_2838349) # Kyphosus azureus (Synonym: Hermosilla azurea, Alternative ID-> NCBITaxon:302770)
[http://purl.obolibrary.org/obo/NCBITaxon_2838337](http://purl.obolibrary.org/obo/NCBITaxon_2838337) # Beringraja binoculata ( Synonym: Raja binoculare, Alternative ID-> NCBITaxon: 341241)
[http://purl.obolibrary.org/obo/NCBITaxon_2838341](http://purl.obolibrary.org/obo/NCBITaxon_2838341) # Phanerodon vaccai (Synonym: Rhacochilus vacca, Alternative ID->NCBITaxon:50905)
[http://purl.obolibrary.org/obo/NCBITaxon_2838339](http://purl.obolibrary.org/obo/NCBITaxon_2838339) # Beringraja inornata (synonym: Raja inornata, Alternative ID->NCBITaxon:740706)

One of the mentioned IDs is a plant term- I've checked that it's anyways not in the plant*part table. 
DELETED " http://purl.obolibrary.org/obo/NCBITaxon_1428164 # species: Sorghum X drummondii (Nees ex Steud.) Millsp. & Chase

**Comment by ddooley** [comment]
This is resolved in master now.
