### ISSUE TITLE
NTRs: food product and diet terms

### ISSUE THREAD

**Issue by zhengj2007** [FoodOntology/foodon#234]
The Clinical and Epidemiology Database (ClinEpiDB, https://clinepidb.org/) is an open-access online resource for exploring and analyzing clinical and epidemiologic studies. We integrated the studies from multiple resources and standardized data using OBO Foundry ontologies. It contains the datasets, such as interaction of enteropathogenic infection and undernutrition. So, the ClinEpiDB need many terms associated with nutrition, food products, and diets. The ClinEpiDB is developed by [VEuPathDB](https://veupathdb.org) team. We added the terms in VEuPathDB ontology [issue 394](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/394) since most of the terms are information content entities (ICEs) that are about food products and diets. But we'd like to associate the ICEs with food products.

Here are the food product terms we need:
- animal food product
- apple food product
- banana food product
- barley food product
- beef food product
- berry food product
- botanical fruit food product
- cabbage food product
- carrot food product
- cereal grain food product
- cereal grain food product
- confectionary food product
- cow milk food product
- egg food product
- fish food product
- food product derived from fish or shellfish
- food product derived from squash, carrot, or sweet potato
- food supplement for moderate malnutrition
- food supplement for severe malnutrition
- formula fortified from cow's milk
- formula not fortified from cow's milk
- fortified food
- iron-rich food
- leafy vegetable plant food product
- legume food product
- maize food product
- mango food product 
- maternal milk
- meat food product
- milk or milk based food product
- non-human animal milk
- oat food product
- papaya food product
- pasteurized donor milk
- pea food product
- pear food product
- plant root product
- plum food product
- pork food product
- potato food product
- poultry food product
- rice food product
- rye food product
- steeped beverage product
- sweetened drink
- tomato food product
- vitamin A rich fruits
- vitamin A-rich food
- wheat food product

Besides, we also need some diet terms, such as the terms listed below.
- diet including dairy food product
- diet including dark green leafy vegetables
- diet including dark green leafy vegetables or meat
- diet including dark green leafy vegetables, meat, eggs, or fish
- diet including dark green leafy vegetables, meat, or eggs
- diet including dark green leafy vegetables, meat, or fish
- diet including fruit with yellow, orange, or red flesh
- diet including meat
- diet including meat or eggs
- diet including meat or fish
- diet including meat or fish
- diet including meat, eggs, or fish
- diet including non-organ meat, eggs, or fish
- diet including organ meat
- diet including proteins from non-animal sources
- diet including solid or semisolid food
- diet including vegetables with yellow, orange, or red flesh
- diet including water
Will the FOODON take the diet terms?

If the FOODON would like to take the terms, we will submit the terms following FOODON NTRs tracker.

**Comment by ddooley** [comment]
Hi,
ClinEpiDB looks like a great resource and we're happy to see food ontology used there!  It looks like many of your [x] food product terms are already in FoodOn but we'd be happy to take the remainder.

The diet terms would normally go into ONS, [Ontology for Nutritional Studies](https://github.com/enpadasi/Ontology-for-Nutritional-Studies), which FoodOn imports the diet and dietary pattern of.  ONS is promising a bit of a revamp though, so let me check in with them to see where they are at with that.

**Comment by zhengj2007** [comment]
@ddooley Thanks for your quick response. It's great that FOODON would like to take the food product terms. If you need further information for adding new food product terms, please feel free to let us know.

ONS does not look like in good shape. But if they'd like to improve it and take the diet terms, we are happy to submit the terms to ONS. Thanks for checking with them.

**Comment by ddooley** [comment]
Discussed at FoodOn curation call Oct 13.  We're interested in getting more information on your use of dietary terms with respect study metadata representation / model.  We will follow up with a call/presentation invite!

**Comment by ddooley** [comment]
As well I'll send a list of matched x food product foodon terms; with remainder welcome into FoodOn.

**Comment by zhengj2007** [comment]
We will work on representations/models and discuss with your team.

**Comment by ddooley** [comment]
A preliminary use of our https://lexmapr.cidgoh.ca/ tool identifies these [matching food products](https://docs.google.com/spreadsheets/d/1e_4UIh-X2YCEapuS3LaIW-lpiUnnj4AIKWVW-pJvVCo) .  I've left the bad matches in red at bottom of list - terms that I can see FoodOn needs new entries for  -  but the others should be ready to go.

**Comment by zhengj2007** [comment]
It looks good. Thanks!

**Comment by truemping** [comment]
Jie- I'm working with Damion + team on curating the new terms you've asked for. If possible, it would be really helpful to learn just a bit more context around how you plan to use some of the terms, so that we're setting things up in a way that matches your needs. Specifically we have some questions about the overlap/mutual exclusivity of some of the diet terms, and how we might best model the "foods rich in [nutrient]" terms. Could we find 30 min for a chat sometime in the next week or so? Let me know a time that's good for you (I'm on US Central time, but I can be pretty flexible). Thanks! --Troy

**Comment by zhengj2007** [comment]
Hi @truemping, It sounds good to have a call for it. @johnwjudkins in our team will show you how the terms are used in our project and what terms we need from FOODON. Both John and I are available this Wednesday after 3PM EST and this Friday. Could you please let us know what time is good to you? Thanks!

**Comment by truemping** [comment]
@zhengj2007 @johnwjudkins could we meet Wed, 2 Nov, at 3pm EST? Here is the link for our conversation:
https://meet.google.com/wiw-hxan-tey 
Talk to you soon.

**Comment by johnwjudkins** [comment]
@truemping That works for me. Thanks.

**Comment by zhengj2007** [comment]
@truemping Works for me too. Thanks!

**Comment by johnwjudkins** [comment]
[food-design-pattern.xlsx](https://github.com/FoodOntology/foodon/files/9954369/food-design-pattern.xlsx)
I'm submitting our list in a ROBOT template format of all our terms related to food/diet. First in the list are food products (which I think you'd be most interested in) followed by information terms about food products in particular contexts. 

The ID column values are for VEuPath internal use to keep track of IDs we may replace in our project files. The Note column is just notes for clarity/discussion on a few terms; it's not meant to be an annotation property.

**Comment by johnwjudkins** [comment]
@truemping @ddooley I should have tagged you in my last comment. By the way, I mentioned in a note in the spreadsheet there that the VEuPathDB ontology has 'breastfeeding process', and it could fit in FOODON, but GO already has [suckling behavior](http://purl.obolibrary.org/obo/GO_0001967).

**Comment by truemping** [comment]
thanks @johnwjudkins for the great prep here. We'll go through everything in detail and get back to you shortly.

**Comment by johnwjudkins** [comment]
@truemping @ddooley Following up. Any progress on the requested terms, especially for these food products?

moderate malnutrition supplement food product
severe malnutrition supplement food product
fortified food product
iron rich food product
vitamin A rich food product
dark green leafy vegetable food product

I'm still wondering what is the best way to ontologize foods that are "rich" in some nutrient. Perhaps we could just use PATO's [increased amount](http://purl.obolibrary.org/obo/PATO_0000470), or we could refer to some standard of how much of a nutrient a food has to contain to be considered "rich".

**Comment by truemping** [comment]
@johnwjudkins so sorry for the slow progress here. We've done some preliminary analysis, and I'm hoping to finalize most of the terms with the team over the course of this week. How about if we set up a time at the end of this week or beginning of next week to review things? Hopefully it will all be pretty self-explanatory, but perhaps we'll need to discuss 1-2 places where things were tricky. My calendar on 1/27 and 1/30 is pretty flexible-- what works best for you?

**Comment by johnwjudkins** [comment]
@truemping Thanks for following up. I'll be out those two days, but I could meet next week at our previous meeting time (Wed. 3 PM eastern). @zhengj2007 what do you think?

**Comment by zhengj2007** [comment]
@johnwjudkins It works for me.

**Comment by truemping** [comment]
Yes, 3pm EST on Wed, Feb 1. Below is a link we can use for the meeting. @johnwjudkins @zhengj2007 @ddooley 

Review new FoodOn terms for GeneEpiDB
Wednesday, February 1 · 2:00 – 3:00pm
Google Meet joining info
Video call link: https://meet.google.com/tdt-kdoj-pnv

**Comment by truemping** [comment]
Initial draft of robot template, to add some terms to FoodOn, attached. (draft values, not finalized)
[https://docs.google.com/spreadsheets/d/1er_JFhJCFbCkezsDyilSVek_PAmj_UerbBQywy3xXLg/edit?usp=sharing](url)

**Comment by zhengj2007** [comment]
@truemping The link doesn't work. Could you please check it? Thanks!

**Comment by ddooley** [comment]
@zhengj2007 I think the hyperlink is some kind of apple security hoop; but if you cut and paste that as text into a browser it will work.

**Comment by zhengj2007** [comment]
@ddooley It worked. Thanks!

**Comment by truemping** [comment]
@zhengj2007 @johnwjudkins Please don't make any changes to the document I uploaded yesterday. (It's not the "master" anymore, because we've loaded this text elsewhere and then edited it.) I'll let you know when we have a "solid draft, near final" for you to review.

**Comment by johnwjudkins** [comment]
It turns out we don't have a specific list of "dark green leafy vegetables" in our project. But there is a description with examples here: https://www.ars.usda.gov/plains-area/gfnd/gfhnrc/docs/news-2013/dark-green-leafy-vegetables/

**Comment by ddooley** [comment]
To see if we can finish this item off I have added the following terms to foodon draft:
<img width="1042" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/1653617a-31d9-4b2a-bb33-1cecab513341">
One question is whether we can deemphasize "dark green leafy vegetable food product" in favour of "dark green leafy vegetable food material"?  We're starting to veer away from "food product" towards "food material" categories where possible insofar as food products require some kind of processing done to them; whereas one might want to talk about the dark green vegetable leaves without implying processing.

**Comment by zhengj2007** [comment]
@ddooley Thanks for working on it. Both John and I left the VEuPathDB team. And the clinEpiDB is not funded now. I think FOODON can add the terms as you prefer. The terms may help other projects.

**Comment by ddooley** [comment]
Ok, thanks.  Closing now.
Slight addendum: dark green leafy vegetable food material is now FOODON_00005045
