### ISSUE TITLE
"Is similar to" link for Analog's

### ISSUE THREAD

**Issue by michaelehowe2** [FoodOntology/foodon#238]
Sorry if this already exists, but I was wondering if it would be possible to link the analogs with their original counterpart. i.e.

Milk "is similar to" Milk Analog

**Comment by maweber-bia** [comment]
Sorry to interfere but I do not think that the assertion  milk is similar to milk analog is correct.

Just  as peanut butter is not similar to butter.

Magalie



De : michaelehowe2 ***@***.***>
Envoyé : lundi 17 octobre 2022 12:41
À : FoodOntology/foodon ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [FoodOntology/foodon] "Is similar to" link for Analog's (Issue #238)


Sorry if this already exists, but I was wondering if it would be possible to link the analogs with their original counterpart. i.e.

Milk "is similar to" Milk Analog

**Comment by ddooley** [comment]
FoodOn has a "has food substance analog" relationship used to connect such foods to each other.  This allows more of a declarative relation between products and the "cow milk (liquid)" class for example. We haven't methodically gone through FoodOn to attach this relation between product classes however.  But we could add " 'cow milk (liquid)' 'has food substance analog' some 'milk substitute' ".  

We will be improving organisation of the food product analog branch a bit soon btw, see https://github.com/FoodOntology/foodon/issues/218

From past discussion, things may get a little touchy in the food industry if one casts that e.g. 'soy milk' is a milk substitute for example. That gets very relative to consumer too.

**Comment by michaelehowe2** [comment]
@maweber-bia - Using "similar to" is the wrong wording. But by definition if its an analog of something then its "a thing seen as comparable to another."

@ddooley "has food substance analog" relationship is exactly what I was meaning, so that's great that exists. But as you say that isn't used very much. Glad improvement is underway.

I appreciate that this is a touchy subject, but having a web of entities that are used as alternatives is a very useful thing. But I also realise that it gets complicated as some things are alternatives for certain use cases but not for others. (i.e. Vegetable Spread vs Butter on bread is OK, but Vegetable Spread in french pastry doesn't work.)

I'll close this thread as it seems @ddooley answered my issue.
