### ISSUE TITLE
Not able to load ontology ('foodon.owl', 'foodon-base.owl')

### ISSUE THREAD

**Issue by iamyihwa** [FoodOntology/foodon#239]
Getting error 'foodon.owl; lineNumber: 16; columnNumber: 76; 
 Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.

When loading the ontology either using 'Protege' tool, or owlready2 library (python). 

Protege: 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/12494156/196935702-33b9813f-6d2d-42e1-af29-83fb1ac31a53.png">

Owlready2 : 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/12494156/196935774-01c9a6aa-eafb-4df3-bc0a-bc10de88f507.png">

**Comment by ddooley** [comment]
Where are you getting foodon.owl from? I'm able to load this into protege 5.5 from our https://github.com/FoodOntology/foodon/ without an error!

**Comment by ddooley** [comment]
Also, the downloaded file should be ~40Mb.

**Comment by iamyihwa** [comment]
Thanks @ddooley  for your input.
You were right that the file that i got wasn't quite correct one! 

When I git clone the whole repo and get the owl files, each file is around ~30MB. 
Whereas if I simply download each file , then there size is only around 100KB. 

After downloading it correctly, it all works!
