### ISSUE TITLE
Mint Food Product

### ISSUE THREAD

**Issue by michaelehowe2** [FoodOntology/foodon#241]
Can we add [mint jelly](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_03305875) under [mint food product](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_00002432)

**Comment by michaelehowe2** [comment]
Mint Jelly probably should also be merged with 

- [jellied mint sauce](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_03305893)

**Comment by ddooley** [comment]
Done in foodon-edit.ofn !
And I've obsoleted jellied mint sauce in favour of mint jelly.  There's no basis as far as I can tell for having a "jellied mint sauce" product.
