### ISSUE TITLE
NTR: Papadam

### ISSUE THREAD

**Issue by michaelehowe2** [FoodOntology/foodon#242]
# NTR: Poppadom 

## Parent Term/Class:
Open for discussion as I would like to put it under flour product, 
- [flour food product](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_00001056)
- [cultural food product](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_00001796)
## Definition: 
A {requested parent term} {which/during which} is either fried or cooked with dry heat (flipped over an open flame) until crunchy

## Definition Source:
[Papadam}](https://en.wikipedia.org/wiki/Papadam)
### Exact Synonym(s):
Poppadom
### *Additional Comments (not an annotation)*:
As this can be made from many flours I don't think this can go any lower in the flour hierarchy. It is also of Indian origin if there is a way to connecting it to that part of the ontology.

**Comment by ddooley** [comment]
This is already in foodon as http://purl.obolibrary.org/obo/FOODON_03307020 Poppadum with synonym you gave. Now currently we have it under "bread food product" but that ties it too closely to wheat.  We will discuss at next foodon curation meeting.

**Comment by michaelehowe2** [comment]
Ah. I was using the search via https://www.ebi.ac.uk/ols/search?q=poppadom&ontology=foodon and it didn't find it. Found it now, thanks.

Yeah it feels more flour food rather than bread.

**Comment by ddooley** [comment]
A delay in this but now resolved in upcoming FoodOn draft.  Bread food product is no longer committed to having wheat as ingredient.
