### ISSUE TITLE
Multilingual Export

### ISSUE THREAD

**Issue by michaelehowe2** [FoodOntology/foodon#244]
Hello (Sorry for flooding the form with "issues"), We've just started building on-top of foodon so are focusing on the issues as we notice them. Please let me know if there is a better way to do this.

--

We are based in the UK and find quite a lot of the terminology american English rather than British English (Candy vs Sweets, yoghurt vs yogurt, etc). It would be great if there was a way to not only have words as synonyms, but also localise the ontology itself. Is there any plans for this?

**Comment by ddooley** [comment]
So this points historically to the fact that the food product branch was based on LanguaL's SIREN database, an American list of over 9000 food products that were showing up in their National Agriculture Library.  We actually haven't formulated a policy about what english variant the label of a term should be - at moment FoodOn labels are marked with generic @en language. But we can create exact synonyms that have language variations like @en-uk and @en-us (just a few examples of this you can find by searching in protege for "en-uk" etc.  However we haven't yet placed such an annotation project into our future workplan.

**Comment by oldskeptic** [comment]
[michaelehowe2](https://github.com/michaelehowe2) Just jumping in to close this. You can commit descriptions and labels with "@en-gb" and use sparql to fallback from  "@en-gb" to "@en" or "@en-us" with `LANGMATCHES` and `Coalesce`.
