### ISSUE TITLE
NTR: Mint sauce

### ISSUE THREAD

**Issue by michaelehowe2** [FoodOntology/foodon#245]
# NTR: Mint sauce

## Parent Term/Class:
- [mint food product](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_00002432)
- [sauce](https://ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/FOODON_03311146)
## Definition: 
A {requested parent term} {which/during which} is made from finely chopped [spearmint](https://en.wikipedia.org/wiki/Spearmint) ([Mentha](https://en.wikipedia.org/wiki/Mentha) spicata) leaves soaked in [vinegar](https://en.wikipedia.org/wiki/Vinegar), and a small amount of [sugar](https://en.wikipedia.org/wiki/Sugar).
## Definition Source:
"[Mint sauce - Wikipedia](https://en.wikipedia.org/wiki/Mint_sauce)

**Comment by ddooley** [comment]
New term id is http://purl.obolibrary.org/obo/FOODON_00004312 in foodon-edit.ofn.  That will make its way to /foodon.owl within a few days.
