### ISSUE TITLE
Error in FOODON:03302204

### ISSUE THREAD

**Issue by jarretinha** [FoodOntology/foodon#246]
I tried to convert the owl file to obo using ROBOT. Command resulted in the error below. Of course, removing the term solves the problem. 

```
robot -v convert --input foodon.owl -output foodon.obo

OBO STRUCTURE ERROR Ontology does not conform to OBO structure rules:
multiple name tags not allowed. in frame:Frame(FOODON:03302204 id( FOODON:03302204)xref( SUBSET_SIREN:F2204)property_value( IAO:0000114 IAO:0000428)property_value( IAO:0000412 http://langual.org xsd:string)name( honey cake (sliced, reduced-salt))comment( SIREN DB annotation:
* has quality 'sliced, thick, between 0.5 and 1.5 cm.' (http://purl.obolibrary.org/obo/FOODON_03430124)
* has quality 'fully heat-treated' (http://purl.obolibrary.org/obo/FOODON_03440014)
* derives from 'seed, skin removed, germ removed (endosperm)' (http://purl.obolibrary.org/obo/FOODON_03420208)
* formed as a result of 'carbohydrate fermentation process' (http://purl.obolibrary.org/obo/FOODON_03460256)
* has substance added  'honey added' (http://purl.obolibrary.org/obo/FOODON_03460149)
* has substance added  'sucrose added' (http://purl.obolibrary.org/obo/FOODON_03460158)
* has consumer 'reduced salt food' (http://purl.obolibrary.org/obo/FOODON_03510087)
        )name( honey cake sliced reduced-salt)subset( subset_siren)is_a( FOODON:00002348)relationship( RO:0002350 FOODON:03400210))
```

**Comment by ddooley** [comment]
Thanks for raising this - I wasn't aware of .obo conversion issues.  I have removed the duplicate label that was causing this particular problem.  However there are other cases of duplicate label and duplicate rdfs:comment that I see trigger the same error in converting to .obo  . I wasn't aware that multiple rdfs:comments were banned from obo so that will take some time to work through.

**Comment by ddooley** [comment]
Unfortunately FoodOn's import of 3rd party ontologies is riddled with double label variants (sometimes just with or without @en language tag), and double definition variants.  We won't be able to support output of .obo format without solving a number of these upstream problems, or picking label or definition arbitrarily, which leads to inconsistency.  So I'm going to close this.  It might be that ODK which FoodOn will get implemented soon in its latest release, will have a solution.
