### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jdelacueva** [FoodOntology/foodon#25]
What is the license of this repository? Thank you in advance.

**Comment by Public-Health-Bioinformatics** [comment]
Thanks for bringing that ommision to my attention.  I'm just checking in with the partners.  It will either be CC-BY or CC-0.  Will let you know shortly.

Regards,

Damion

**Comment by Public-Health-Bioinformatics** [comment]
I've updated the license to be CC-BY 4.0 (we may at some point simplify that to CC-0 in conjunction with other OBOFoundry.org ontology licenses.)
