### ISSUE TITLE
Syntax error in CURIE in dbxref for sesame plant

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#251]
From https://github.com/INCATools/ontology-access-kit/issues/344

http://purl.obolibrary.org/obo/FOODON_03411226

this has an xref:

"DPNL 2003:13063"

This is not a valid dbxref due to the space, which should be removed

ideally the prefix would be registered with bioregistry.io too but the most important thing is syntactic correctness

**Comment by ddooley** [comment]
We'll have this fixed asap.  I actually wasn't aware that oboInOwl#hasDbXref was required to be a curie. Where does one find that info?

d.

**Comment by cmungall** [comment]
https://owlcollab.github.io/oboformat/doc/obo-syntax.html#2.5
https://owlcollab.github.io/oboformat/doc/obo-syntax.html#2.6

but as to broader requirements that prefixes should be expandable to URIs see the sssom paper...

**Comment by ddooley** [comment]
I'm just checking with LanguaL people about the efficacy of DPNL 2003 links, which may not be effectively pointing anywhere, in which case I will remove them altogether rather than fixing their curries.

**Comment by ddooley** [comment]
This is now resolved in /foodon.owl .  A consult with LanguaL yielded that DPNL links are now archaic, so I've removed them entirely.  As well some other hasdbxref uri spacing is fixed.
