### ISSUE TITLE
Issue: bakery product

### ISSUE THREAD

**Issue by cmrn-rhi** [FoodOntology/foodon#254]
I noticed that "bakery product" [FOODON:03310635] and related terms are under "wheat based bakery food product" [FOODON:00002347] and I would argue it should be the other way around. There are also a lot of items under "wheat based bakery food product" that can be wheat-free (really anything that doesn't specify "wheat").

**Comment by ddooley** [comment]
The SUBSET_SIREN:F10635 reference on that "bakery product" leads to an entry that indicates that it originates from wheat (Langual facet B1312).  It also says its fully heat treated, and baked, so we're dealing with 1 baked item here, as opposed to things like dough, or cake mix.  How about I relabel it to "wheat bakery product (baked)" ?

**Comment by cmrn-rhi** [comment]
That sounds great to me.

**Comment by ddooley** [comment]
Done
