### ISSUE TITLE
plural groupings of ‘animal parts’

### ISSUE THREAD

**Issue by Anoosha-Sehar** [FoodOntology/foodon#258]
For developing a standardized template to organize 'animal * part' in FoodOn.
Discussed it in meeting with @ddooley  and @kaiiam about adding a class '`X {animal} heart parts`' underneath 'X {animal} heart (whole or parts). (Dec 5,2022)
We talked about how can we appropriately axiomatize '`X {animal} heart parts'`?  
Where X {animal} could be any animal, e.g. 

-duck organ (whole or parts)
  --duck heart (whole or parts)
> ---duck heart (whole)
> ---duck heart (raw)
> ---duck heart (whole, raw)     
> -- -**`duck heart parts`**

Needs suggestions on the axiom.

**Comment by Anoosha-Sehar** [comment]
One of the option which was discussed: 
{animal} heart parts = ''animal parts' and 'derives from' some '{animal} heart (whole)' 
(e.g. duck heart parts = ''animal parts' and 'derives from' some 'duck heart (whole)'

**Comment by Anoosha-Sehar** [comment]
Not exactly sure, if it makes sense. Just brainstorming (following the template we have designed so far[Slide 3 ](https://docs.google.com/presentation/d/1HqRG73Z3FYmmcWwSROPJJ33PSMFnLcQmRA5RmVGpbu4/edit#slide=id.g17503889009_0_6))

`{animal} heart parts`= `''{animal} organ parts' and 'derives from' some ' X {animal} heart (whole)’`
(e.g. duck heart parts= ''duck organ parts' and 'derives from' some ' duck heart (whole)’)
`{animal} organ parts`= `'{animal} parts' and 'derives from' some '{animal} organ (whole)’`
(e.g. duck organ parts=  ''duck parts' and 'derives from' some 'duck organ (whole)’
`{animal} parts` = `''animal parts' and 'derives from' some '{animal) whole'`
(duck parts = ''animal parts' and 'derives from' some '{duck) whole')
`animal parts `= `''object aggregate' and 'has member' some '{animal} part ' and 'has member' only '{animal} part')`

or if we should use 'object aggregate' for all these plural groupings mentioned above?

**Comment by ddooley** [comment]
Slight detail (you probably meant):

`animal parts = ''object aggregate' and 'has member' some '{animal} part ' and 'has member' only '{animal} part')`

doesn't need a variable {animal} anymore, so:

`animal parts = ''object aggregate' and 'has member' some 'animal part ' and 'has member' only 'animal part')`

And an 'animal part' definition finally brings us to what we need to define carefully with respect to UBERON to make clear we're not talking in-situ anatomical part which is UBERON's default interpretation (except for body substances like milk), but rather a severed or butchered part.  

`animal part = 'derives from' some animal and 'derives from' only animal`

A remaining issue for me is how much processing we want to allow in the animal part "derives from" axiom?  Is gelatin an "animal part"?  Maybe we disallow mixtures and object aggregates as "animal part"?  Or maybe this is simply taken care of in axioms that qualify animal part(s).

d.

**Comment by Anoosha-Sehar** [comment]
Yeah my bad, you got it right. I forgot to remove the brackets. Thank you for the correction.

Just for reference, so far we have defined 'animal part' as: Meat or organ or muscle tissues that may include, bone, fat, skin and cartilage.
Yeah I agree, mot sure but maybe can start with evaluating on if it can be handled in axioms that consume 'animal part'.

**Comment by ddooley** [comment]
Hmm, I think then we need to re-lable 'animal part' to 'animal tissue part' to distinguish from a more general 'animal part' which covers bone (&bone meal) and cuts of fat with little or no tissue.

**Comment by ddooley** [comment]
I'll close this since it seems to be handled in latest animal pieces diagram.  We've started to use "piece" and "pieces" instead of "part" or "parts" to consider literal pieces as separate from anatomical parthood.
