### ISSUE TITLE
Geo location "Southwest Asia" accidentally has ancestral group items in it.

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [FoodOntology/foodon#26]
The ancestro demonyms need to be moved from FOODON_03520509 "Southwest Asia" back into a repaired Ancestro "Southwest Asia" branch.

**Comment by Public-Health-Bioinformatics** [comment]
Fixed in upcoming release. However ancestro, GAZ, and FoodOn still have overlapping global region classes which need to be normalized.

**Comment by cmungall** [comment]
What is the plan here?

Currently the release version of FOODON has PURLs of the form

http://purl.obolibrary.org/obo/ancestro_0001
http://www.ebi.ac.uk/ancestro/ancestro_0308

Neither of which resolve

This is a problem as they leak into ontologies that import foodon.

It also seems odd for FOODON to be importing an ontology designed for grouping people in GWAS, we need better modular design principles in OBO

**Comment by cmungall** [comment]
I can see the use case for an ontology *like* ancestro for foods of cultural significance, but ancestry and culture are only mutual proxies, not identical. FOODON should not import ancestro

cc @pbuttigieg

**Comment by Public-Health-Bioinformatics** [comment]
Hmm, Argh.  Ancestro made a move recently to switch their PURLS to be OBOFoundry friendly - but now I see this was in advance of their actually getting into OBOFoundry. The purls are stated in OLS.

https://www.ebi.ac.uk/ols/ontologies/ancestro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fancestro_0001

And so I switched a few weeks ago to using their new PURLS.

In FoodOn, the old www.ebi.ac.uk are weeded out - except that one you reference was marked Deprecated in FoodOn. I guess I should update its URI anyways even if deprecated since it should resolve when they complete transition into OBOFoundry.

So Ancestro provides a continent-like grouping but also with categories like "Hispanic". Foodon references Ancestro's demonyms for countries, but the countries themselves we switched over to Gazetteer in FoodOn.  Ancestro is looking at merging their content with EFO ethnic group (http://www.ebi.ac.uk/efo/EFO_0001799) which they define as "A group of people with a common cultural heritage that sets them apart from others in a variety of social relationships".  I would take your recommendation and switch to a more attenuated "cultural group" but until someone else advanced that, esp. given their overlap, I suggest we continue with the ethnic group proxy.

**Comment by ddooley** [comment]
Note, we've switched to using hancestro URLS

**Comment by cmungall** [comment]
maybe this can be closed?

Though it looks like foodon imports hancestro, but doesn't actually use it?

**Comment by ddooley** [comment]
Right, I can close.  But we were providing "italian", "french" etc. as a prelude to linking recipes to their country/cultural origin. I'll check in to see with our JFOW discussion group if they think that's useful.
