### ISSUE TITLE
Some terms got lost in last release?

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#260]
Maybe I am the only one but I had been using the following FOODON classes:

- FOODON_3317331
- FOODON_3500000
- FOODON_3500001
- FOODON_3500002
- FOODON_3500003
- FOODON_3500004

And somehow they have disappeared without trace?

I can still see them on the old release: https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_3500004

**Comment by ddooley** [comment]
Thanks for raising this.  I can see the curation problem, part of which we spotted earlier.  Basically some FoodOn terms weren't given the right id pattern in a robot table, and now they overlap with existing entries.  But I didn't realize the range you gave was part of the problem. I think the 03600001 etc terms below are the corrected ids for the first terms, but I don't know why then there wasn't a deprecated older ID.  We will add the deprecated 7 digit terms.  The terms in red were scheduled for correction.
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/4000582/207088638-e7d40065-c9a6-4a9c-bb9a-a89b2d94eab0.png">

However the "bacon (whole cut or parts) " FOODON_3317331 reference I think is wrong on the ECTO side - that should be FOODON_03317331 with leading 0.

**Comment by matentzn** [comment]
Thanks @ddooley we will recurate the affected entires on our end.

**Comment by matentzn** [comment]
I think we fixed it on our end now! Thank you @ddooley

**Comment by ddooley** [comment]
Note that FoodOn 3500005 to 3500012 have been deprecated now and replaced by 03600005 to 03600012, in case you were depending on those ID's too.

**Comment by matentzn** [comment]
Thank you @ddooley I also fixed these now!
