### ISSUE TITLE
Foodon is currently invalid RDF due to orcids

### ISSUE THREAD

**Issue by jamesamcl** [FoodOntology/foodon#263]
There are four offending lines in `http://purl.obolibrary.org/obo/foodon.owl`:

Line 166648:
```xml
        <obo:IAO_0000117 rdf:resource="https://orcid.org/ 0000-0001-7361-4159"/>
```

Line 166815:

```xml
        <dc:contributor rdf:resource="https://orcid.org/ 0000-0001-5275-8866"/>
```

Line 166839:

```xml
        <dc:contributor rdf:resource="https://orcid.org/ 0000-0001-5275-8866"/>
```

Line 166865:

```xml
        <dc:contributor rdf:resource="https://orcid.org/ 0000-0001-5275-8866"/>
```

The URIs have spaces in them which is not valid RDF/XML (rejected by Apache Jena Riot).

**Comment by ddooley** [comment]
Thanks for spotting this.  We have fixed this now and new foodon.owl in root github has the fix.  I'll close if no further issue raised in the next week!

**Comment by jamesamcl** [comment]
Thanks @ddooley !
