### ISSUE TITLE
meal by time of day - missing supper

### ISSUE THREAD

**Issue by RobertDanhi** [FoodOntology/foodon#266]
A very common name for a time specific meal period is "supper", usually a meal occasion after dinner or instead of dinner after 10pm/ 22:00, then if folks go for some food much later after midnight (such as after bars/dancing/drinking) it can still be called supper, and if at home more  referred to as "midnight snack" (this within Northeast and Southeast Asian context since in much or Europe such as Spain a majority of full service/fine dinning restaurants don't even open for dinner until 9pm)

**Comment by ddooley** [comment]
Thanks for this.  Finally addressing this - it has been added to FoodOn via NCIT term import for Breakfast, Lunch and Supper!  Revised diagram is at bottom of https://github.com/FoodOntology/foodon/issues/236
