### ISSUE TITLE
Upper level FoodOn term renaming

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/foodon#268]
There are a few design issues that motivate some renaming and repositioning. Details below for feedback in the next week or two.  

A move towards recognizing that many organism x part terms can - and need - to be referenced without necessarily involving a food role, suggests that we primarily position organism x part terms under material entity directly, but have it that they can also be multi-homed under a "food material" or "food product" hierarchy. 

There is also the need to distinguish between a taxonomy hierarchy, and an anatomy hierarchy, with whole organisms, proper parts of organisms, and the convenience of referring to a plurality of parts with one precomposed term, as well as the most vague reference to some "animal material" that could be a single whole animal, or a part of one, or several parts.

"food product organismal source" renamed -> organismal source
"part of organism" renamed -> piece of organism
"part of animal" renamed  -> piece of animal
"animal body or body part" renamed -> animal (whole or pieces)

![image](https://user-images.githubusercontent.com/4000582/219566021-dba2d368-2041-4851-be79-8fb4dcddfbf4.png)

**Comment by kaiiam** [comment]
I agree with everything you said, we'll have to think/discuss more about the diagram although it's a good first pass. 

Are you saying we'd assert `food material` has a `food role` and then multi-home classes like `chicken (whole)` under both the `material entity` branch and under `food material`? That seems reasonable to me we should try it out in our demo animal parts code/template.

**Comment by ddooley** [comment]
Chicken (whole) would primarily (declaratively) be under ME / multicellular organism / animal (whole); but from a menu perspective it would be nice to also have it under "chicken food product".  Hoping a simple inference can get it to appear there too.

**Comment by ddooley** [comment]
Here's an updated diagram:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/4000582/220535977-d6e912f1-6086-4e94-b8bc-efb0f80f9846.png">

**Comment by maweber-bia** [comment]
good job! this will definitively clarify the difference between food product and food material

just a detail: not sure about "animal egg", I would prefer "bird egg" or vertebrate vs invertebrate animal egg (this would allow the distinction between shelled eg and unshelled egg)!

I would prefer the term "piece" rather than "portion" but this is rather personal choice... a portion is more something like a part of a homogeneous whole, a piece can be something heterogeneous in my mind.

**Comment by maweber-bia** [comment]
> Chicken (whole) would primarily (declaratively) be under ME / multicellular organism / animal (whole); but from a menu perspective it would be nice to also have it under "chicken food product". Hoping a simple inference can get it to appear there too.

But I think that in a menu, it will be the cooked chicken, not the raw ??  (for example roasted chicken) ?

**Comment by ddooley** [comment]
So the egg hierarchy isn't the complete one; and "animal" currently covers both vertebrates and invertebrates - although that is up for discussion.  And I meant menu in terms of application menu, not culinary menu, but I guess I have to be more careful with my language ;o)  

Look forward to reviewing soon!

**Comment by ddooley** [comment]
Here's the next iteration: https://drive.google.com/file/d/17GPPFyNwtbQSA_vsZqVndVmhCw87wO09/view?usp=share_link

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/4000582/226066749-63f208e5-f95e-48ff-9a5e-076159c4f39d.png">

**Comment by maweber-bia** [comment]
I find the "meat cut" hierarchy better now; about eggs: I still find useless to have 'animal egg' as you have specified 'fish egg", 'hen egg'...each and every animal eggs are not "shelled eggs"... but you can directly connect 'hen egg' as a subclass of 'shelled egg'.

With respect to 'living lettuce' , I understand that a ‘Living lettuce’ is sold with a small, clean root ball still attached. This lettuce is grown on water, in special gutters or on floating platforms. The root ball remains attached to the lettuce until the leaves are picked for consumption. This keeps the lettuce fresher for longer, plus the root ball improves the flavour and crunchiness of the leaves. A living lettuce can contain just one head of lettuce or it can be a mix of several types, such as Lollo Rosso, Lollo Biondo and Oakleaf (https://www.lovemysalad.com/salapedia/living-lettuce). What about a lettuce without root ?

**Comment by ddooley** [comment]
Indeed most veggies get delivered to consumers having been extracted from original whole plants.  The "plant piece" branch supports this.  The PO plant anatomy ontology supplies our vocabulary for these parts, and part of its design philosophy is that when one names a part, one doesn't necessarily mean its connected to some other part of a plant (unlike UBERON which assumes that everything is (logically) connected except for "body products".) so we can use them directly, so "[rosette](http://purl.obolibrary.org/obo/PO_0025615)" is the term for lettuce head!  Then rosette x taxon gives us the kinds of lettuce without root.

**Comment by ddooley** [comment]
OBI has a term "processed material".  I think we could use that prefix to talk about "processed carcass", to distinguish the food related processing, vs. previous term I had in mind which was "modified carcass".

**Comment by ddooley** [comment]
Most of the above renaming is complete in current FoodOn release, except for a bunch of new / updated terms in the animal x anatomical part hierarchy which will be coming on line in the next few months.
