### ISSUE TITLE
NTR: general "pasta food product"

### ISSUE THREAD

**Issue by cmrn-rhi** [FoodOntology/foodon#272]
In FoodOn "pasta food product" is a subclass of "wheat food product":

- plant food product [[FOODON:00001015](http://purl.obolibrary.org/obo/FOODON_00001015)]
  - plant seed food product [[FOODON:00001173](http://purl.obolibrary.org/obo/FOODON_00001173)]
    - cereal grain food product [[FOODON:00001093](http://purl.obolibrary.org/obo/FOODON_00001093)]
      - wheat food product [[FOODON:00001141](http://purl.obolibrary.org/obo/FOODON_00001141)]
        - pasta food product [[FOODON:00001211](http://purl.obolibrary.org/obo/FOODON_00001211)]

But pasta isn't always made with wheat; these days you get corn, quinoa, buckwheat, and even shirataki which is a mushroom so not even a "cereal grain food product". We also get sweet potato noodles which isn't a "plant seed food product" And depending on how descriptive we want to be we could even accommodate noodles made from meat ([example](https://ladyandpups.com/2020/07/24/gluten-free-low-carb-chewy-all-purpose-noodles-made-of-chicken-breast/)) which wouldn't even fall under the "plant food product" hierarchy.

The proposal of this post is that we have a generic version of the pasta hierarchy not tied to cereal grains unless it is a cereal grain version of the term, and move terms like "buckwheat noodle" out from under the wheat "pasta food product".

Perhaps it would be better to place a general "pasta food product" under the "processed food product" [[FOODON:03311737](http://purl.obolibrary.org/obo/FOODON_03311737)] or "prepared food product" [[FOODON:00001180](http://purl.obolibrary.org/obo/FOODON_00001180)] hierarchy rather than the "food product by organism". Side note: I'm not really clear on the difference between "processed food product" vs "prepared food product" in FoodOn as "processed food product" doesn't have a definition and "prepared food product" mentions processes.

**Comment by maweber-bia** [comment]
> The proposal of this post is that we have a generic version of the pasta hierarchy not tied to cereal grains unless it is a cereal grain version of the term, and move terms like "buckwheat noodle" out from under the wheat "pasta food product".
> 
> Perhaps it would be better to place a general "pasta food product" under the "processed food product" [[FOODON:03311737](http://purl.obolibrary.org/obo/FOODON_03311737)] or "prepared food product" [[FOODON:00001180](http://purl.obolibrary.org/obo/FOODON_00001180)] hierarchy rather than the "food product by organism". Side note: I'm not really clear on the difference between "processed food product" vs "prepared food product" in FoodOn as "processed food product" doesn't have a definition and "prepared food product" mentions processes.

You are right and all product hierarchies should be reviewed to avoid mixing botanical origins and process type!

Actually, the difference between  "processed food product" vs "prepared food product" is not clear, and I feel like it comes from former (old) imports. We should distinguish only primary raw products and primary derivatives based on their natural source, and then composite foods separately to prevent them from mixing with each other.

To make the parallel with FoodEX2 (and TransformON) there is a class for "pasta and similar products (uncooked)" where you find filled (stuffed) pasta, plain pasta (not stuffed) and pasta-like products (for example: soy vermicelli, rice noodle, gnocchi, etc.)

I hope this could be helpful!

**Comment by ddooley** [comment]
Re.  difference between "processed food product" vs "prepared food product":  
"prepared food product" intended as ready-to-eat with at most say some application of heat.  
"Processed food product" a bit harder to define, probably why it needs a definition.  Intention was to capture the kinds of subclasses it has - processed ingredient that would contribute to a recipe, but wouldn't be considered a meal in themselves.

**Comment by maweber-bia** [comment]
> "Processed food product" a bit harder to define, probably why it needs a definition. Intention was to capture the kinds of subclasses it has - processed ingredient that would contribute to a recipe, but wouldn't be considered a meal in themselves.

I think that a definition for processed food could be " all kinds of food or ingredients which have undergone a transformation from raw materials" . A prepared food could be a sub-class of processed food with the proposed definition, "prepared food product" intended as ready-to-eat which only needs heating or reheating if any.

**Comment by mateolan** [comment]
I am finding the distinction between prepared and processed a bit
arbitrary--if not outright incorrect...Where are you imagining potato chips
or some such fitting in? What about the rotisserie chicken at the grocery
store? Aren't all prepared foods also processed? Rather than prepared,
perhaps we can say, "Ready-to-eat".

Hot and prepared foods have specific definitions within the USDA for
nutrition assistance programs
<https://www.fns.usda.gov/snap/retailer-eligibility-prepared-foods-and-heated-foods>--and
unless there is a good reason not to, we should probably use these
definitions.
As far as I am concerned, anything that is prepared is by definition also
processed--but we can distinguish *where *the processing occurs, i.e.
factory-processed vs retailer-prepared/processed, vs.
home-processed/prepared...or some such.

I think we need definitions that are less fuzzy, with very clear
distinctions, akin to hyperpalatable foods
<https://onlinelibrary.wiley.com/doi/abs/10.1002/oby.22639>, and foods of
minimal nutritional value
<https://www.fns.usda.gov/cn/foods-minimal-nutritional-value>--which, if I
am not mistaken, are not yet included in FoodOn, or...?

~mc

**Comment by ddooley** [comment]
I was thinking that prepared food would move to be a subclass of processed food, sorry I didn't say that before!  Indeed prepared foods are definitely processed food.  I'll check out those defs! As well Amanda Winsor just informed us about https://www.accessdata.fda.gov/scripts/ora/pcb/tutorial/index.cfm?action=tutorial.lesson4a#class  processed food related codes, which look important to mirror.

**Comment by maweber-bia** [comment]
of course, prepared food are processed food ;-)

Thanks Matthew for the interesting references,  especially the one about "hyperpalatable food", which seems to propose  a more precise definition than the one for  "ultra-processed" food from NOVA !!

**Comment by ddooley** [comment]
And @maweber-bia  I should credit you with leading that thought up above!

**Comment by ddooley** [comment]
"pasta food product" is now under processed food product!
"prepared food product" is now under processed food product as well in current foodon draft! And I've added a see also note there pointing to the link you provided @mateolan , as well as new terms below, so thanks!

We can shorten labels, and hash out better definitions here for:

-     processed food:
    -     prepared food: A food product that is 1) ready or nearly ready for consumption; 2) usually a composite of several foods or ingredients that often belong to distinct product types; 3) usually formulated, mixed and partially or fully cooked.
    -     hyperpalatable food: A food which has a specific combination of fat, sugar, sodium and carbohydrates that makes it artificially rewarding to eat and harder to stop consuming.  [Hyper-Palatable Foods: Development of a Quantitative Definition and Application to the US Food System Database](https://onlinelibrary.wiley.com/doi/abs/10.1002/oby.22639)
    -     minimally nutritional food:

**Comment by ddooley** [comment]
Actually I will close this issue and open a new one.
