### ISSUE TITLE
artichoke heart vs "artichoke"

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/foodon#278]
"artichoke heart" is redundant with "artichoke" unless we add some variance about it being connected to a stem. Not sure which should be normalized/deprecated to the other.

**Comment by maweber-bia** [comment]
In EFSA FoodEX2 there is "Globe artichoke" with the following scope note:
Stem/stalk from the plant classified under the species Cynara cardunculus L. Globe artichoke group , commonly known as Globe artichokes. The part consumed/analysed is not specified. When relevant, information on the part consumed/analysed has to be reported with additional facet descriptors. In case of data collections related to legislations, the default part consumed/analysed is the one defined in the applicable legislation.

I think "artichoke heart" could be appropriate when refereing to some canned/cooked artichoke.... and artichoke could refer to the whole plant. The heart of the artichoke (also called artichoke bottom) is the central part of the plant from which all the leaves are attached. It is the heart of the artichoke that is edible and not the bitter leaves of the  vegetable. We therefore eat the heart and a little of this heart on each of the leaves that we detach as we eat the artichoke.

**Comment by ddooley** [comment]
FoodOn does make distinction between artichoke and "artichoke plant" - we're trying to curate reference to X plant" for each fruit/vegetable etc.  I see we have taxon [Cynara cardunculus var. scolymus](http://purl.obolibrary.org/obo/NCBITaxon_59895) for Globe artichoke, so that (FoodEx2) and Wikipedia seem to align with what you have. We can consolidate our "artichoke plant" to that taxon.

So what remains is the "artichoke heart" with the bulk of its petals/leaves removed, vs the "artichoke head" which still has all those petals/leaves on it?

**Comment by maweber-bia** [comment]
> So what remains is the "artichoke heart" with the bulk of its petals/leaves removed, vs the "artichoke head" which still has all those petals/leaves on it?

yes !!

**Comment by ddooley** [comment]
Updates complete!
