### ISSUE TITLE
Problematic axiom injection in FOODON latest release

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#281]
https://www.ebi.ac.uk/ols4/ontologies/foodon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCARO_0000000

<img width="1571" alt="image" src="https://github.com/FoodOntology/foodon/assets/7070631/00b5c647-5a54-421e-8a72-0f8ff078a511">

Apart from the fact that you should probably pivot to Uberon core subset over CARO which is no longer maintained, you have injected that fact that CARO:0000000 is a BFO:material_entity.. This causes issues because that CARO class encompasses both material _and_ immaterial entities (e.g. Lumens etc). 

While the Mondo import system is not yet updated to the latest ODK (which is resilient to such problems), it still causes some problems (especially for those with more old-school imports systems): https://github.com/monarch-initiative/mondo/pull/6609

**Comment by matentzn** [comment]
Ah you have already fixed it (thx @gouttegd for pointing out): https://github.com/FoodOntology/foodon/commit/d6714ab5c651183601b9ee00f6845806c452a3f7

@ddooley can we have a new FOODON release soon?

**Comment by ddooley** [comment]
This should be resolved now!  I will close, but reopen if problem persists.
