### ISSUE TITLE
NTRs: for 2023 USDA Foundation Foods mapping

### ISSUE THREAD

**Issue by kaiiam** [FoodOntology/foodon#285]
Hello Foodon team, there are several missing terms that USDA's Foundation Foods has sampled which we'd like to be able to map to in Foodon. 

# Flours
### quinoa flour
parent: quinoa food product
### coconut flour
parent: coconut food product
### chestnut flour
parent: chestnut food product
### 00 flour 
parent: wheat flour food product
### semolina flour
parent: durum wheat food product
### semolina flour coarse
parent: semolina flour
### semolina flour fine
parent: semolina flour

# Dairy analog
### oat milk
parent: beverage food product?

# Dairy 
### queso fresco
parent: cheese food product

# Beans
### white kidney bean (dried)
parent: white kidney bean
### white kidney bean (canned)
parent: white kidney bean
### black turtle bean (canned)
parent: black turtle bean
### blackeyed pea (dried) 
parent: blackeyed pea
Note: Foodon already has `blackeyed pea (raw)` not sure if raw and dried are the same for beans. If the same then this isn't needed
### blackeyed pea (canned)
parent: blackeyed pea
### navy bean (canned)
parent: navy bean

# Meats
### pork (ground or minced, raw)
parent: pork (ground or minced)
### chicken meat (ground or minced, raw)
parent: chicken meat (ground or minced)
### for ground beef (raw) 
If possible to add some more add fat content levels 10 and 20 % fat? If not that' ok.
### chicken breast (skinless, boneless, raw)
parent: chicken breast (skinless, boneless) 
### chicken thigh (skinless, debonned, raw)
parent: chicken thigh (skinless, debonned) 
### bacon (cooked)
parent: bacon (whole cut or pieces)

# Other dishes
### sesame butter
parent: sesame food product
### pupusa with beans 
parent: pupusa (dish)
### pork tamale
parent: tamale

**Comment by ddooley** [comment]
NTR IDS:

quinoa flour: http://purl.obolibrary.org/obo/FOODON_00004506
coconut flour: http://purl.obolibrary.org/obo/FOODON_00004507
chestnut flour: http://purl.obolibrary.org/obo/FOODON_00004511
00 flour: http://purl.obolibrary.org/obo/FOODON_00004512
semolina flour: http://purl.obolibrary.org/obo/FOODON_00004513
semolina flour coarse: http://purl.obolibrary.org/obo/FOODON_03303411
semolina flour fine: http://purl.obolibrary.org/obo/FOODON_00004514

Dairy analog
oat milk: http://purl.obolibrary.org/obo/FOODON_00004515
parent: -> **plant derived beverage**

Dairy
queso fresco: http://purl.obolibrary.org/obo/FOODON_00004528

Beans
white kidney bean (dried): http://purl.obolibrary.org/obo/FOODON_00004516
parent: white kidney bean

white kidney bean (canned): http://purl.obolibrary.org/obo/FOODON_00004517
parent: white kidney bean

black turtle bean (canned): http://purl.obolibrary.org/obo/FOODON_00004518
parent: black turtle bean (cooked)

blackeyed pea (dried): http://purl.obolibrary.org/obo/FOODON_03301383
parent: blackeyed pea
Note: Foodon already has blackeyed pea (raw) not sure if raw and dried are the same for beans. If the same then this isn't needed
-> FoodON already has the dried one too.

blackeyed pea (canned) : http://purl.obolibrary.org/obo/FOODON_03302075
navy bean (canned): http://purl.obolibrary.org/obo/FOODON_00004519

Meats
pork (ground or minced, raw): http://purl.obolibrary.org/obo/FOODON_00004520
chicken meat (ground or minced, raw): http://purl.obolibrary.org/obo/FOODON_00004521
chicken breast (skinless, boneless, raw): http://purl.obolibrary.org/obo/FOODON_00004522
chicken thigh (skinless, debonned, raw): http://purl.obolibrary.org/obo/FOODON_00004523
bacon (cooked): http://purl.obolibrary.org/obo/FOODON_00004524

Other dishes
sesame butter: http://purl.obolibrary.org/obo/FOODON_00004525

pupusa with beans
renamed: **pupusa with bean filling**: http://purl.obolibrary.org/obo/FOODON_00004526

pork tamale: http://purl.obolibrary.org/obo/FOODON_00004527

**Comment by ddooley** [comment]
About:

```
for ground beef (raw)
If possible to add some more add fat content levels 10 and 20 % fat? If not that' ok.
```

We will have to discuss this one in the FoodOn curation group.  I think we could have ground beef (lean, raw) or (fatty, raw) but would be leary of putting in %.

**Comment by ddooley** [comment]
Our new animal parts template has regular and lean categories of meat, so we'll have beef terms for these soon.  Closing this now.
