### ISSUE TITLE
FOODON web site links broken

### ISSUE THREAD

**Issue by caufieldjh** [FoodOntology/foodon#290]
Apologies if there's a better place for this issue.

Some links on https://foodon.org/ currently redirect to broken or unsavory locations.

On https://foodon.org/resources/software-and-db/ for example:
* https://index.globalnames.org/ is a 404
* https://yourterm.org/yourterm-food/ is a redirect

On https://foodon.org/resources/food-humour/ , the link to the peanut butter sandwich video (https://www.youtube.com/watch?v=Ct-lOOUqmyY) is private.

**Comment by kltm** [comment]
Related, I'd also note that links in OLS often include the closing `)`; http://www.ebi.ac.uk/ols4/ontologies/foodon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFOODON_03301906 .

**Comment by ddooley** [comment]
Thanks for this feedback!  I've updated the indicated links now!

As for the "SIREN DB annotation" references, I see Ontobee and OLS are both including tailing parentheses of a parenthasized URL in the text. I suspect this can't be solved just by adding a trailing /.  I think we'll duck and solve this issue by simplifying those foodon references to basic ontology code refs [FOODON:12345678].  I'll let you know here when that is done.

**Comment by ddooley** [comment]
Our draft foodon-edit.owl now solves the SIREN DB link problem.  We'll release a new foodon version within a few weeks.
