### ISSUE TITLE
Version IRI is not updated to reflect the current release

### ISSUE THREAD

**Issue by SaschaLosko** [FoodOntology/foodon#292]
While within the `<owl:Ontology>` element `<dcterms:date>` is correctly set to `2023-12-18`, the date of the current release, the version IRI however remains set to `http://purl.obolibrary.org/obo/foodon/releases/2023-05-03/foodon.owl`

This is inconsistent with the typical use of version IRIs and, in our case, interferes with the detection of new releases. Would it be possible to change this so that the version IRI is in sync with your releases?

**Comment by ddooley** [comment]
I just noticed this.  We'll make sure to address this in our upcoming conversion of FoodOn to work with latest ODK which should cover that.  Sorry for complication!

**Comment by ddooley** [comment]
This is now resolved!
