### ISSUE TITLE
Hazardous vs edible food hierarchy within FoodOn

### ISSUE THREAD

**Issue by ddooley** [FoodOntology/foodon#295]
We need to finesse the terms used to describe hazardous vs. safe to eat food, before they are entered into FoodOn.  We're looking at this kind of structure:

<img width="804" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/90bf6c7f-3a70-4878-afa6-0a0bcfa14325">

Basically, some kinds of hazardous food material, like cassava root, or large coconut pieces, can be made edible with processing.

Feedback appreciated!

**Comment by maweber-bia** [comment]
Thank you for the nice diagram, but I think there is some contradiction between "edible hazardous  food material" with respect to the definition of "edible material" --> I suggest edible = orally ingestible, and a class "safe edible food material" vs "hazardous edible food material" (at the moment the definition of edible material specify "non-poisonous material,..." but this is not reflected in the label

**Comment by marieALaporte** [comment]
Where would fruit or vegetable skin fit in this diagram ? There are edible but some people get rid of it. Do you want to tackle that through having a term for peeled for those food items? This is something that we will be interested in having for PTFI. 

How are you planning on building those hierarchies? do you plan on having specific properties for those. Or this more something that people will be using when annotating data and creating instances ?

**Comment by oldskeptic** [comment]
Part of the trouble that I see is that **inedible** and **uneatable** are often used as superlatives in common language and their dictionary definitions are imprecise and occasionally synonymous.  I appreciate I am being english-centric here but it serves to communicate intent:

* **unpalatable** may be a better label for cases that account for discomfort rather than harm.
* **Comestible** may be a better label than **edible**. 
* I would like an approach that does not force membership in disjoint classes like **comestible** and **non-comestible**. The reason for this is that it allows maneuvering room for untidy situations such as @marieALaporte 's fruit peels. Banana or Orange peels won't kill you but you probably don't want to eat it.
* A **rotten**, **comestible** fruit is an annoying corner case because we'd be trying to class an orange as both **comestible** and **rotten** and in most cases **rotten** implies **non-comestible** (unless you're in a few other corner cases of **cheese**). The only "sane" solution that I see is that the comestible orange is transformed into a **rotten**, **non-comestible** and **unpalatable** orange by a **process**. Or, we keep the comestible class away from the fruit varietal and class the specific instance of the Orange as **comestible** / **non-comestible** over its lifetime.
* A separate "Food Hazard" might be valuable in it's own right, can we pull most of it from HACCP?

**Comment by maweber-bia** [comment]
> Part of the trouble that I see is that **inedible** and **uneatable** are often used as superlatives in common language and their dictionary definitions are imprecise and occasionally synonymous. I appreciate I am being english-centric here but it serves to communicate intent:
> 
>     * **unpalatable** may be a better label for cases that account for discomfort rather than harm.
+1
> 
>     * **Comestible** may be a better label than **edible**.
+1 although edible and eatable have quite the same meaning as comestible 
> 
>     * I would like an approach that does not force membership in disjoint classes like **comestible** and **non-comestible**. The reason for this is that it allows maneuvering room for untidy situations such as @marieALaporte 's fruit peels. Banana or Orange peels won't kill you but you probably don't want to eat it.
>
You can eat orange peels or even banana peel when they are processed (citrus peel can be grated  or candied, banana peels are comestible: in India or Bangladesh, iIt's common to cook curries using banana peels)

>     * A **rotten**, **comestible** fruit is an annoying corner case because we'd be trying to class an orange as both **comestible** and **rotten** and in most cases **rotten** implies **non-comestible** (unless you're in a few other corner cases of **cheese**). The only "sane" solution that I see is that the comestible orange is transformed into a **rotten**, **non-comestible** and **unpalatable** orange by a **process**. Or, we keep the comestible class away from the fruit varietal and class the specific instance of the Orange as **comestible** / **non-comestible** over its lifetime.

rotten does not always imply non-comestible, as  mentionned for cheeses ; I think you should apply some specific rules with respect to the kind of rotten food, and even to the kind of rotting agent ? 

> 
>     * A separate "Food Hazard" might be valuable in it's own right, can we pull most of it from HACCP?

are you thinking of different kinds/classes of hazards such as biological, chemical, physical and allergen "contamination" ?

**Comment by oldskeptic** [comment]
> > ```
> > * **Comestible** may be a better label than **edible**.
> > ```

It avoids common english exaggerations; en français on dit souvent "c'est pas mangeable", même si la nourriture est comestible. We should address this in the definition but the languages-specific labels matter for the concepts.

> You can eat orange peels or even banana peel when they are processed (citrus peel can be grated or candied, banana peels are comestible: in India or Bangladesh, iIt's common to cook curries using banana peels)

Yes, thus unprocessed orange peels would be unpalatable but still comestible. Candied orange peels would be both unpalatable and comestible. 

> rotten does not always imply non-comestible, as mentionned for cheeses ; I think you should apply some specific rules with respect to the kind of rotten food, and even to the kind of rotting agent ?

A per my previous comments, the size of those rules will become unmanageable. I'd support an instance-based approach for this.

> are you thinking of different kinds/classes of hazards such as biological, chemical, physical and allergen "contamination" ?

I like @ddooley 's current hierarchy. HACCP is a short-cut to how commercial kitchens work, so I'm keen on it.

**Comment by maweber-bia** [comment]
> It avoids common english exaggerations; en français on dit souvent "c'est pas mangeable", même si la nourriture est comestible. We should address this in the definition but the languages-specific labels matter for the concepts.

Right, "c'est pas mangeable" = it is not good, not palatable whereas "c'est pas comestible" = Which can not be used as food by human beings.

So, I like these nuances:

- edible and eatable both refer to something that is "able to be eaten," but edible is usually used to describe something that is safe to eat, without regard to taste, while eatable often describes something that has some level of acceptable flavor (https://www.merriam-webster.com/grammar/edible-vs-eatable-usage)
- edible= orally ingestible=able to be eaten without causing harm =safe (in French: consommable, ingérable, mangeable)
- eatable=acceptable=palatable (in French=acceptable, palatable)
- comestible= which can be used as food by human beings (in French=comestible)
- unpalatable may be a better label for cases that account for discomfort rather than harm.
- hazardous=unsafe with respect to biological, chemical, physical,or allergen contamination



> Candied orange peels would be both unpalatable and comestible.

I like candied orange ;-)  I think "palatable or unpalatable" is depending on preferences 



> A per my previous comments, the size of those rules will become unmanageable. I'd support an instance-based approach for this.

That was also the meaning of my previous statement : an instance-based approach is required

cheers!

**Comment by oldskeptic** [comment]
> > Candied orange peels would be both unpalatable and comestible.
> 
> I like candied orange ;-) I think "palatable or unpalatable" is depending on preferences

s/unpalatable/palatable ; my typo.

**Comment by ddooley** [comment]
- Palatable / unpalatable is great!  Note about instances/vs class: indeed we may find these terms are only used in the instance level due to personal preference.  On the other hand one may say for some vegetarians the unpalatability of meat is the deciding factor, for others the sustainability factor is more important.  So generalizations can be made about patterns that use this language.
- Indeed if "edible" carries semantics of personal preference, that is not what I was after. I wanted a term that was about ability to consume a substance without hazard, and which ignores personal preference factors.  **Comestible** is a new one on me, lets discuss!
- I know "edible hazardous food material" sounds like a contradiction.  Actually I realize it probably can be skipped, so a "hazardous food material" instance is input to food preparation.  This covers chopping food, cooling food, cooking food...
- Yes, we could rename "edible food material" to "orally ingestible material" and "orally ingestible food material"
- @marieALaporte & @oldskeptic  it would be great to support the diagram with further axioms on the terms but the diagram would literally reflect a preliminary hierarchy of terms in FoodOn or perhaps ONS (which is getting a revamp right now). What I see as key is that these terms are used to tag content in a clear way.

**Comment by ddooley** [comment]
Updated diagram bu still have to sort out definitions

![Screenshot 2024-01-25 at 9 58 11 AM](https://github.com/FoodOntology/foodon/assets/4000582/916f7329-7e9b-45f1-b764-be8f2e5c5d69)

**Comment by oldskeptic** [comment]
A few more thoughts on hazards: The austria wine scandal where glycol was being used to sweeten wine, which would be "edible hazardous food material": https://en.wikipedia.org/wiki/1985_Austrian_diethylene_glycol_wine_scandal

@ddooley How do you feel about keeping palatable / unpalatable as a class outside food material? 

The reason I bring this up is that it makes it possible to have what otherwise would handle certain hazardous situations: 

Anti-freeze (ethylene glycol) is toxic (non-comestible) but sweet (palatable) which results in animal / human poisoning cases.

**Comment by maweber-bia** [comment]
> * Indeed if "edible" carries semantics of personal preference, that is not what I was after. I wanted a term that was about ability to consume a substance without hazard, and which ignores personal preference factors.  **Comestible** is a new one on me, lets discuss!

-> "edible" does not carry semantics of personal préference, but "palatable/unpalatable" does

I suggest to replace "edible" by "comestible" in your diagram:
- palatable/unpalatable food  subclasses of comestible food
- comestible food subclass of comestible material and subclass of food material
-comestible material subclass of material entity

Def comestible food: A food material which can be used as food by human beings 



> * I know "edible hazardous food material" sounds like a contradiction.  Actually I realize it probably can be skipped, so a "hazardous food material" instance is input to food preparation.  This covers chopping food, cooling food, cooking food...
> 
> * Yes, we could rename "edible food material" to "orally ingestible material" and "orally ingestible food material"

Def edible food: A food material which is orally ingestible

Def edible hazardous food: A food material able to be eaten but potentiallly causing harm =unsafe

**Comment by oldskeptic** [comment]
@damion "Hazard food Material" in the hierarchy graph might be a problem; I'm thinking of a food that is edible / comestible, palatable but still hazardous: Scalding is already in there, but what about foods such as cinnamon where the "spoonful of cinnamon challenge" has caused choking accidents. 

Other corner case: Hops pellets are edible / comestible but not palatable as are like orange peels. 

 "edible hazardous food material" vs "hazardous food material", where would we classify an ingredient that is not ...food, such as baking soda (Sodium bicarbonate)? The different between tagging it as food and / or edible is really intent. Should we have a separate term for "Food Safe" which would also apply to machinery and containers?

**Comment by ddooley** [comment]
About comestible - is it limited to human beings being the consumer?  I think we might as well keep things general so that we can cover food for domesticated animals too.

Updated diagram from Thursday Feb 1 discussion:
![image](https://github.com/FoodOntology/foodon/assets/4000582/3ed84c77-71dc-47ec-9401-44db87c3d2b9)

**Comment by maweber-bia** [comment]
let's think about this:

- edible= orally ingestible
- inedible= which can not be orally ingested /eaten without appropriate treatment during a transformation process
- eatable= acceptable (from a cultural/organoleptic point of view)--> acceptable for human being or for animal, depending on the kind of animal  ;-)
- palatable = pleasant, comfortable in mouth,, ....--> organoleptic characteristics for human being as well as for animals
- comestible= which can be eaten **by human beings** (for animal we generally don't use "**food"** but **"feed",** let's say "feed" is not comestible by human beings...or at least not eatable)
- digestible = orally ingestible material that can be digested (by human beings or animals...)
- edible hazardous food material : any kind of food material that represent a hazard/risk when eaten by human

then: 
hazardous (edible) food material subclass of edible food material
eatable (edible) food material subclass of edible food material
comestible (edible) food material subclass of edible food material

exemple of an inedible food material: an apple can not be orally ingested as a whole but can be orally ingested once cut into smaller pieces ( --thank to Matthew for this example) --> the process of cutting an apple makes it edible

but be careful:  you may choke if the apple piece is too big or if you swallow it the wrong way !!! 
I'm not even talking about poisoned apples ;-)


Feedback ?

**Comment by ddooley** [comment]
@oldskeptic above I mention "palatable food" and "unpalatable food", and indeed anti-freeze is neither of those.  I agree it is palatable so we could have an additional "palatable material" and "unpalatable material" sitting under material entity so I've adapted diagram to that.

About glycol-sweetened wine, it is certainly a "poisonous food material".  That justifies that "edible hazardous food material" be a subclass of "hazardous food material"!

**Comment by oldskeptic** [comment]
> About comestible - is it limited to human beings being the consumer? I think we might as well keep things general so that we can cover food for domesticated animals too.

There's an intersection with food allergies here that might be annoying, but what do you think about having a comestible class that contains a restriction on species (or sub-group of species)? That would allow for "Comestible", "Human Comestible" or "Cat Comestible" etc...

**Comment by oldskeptic** [comment]
> exemple of an inedible food material: an apple can not be orally ingested as a whole but can be orally ingested once cut into smaller pieces ( --thank to Matthew for this example) --> the process of cutting an apple makes it edible 
> but be careful: you may choke if the apple piece is too big or if you swallow it the wrong way !!! I'm not even talking about poisoned apples ;-)

Snow White is indeed on notice! I am not completely happy with (in)edible because the average person would think it's weird to say that an apple is inedible which creates an unnecessary scientific / layman gap. I would prefer "Whole Apple" == "Non-Ingestible food material" and "Apple Slice" == "Ingestible food material" which doesn't depend on inheritance and handles the "doesn't fit in mouth, requires mechanical separation" bit.

Encore, c'est une distinction du mot versus la definition mais je crois qu'il y a de la valeur dans notre discussion. C'est le meme problemes existes en francais, et al. 
 
> * comestible= which can be eaten **by human beings** (for animal we generally don't use "**food"** but **"feed",** let's say "feed" is not comestible by human beings...or at least not eatable)

I'm going to push back on this; in everyday slang "Cat Food", "Pig Feed", "Dog Food", etc... But "Feed" is a term for "comestible for non-humans"?

**Comment by maweber-bia** [comment]
Actually, "palatable" or "eatable" or "digestible" are also classes that should contain some restrictions on species...

From my perspective, feed= non comestible for human....

**Comment by oldskeptic** [comment]
> About glycol-sweetened wine, it is certainly a "poisonous food material". That justifies that "edible hazardous food material" be a subclass of "hazardous food material"!

Annoying corner case: How are we going to deal with water toxicity vs "glycol-sweetened wine" == "poisonous food material"? One model is concentration based, the other is logically based.

**Comment by maweber-bia** [comment]
(potable = drinkable)  water is not toxic if you are drinking it in a reasonable amount; a poisonous food material implies that a poison (=chemical contaminant) has been added

Any food or beverage should be consumed in a reasonable amount (this is the principle of any balanced diet)   ...I think that as long as the food or the beverage is comestible or drinkable there should not be considered as "toxic"... the dose is relative to the instances not to the classes

**Comment by ddooley** [comment]
Well, I see now that "**contaminated food material**" is a good class to have, where bacterial (e.g. bad E-coli) or chemical contamination occurs.  But in contrast, it would be good to have a term that covers food containing poisonous chemicals that are naturally part of a food, such as cassava root & its cyanide variant.

We should encourage that the **effect** of a chemical and biological hazard is a function of exposure dose and time duration, as well as a person's sensitivity.  Trace amounts of anything may have no effect.   Liaison with ECTO: "The Environmental Conditions, Treatments, and Exposures Ontology" could be helpful here.

**Comment by maweber-bia** [comment]
> Well, I see now that "**contaminated food material**" is a good class to have, where bacterial (e.g. bad E-coli) or chemical contamination occurs. But in contrast, it would be good to have a term that covers food containing poisonous chemicals that are naturally part of a food, such as cassava root & its cyanide variant.
> 
 
let's also see the case of some antinutritional compounds (especially  plant metabolites) in liaison with CDNO

**Comment by ddooley** [comment]
The latest diagram avoids the word "inedible", though that can arise as a broad or exact synonym in vocabulary if people want. @maweber-bia that makes your definition of it match "hazardous food material", so an exact synonym of that term?  And "orally ingestible material" would have edible as an exact synonym.  It covers more than food, so e.g. edible pill.

I'm a little puzzled about why we would turn to using "comestible" if 1) it doesn't imply something particular like food which is "safe to eat" (directly); and 2) its use is running up against the same issues that "food" itself is?  If we have to turn to qualifying either one, e.g. "human comestible" vs "human food", "cat comestible" vs "cat food", then why not just stick with qualifying the most common word "food"?

**Comment by ddooley** [comment]
Since I just signed up for ChatGPT, I thought I'd checkup on what ChatGPT 4 thinks about this.  At first I was ready to dismiss it as sort-of on target, illustrating how ontology thinking about classes of entity is 1 step removed from its conceptual space.  None of the subclasses are "food" per se.
<img width="657" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/d1cbd447-6853-4dbc-af4a-bc1d3d0d3119">
But then I realized I didn't use the word "ontology" in question so tried that:
<img width="892" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/c795d3b3-d353-41b8-aecd-cecf30ac7f2b">
And I tried having it understand that top level term should be singular:
<img width="986" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/237d6ed9-628d-4d1b-9a70-d884853c26b9">
Told it to add allergens
<img width="1163" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/139c98e7-d562-4906-84b6-d05855635758">
Told it to "make each node be a food material having that node's hazard":
<img width="1307" alt="image" src="https://github.com/FoodOntology/foodon/assets/4000582/5b402689-f5c1-4e0c-8620-e3830252223c">
I asked it to be comprehensive about foods associated with hazards.

> Creating a comprehensive entity-relationship diagram with a full list of food materials associated with each kind of hazard requires detailing a wide variety of food items and their respective hazards. However, due to constraints in processing and visualizing complex diagrams with a large amount of data in a single request, the attempt to generate such a detailed diagram was unsuccessful.
> 
> For a comprehensive understanding, it's important to consider multiple food categories and their associated hazards, such as:
> 
> Pathogenic Agents: Various bacteria, viruses, and parasites can be found in a wide range of foods, including chicken, beef, leafy greens, eggs, and shellfish, with pathogens like Salmonella, E. coli, Norovirus, and Hepatitis A.
> Chemical Toxins: Foods like fish can contain mercury and PCBs; vegetables may have pesticide residues, and canned goods could contain BPA from can linings.
> Physical Foreign Objects: Processed meats might contain bone fragments; candies could have plastic pieces, and soft drinks may have glass shards.
> Allergens: Common allergenic foods include peanuts, wheat, milk, soy, tree nuts, and shellfish, each associated with specific allergic reactions or intolerances, such as peanut allergy, gluten allergy (celiac disease), lactose intolerance, soy allergy, tree nut allergy, and shellfish allergy.
> To visualize these relationships accurately in a single diagram, it would be necessary to simplify the information or create multiple, smaller diagrams focused on specific hazard categories or food groups. This approach would help in managing the complexity and ensuring the diagram remains clear and informative. If you have specific categories or a more focused list you'd like to visualize, please let me know, and I can attempt to create a diagram based on that.

So that's a reasonable point - complaining about doing too much work for me!  At any rate, it suggests a number of use-cases to consider, and that for every kind of hazardous food material, there is a kind of hazard to name that lies within it.

Lastly I asked to have it add "temperature food hazards" but it interpreted that narrowly to be about the environmental temperature condusive to fostering toxic bacteria in food. So I had to be more precise.

> Adding foods that present a hazard due to being too hot or too cold expands the scope of temperature hazards in food safety. Unfortunately, I'm currently unable to generate a visual diagram due to a technical limitation. However, I can describe how these items might be included in an entity-relationship model focused on food safety:
> Temperature Hazard: This category could be divided into two sub-categories to address the specific risks associated with foods that are too hot or too cold:
> Too Hot: Foods like hot soups or beverages can cause scalding if not handled or consumed with care. The immediate risk here is physical injury rather than foodborne illness.
> Too Cold: Items such as ice cream can cause discomfort or minor injuries like freezer burn to the mouth. Though less common, extremely cold foods can pose a risk if they lead to tissue damage or are consumed in a way that could harm the body.
> This detailed approach helps underline the importance of temperature control, not just for preventing microbial growth but also for avoiding physical harm when consuming food. Proper food handling and consumption practices are essential for ensuring safety and preventing injuries or illnesses related to temperature extremes.
>

**Comment by maweber-bia** [comment]
> The latest diagram avoids the word "inedible", though that can arise as a broad or exact synonym in vocabulary if people want. @maweber-bia that makes your definition of it match "hazardous food material", so an exact synonym of that term? And "orally ingestible material" would have edible as an exact synonym. It covers more than food, so e.g. edible pill.
> 
From my perspective, inedible is antonym of edible, that means inedible = not orally ingestible
> I'm a little puzzled about why we would turn to using "comestible" if 1) it doesn't imply something particular like food which is "safe to eat" (directly); and 2) its use is running up against the same issues that "food" itself is? If we have to turn to qualifying either one, e.g. "human comestible" vs "human food", "cat comestible" vs "cat food", then why not just stick with qualifying the most common word "food"?

Right, comestible is redundant, we can get rid of this adjective if we are using "food" in the label

**Comment by maweber-bia** [comment]
I think "comestible" could be a broad synonym of "eatable" ?

**Comment by ddooley** [comment]
I'll do a version of our diagram above that tries to place the synonyms according to discussions so far.

**Comment by ddooley** [comment]
Also I'm following up with Sander van Leeuwen re. [his presentation](https://youtu.be/VaBJ7XTv5RM?t=8008) last summer on the subject.

**Comment by ddooley** [comment]
@maweber-bia comestible as synonym sounds good!

On subject of AI, Google Gemini can't generate diagrams directly but it was able to answer an RDF graph question: 

______________

**can you describe an RDF graph of hazardous food concepts?**

**RDF Graph of Hazardous Food Concepts**
This RDF graph describes some hazardous food concepts and their relationships.

**Classes:**

- HazardousFoodConcept
- Ingredient
- PreparationMethod
- Microorganism

**Properties:**

- hasIngredient (links HazardousFoodConcept to Ingredient)
- requiresPreparation (links HazardousFoodConcept to PreparationMethod)
- canCause (links HazardousFoodConcept to Microorganism)
- causesSymptoms (links Microorganism to symptoms (literal))

**Example Nodes:**

- HazardousFoodConcept: UndercookedChicken, RawSprouts
- Ingredient: Chicken, Sprouts
- PreparationMethod: Undercooking
- Microorganism: Salmonella, E. Coli

**Example Triples:**

- UndercookedChicken hasIngredient Chicken
- RawSprouts hasIngredient Sprouts
- UndercookedChicken requiresPreparation Undercooking
- UndercookedChicken canCause Salmonella
- Salmonella causesSymptoms "food poisoning, nausea, vomiting"
- RawSprouts canCause E. Coli
- E. Coli causesSymptoms "diarrhea, abdominal cramps"

**Benefits:**

This RDF graph allows for easier querying and understanding of relationships between hazardous food concepts. For instance, you could query the graph to find all HazardousFoodConcepts that can cause Salmonella or all the symptoms associated with E. Coli.

**Additional Considerations:**

The graph can be extended to include additional classes and properties, such as FoodStorage, ConsumptionTime, or SeverityOfSymptoms. Specific details about ingredients and microorganisms can be included as additional nodes and properties. This is a basic example, and the complexity of the graph can be increased depending on the desired level of detail for your specific use case.

**Comment by ddooley** [comment]
And similarly it was happy to give me an example ontology.
__________
**can you describe an ontology of hazardous food concepts?**

**Absolutely! Here's an ontology for hazardous food concepts:**

**Classes:**

- Food
  - Intact Food (unprocessed)
    - Plant-Based Food (fruits, vegetables, grains)
    - Animal-Based Food (meat, poultry, seafood, dairy)
  - Processed Food
    - Minimally Processed (washed, chopped)
    - Highly Processed (canned, frozen, pre-made meals)
- Hazard
  - Biological Hazard (bacteria, viruses, parasites)
  - Chemical Hazard (toxins, pesticides, cleaning agents)
  - Physical Hazard (glass shards, bones, metal)
  - Allergen (peanuts, gluten, shellfish)
- Foodborne Illness (diarrhea, nausea, food poisoning)
- Contamination Event (source of hazard introduction)
- Food Handling Practice (storage, preparation, cooking)

**Relationships:**

- Has Hazard: Links a Food class to a specific Hazard class. One food item can have multiple hazards (e.g., E. coli and Salmonella in raw chicken).
- Causes: Links a Hazard class to a Foodborne Illness class. A hazard can cause multiple illnesses depending on the severity and individual susceptibility.
- Introduced By: Links a Contamination Event to a specific Food class. This describes how the hazard got into the food (e.g., contaminated water used for irrigation).
- Influenced By: Links a Food Handling Practice to the likelihood of a Contamination Event or the severity of a Hazard. For example, improper storage temperature can increase bacterial growth.

**Additional Properties:**

- Food: Source (farm, processing plant), Processing steps
- Hazard: Severity (low, medium, high), Growth conditions (temperature, pH)
- Foodborne Illness: Symptoms, Duration

**Benefits:**

This ontology provides a structured way to represent knowledge about hazardous food concepts. It can be used for:

- Developing food safety regulations
- Designing food traceability systems
- Building decision support tools for food handling
- Standardizing terminology in food safety research

This is a basic ontology, and additional classes and relationships can be added depending on specific needs. For instance, you might include details about food preservation methods or regulations from different countries.

**Comment by maweber-bia** [comment]
> We should encourage that the **effect** of a chemical and biological hazard is a function of exposure dose and time duration, as well as a person's sensitivity. Trace amounts of anything may have no effect. 

we should consider the person's sensitivity with respect to allergenic substances (even "trace amounts" may have an effect for hypersensitive people) - see VITAL® (Voluntary Incidental Trace Allergen Labelling) https://vital.allergenbureau.net/

**Comment by maweber-bia** [comment]
> And similarly it was happy to give me an example ontology.
> 
> **can you describe an ontology of hazardous food concepts?**
> 
> **Absolutely! Here's an ontology for hazardous food concepts:**
> 
> **Classes:**
> 
>     * Food
>       
>       * Intact Food (unprocessed)
>         
>         * Plant-Based Food (fruits, vegetables, grains)
>         * Animal-Based Food (meat, poultry, seafood, dairy)

happy to see those classes are "equivalent" to agricultural raw primary commodities in TransformON/FoodEX2 (https://quantum.mia-ps.inrae.fr/PO2/Ontology/TransformON/Component/aIZSH2)

>       * Processed Food
>         
>         * Minimally Processed (washed, chopped)
>         * Highly Processed (canned, frozen, pre-made meals)

Happy to see 2 different levels of processing....with some associated processes... and that washing and cutting  can be considered as "minimalist processes"
> 
>     * Hazard
>       
>       * Biological Hazard (bacteria, viruses, parasites)
>       * Chemical Hazard (toxins, pesticides, cleaning agents)
>       * Physical Hazard (glass shards, bones, metal)
>       * Allergen (peanuts, gluten, shellfish)
> 
happy to see the 4 categories of hazards we have already in mind ;-)

>     * Foodborne Illness (diarrhea, nausea, food poisoning)
> 
>     * Contamination Event (source of hazard introduction)
> 
>     * Food Handling Practice (storage, preparation, cooking)
> 
>
Good point for google Gemini : those 3 classes are related to "processes" rather than "products"


> **Relationships:**
> 
>     * Has Hazard: Links a Food class to a specific Hazard class. One food item can have multiple hazards (e.g., E. coli and Salmonella in raw chicken).
> 
>     * Causes: Links a Hazard class to a Foodborne Illness class. A hazard can cause multiple illnesses depending on the severity and individual susceptibility.
> 
>     * Introduced By: Links a Contamination Event to a specific Food class. This describes how the hazard got into the food (e.g., contaminated water used for irrigation).
> 
>     * Influenced By: Links a Food Handling Practice to the likelihood of a Contamination Event or the severity of a Hazard. For example, improper storage temperature can increase bacterial growth.
> 
> 
> **Additional Properties:**
> 
>     * Food: Source (farm, processing plant), Processing steps
> 
>     * Hazard: Severity (low, medium, high), Growth conditions (temperature, pH)
> 
>     * Foodborne Illness: Symptoms, Duration
> 
> 
> **Benefits:**
> 
> This ontology provides a structured way to represent knowledge about hazardous food concepts. It can be used for:
> 
>     * Developing food safety regulations
> 
>     * Designing food traceability systems
> 
>     * Building decision support tools for food handling
> 
>     * Standardizing terminology in food safety research
> 
> 
> This is a basic ontology, and additional classes and relationships can be added depending on specific needs. For instance, you might include details about food preservation methods or regulations from different countries.

**Comment by SLvanL** [comment]
Hi all,
 
We from Wageningen Food and Biobased Research from the WUR are working on an ontology for food safety hazards and processes as part of the project Food Safety By Design. In the ontology we define some concepts and relations that I already see occurring in the posts here, so that is good to know! The ontology is designed to accommodate a link between food ingredients (including food ingredients that come from side streams) and microbiological and chemical hazards (physical and allergens are out of scope for the project). Moreover the ontology also accommodates to link data and knowledge on the effect of processes on the present hazards (e.g. grilling meat at 120 degrees for 4 min might eliminate the hazard salmonella, but might introduce the hazard acrylamide). Instead of a Contamination Event class, we have a Process Effect class (to accommodate for both contamination and decontamination events). In the case of storage, it is also possible to store data on the growth conditions of a hazard.
 
I also agree that source is an important factor to indicate presence of hazards, not only to indicate whether it was processed (as suggested by Gemini), but also to indicate where it came from (crops grown in South America may contain different hazards than crops from grown in Europe for example)
 
I would also like to introduce my colleague Bengü Öztürk @benguoz2. We work together on the ontology in this project.

**Comment by ddooley** [comment]
Thanks for the update Sander.  I remember the process level detail in analyzing risk that you presented last summer. Just to say I think FoodOn would like to name upper level categories of food hazard as shown above, but would defer to projects like yours to carry on the risk assessment vocabulary and detailed modelling required at that level, thus supporting FAIR representation of research work and eventually agency and industry usage.

In terms of OBO Foundry strict compatibility one issue is the way object and data properties are used in modelling but that can be normalized or mapped at a later date. By the way we're working on a "food characteristics" paper right now that explores the gap analysis of vocabulary needed vs what is in OBO Foundry, (e.g. what PATO does or doesn't cover and how to fix that).

**Comment by ddooley** [comment]
Feel free to add more comments, but as I have added the above general food hazard hierarchy to the foodon draft version, I am going to close this now.

**Comment by ddooley** [comment]
Update, today Deepseek 7b provided an intermediate and final hierarchy, when asked: " what kinds of hazardous food are there?"

- **Food Safety Hazards**
  - PhysicalHazards
    - Temperature Extremes
    - Storage Conditions Issues
  - ChemicalHazards
    - AdditiveChemicals
      - Artificial Preservatives
      - Food Dyes
    - EnvironmentalContaminants
      - Heavy Metals
      - Pesticides
    - ToxicSubstances
      - PathogenicToxins
- **Biological Hazards**
  - Pathogens
    - BacterialPathogens
      - Escherichia
      - Salmonella
    - ViralInfections
      - Influenza
      - Hepatitis
    - Parasites
      - Flies
      - Roundworms
- **PhysicalHazards**
  - ContaminationIssues
    - CrossContamination
    - FoodborneBacteria
  - HandlingIssues
    - TemperatureRisks
    - PackagingRisks

**Final:** 

1. **Food Hazard**
   - **PhysicalHazards**
     - Temperature Extremes
     - Storage Conditions Issues
     - CrossContamination
     - PackagingRisks
   - **ChemicalHazards**
     - AdditiveChemicals
       - ArtificialPreservatives
       - FoodDyes
     - EnvironmentalContaminants
       - HeavyMetals
       - Pesticides
     - ToxicSubstances
       - PathogenicToxins
   - **Biological Hazards**
     - Pathogens
       - BacterialPathogens
         - Escherichia
         - Salmonella
       - ViralInfections
         - Influenza
         - Hepatitis
       - Parasites
         - Flies
         - Roundworms

But then I asked it to "provide the food hazard hierarchy with terms in singular name" and it replied:

### **Food Safety Hazard**
   - **Physical Hazard**
     - Temperature Extreme
     - Storage Condition Issue
     - Cross-Contamination
     - Handling Technique Issue
   - **Chemical Hazard**
     - Additive Chemical
       - Artificial Preservative
       - Food Dye
     - Environmental Contaminant
       - Heavy Metal
       - Pesticide
     - Toxic Substance
       - Pathogenic Toxin

### **Biological Hazard**
   - **Pathogen**
     - Bacterial Pathogen
       - Escherichia
       - Salmonella
     - Viral Infection
       - Influenza
       - Hepatitis
     - Parasite
       - Flies (mosquitoes)
       - Roundworms

### **Physical Hazard**
   - Contamination Issue
     - Cross-Contamination
     - Foodborne Bacteria
   - Handling Technique Issue
     - Improper Temperature for Storage or Preparations
     - Residue on Packaging Materials

### **Chemical Hazard**
   - Additive Chemical
     - Artificial Preservatives
     - Food Dyes
   - Environmental Contaminant
     - Heavy Metals
     - Pesticides
   - Toxic Substance
     - Pathogenic Toxins

**Comment by maweber-bia** [comment]
Well done!
We can see an inconsistency for "physical hazards" because of **the notion of "contamination"**, especially "**cross contamination**", which should be defined properly!

--> you may have  **a cross contamination** **when pathogens** are non-intentionnaly inoculated in the food OR **when physical (non "eatable" ) objects** are introduced into food **during the process,** coming from the environment (for exemple, iron residues, plastic residues, etc.)


I would say that "packaging risks" and "handling contamination "are two kinds of "physical hazards" because of the potential **presence of harzardous "substances" in the food** that could be **undesirable biological agents or material/objects.**

Any thoughts?

**Comment by maweber-bia** [comment]
and if you defined biological harzards as the  potential causes of troubles or disease, there are not only pathogens but also toxic molecules (e.g. compounds neoformed during processing) that could be listed in this hierarchy
