### ISSUE TITLE
Creation of python assisted robot template animal parts module

### ISSUE THREAD

**Issue by kaiiam** [FoodOntology/foodon#300]
As discussed in [CIDGOH - USDA Collaboration Call Log](https://docs.google.com/document/d/1XDk0SRtCPUAdT_CYSxyvWrFS8O-mfdBJxXqde9ga-Ks/edit?usp=sharing) The foodon team has been working to make a general purpose animal parts module produced by the combination of robot template like rows original work done in [FoodOn Animal Tables](https://docs.google.com/spreadsheets/d/1SJrbJVPuOsX1B4W3D1P0yU5ESID5_KSl9sSxX3cQz48/edit?usp=sharing) against a list of species. Creation of reference issue for long anticipated pull request.

**Comment by kaiiam** [comment]
for your review @ddooley 🎸

**Comment by ddooley** [comment]
This is now launched!
