### ISSUE TITLE
Obsolete class has subclasses

### ISSUE THREAD

**Issue by rachhuntley** [FoodOntology/foodon#305]
Hello,

In both the March and April 2024 Owl versions of Foodon (downloaded from here https://bioportal.bioontology.org/ontologies/FOODON), there is a class 'crab' (http://purl.obolibrary.org/obo/FOODON_03411335) that is marked as obsolete, but it still has subclasses attached to it, e.g. orgeniid family (FOODON:03414138), mud crab family (FOODON:03412215) and several others.

Could these subclasses be rehoused under the correct class, which I am assuming is FOODON:02021446.

Many thanks,
Rachael Huntley.

**Comment by ddooley** [comment]
Thanks for reporting this.  This is now corrected in the Foodon-edit.owl file and will be published shortly!
