### ISSUE TITLE
Stray bracket character in ChEBI URI

### ISSUE THREAD

**Issue by rachhuntley** [FoodOntology/foodon#306]
Hello,

In the latest Foodon Owl file from https://bioportal.bioontology.org/ontologies/FOODON (dated 4/11/2024), the following ChEBI URIs have a right bracket `)` at the end which is causing problems in our application. Could they be removed, please?

http://purl.obolibrary.org/obo/CHEBI_28283)
http://purl.obolibrary.org/obo/CHEBI_28600)
http://purl.obolibrary.org/obo/CHEBI_4038)
http://purl.obolibrary.org/obo/CHEBI_5993)
http://purl.obolibrary.org/obo/CHEBI_6360)
http://purl.obolibrary.org/obo/CHEBI_6699)
http://purl.obolibrary.org/obo/CHEBI_7603)
http://purl.obolibrary.org/obo/CHEBI_90275)

Thanks,
Rachael.

**Comment by ddooley** [comment]
Oh dear!  I see these are actually originating in CDNO, which we import.  I have temporarily corrected them now in foodon-edit.owl draft, but I will get the CDNO curator to do these changes upstream in CDNO too so it doesn't happen again...

**Comment by rachhuntley** [comment]
Great, thanks very much Damion!
