### ISSUE TITLE
Multiple labels for FOODON:00001251 in v2024-06-17 release

### ISSUE THREAD

**Issue by allenbaron** [FoodOntology/foodon#313]
FOODON:00001251 appears to have two different english labels (rdfs:label) in the 2024-06-17 release: 'avian animal food product' and 'avian food product'. Is this intentional? Is one preferred?

_Based on the latest [OBO dashboard](http://dashboard.obofoundry.org/dashboard/index.html) run (2024-05-26) it looks like this isn't the only case._

**Comment by ddooley** [comment]
Thanks for reporting this - the 'avian animal food product' has been resolved.  We will be chipping away at the other duplicate labels, and the OBO dashboard error items, to get top marks, but this will take a while.

**Comment by allenbaron** [comment]
Thanks! ...and I totally understand.

**Comment by ddooley** [comment]
A new release has solved this; I will close this now, but work will continue on duplicate label issue.
