### ISSUE TITLE
invalid dateTime syntax on Russet potato

### ISSUE THREAD

**Issue by balhoff** [FoodOntology/foodon#318]
[Russet potato](http://purl.obolibrary.org/obo/FOODON_00004971) has a value for `dcterms:date` of `2024-07-04 17:32:19`. This should have a `T` between the date and time (https://www.w3schools.com/xml/schema_dtypes_date.asp). This syntax is checked by various RDF tools such as riot.

**Comment by ddooley** [comment]
This will be fixed on next release next week.  Thanks for reporting!
