### ISSUE TITLE
version IRIs don't resolve

### ISSUE THREAD

**Issue by balhoff** [FoodOntology/foodon#319]
I wanted to use a previous version of FOODON to work around #318, but I am unable to download specific versions like `https://github.com/FoodOntology/foodon/releases/download/v2024-07-12/foodon.owl` or `https://github.com/FoodOntology/foodon/releases/download/v2024-06-17/foodon.owl`.

**Comment by ddooley** [comment]
Resolving this now, sorry for delay.  A basic question I have is whether the convention is to have a "v" in front of date?  In the OWL version identifier it seems its not recommended to put anything other than date in.  So it looks like the release folder itself varies slightly, which is fine, but I just want to confirm.

**Comment by balhoff** [comment]
I frequently see the "v" in the tag name, but not in the actual ontology IRI. This is how the Uberon config works:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/5a365c1b1e459cc501a12493e98fd0c55a0b283c/config/uberon.yml#L183-L184

**Comment by ddooley** [comment]
Ok, I have added the foodon.owl file to recent FoodOn releases so that it can be accessed via the vYYYY-mm-dd path, i.e. https://github.com/FoodOntology/foodon/releases/download/v2024-07-12/foodon.owl  . I'll adjust the Ontology Version IRI annotation accordingly into the future.
