### ISSUE TITLE
NTR: Fermented food product in East Asian region, especially in Thailand

### ISSUE THREAD

**Issue by suzuki-shm** [FoodOntology/foodon#36]
Hello.

I would like to submit a request of new terms. They are related to fermented product in East Asian region. Also, I cannot find these terms in SIREN food products.
I'm not confident with these defintion. These terms are mainly from Thailand's fermented product. They are written as a source of microorganisms in Database ([News release](http://www.nite.go.jp/en/nbrc/cultures/nbrc/use/thailact.html)), however they do not have detailed description. I've found out few definitions about them from research paper and etc (Note below). I hope that someone who is familiar with semantics of fermented foods in the Asian region will be here.

* Mum : [Mum (fermented sausage) production with pure culture of Lactobacillus plantarum and Lactobacillus pentosus](http://www.thaiscience.info/Article%20for%20ThaiScience/Article/2/10029146.pdf)
* Miang : Japanese dictionary (translated to English)
* Nham-pla : [Quality characteristics of fermented sour fish cake (Nham‐Pla)](http://www.tandfonline.com/doi/abs/10.1080/10942910009524644?journalCode=ljfp20)

## Requests

```
label: bu-du
definition: Budu is a fish sauce and fermented seafood products.
	xdbref: https://en.wikipedia.org/wiki/Budu_(sauce)

label: Hoi-dong
definition: fermented sea-mussel

label: Hom dong
definition: Fermented onions or pickled onion

label: Hua chai pow chem
definition: fermented vegetable 


label: Shrimp paste
definition: Shrimp paste or shrimp sauce is a fermented condiment commonly used in Southeast Asian, Northeastern South Asian and Southern Chinese cuisines.
	xdbref: https://en.wikipedia.org/wiki/Shrimp_paste
exact synonym: shrimp sauce
narrow synonym: kapi
narrow synonym: ngapi
narrow synonym: terasi
narrow synonym: belacan
narrow synonym: belachan
narrow synonym: blachang
narrow synonym: mắm ruốc
narrow synonym: mắm tép
narrow synonym: mắm tôm
narrow synonym: bagoong alamang
narrow synonym: bagoong aramang
narrow synonym: haa1 zoeng3/haa1 gou1
narrow synonym: hom ha/hae ko
narrow synonym: sidol

label: Ma kham dong
definition: Fermented fruit

label: Ma yom dong
definition: Fermented fruit 

label: Miang
definition: Pickles for tea in northern Thailand. Wrapped in sugar and eat directly

label: Mum
definition: Mum is a Thai traditional dry fermented sausage made from pork or beef with some ground innards, roasted rice, steamed rice, garlic, sugar, pepper, salt and filled into intestine.
	

label: Mum-khai-pla
definition: Fermented fish roe 

label: Mum-sai-pla
definition: Fermented fish intestines

label: nam-budu
definition: Fermented fish in liquid form

label: Nham
definition: Fermented meat

label: Nham-pla
definition: Nham-pla were made from four kinds of fish, namely, striped catfish and nile tilapia from the fresh water fish and threadfin bream and barracuda from the marine fish. 

label: Noa mai
definition: Pickled bamboo shoots in Thailand

label: Noa mai dong
definition: Pickled bamboo shoots in Thailand

label: Pak kard dong
definition: Fermented vegetable

label: Pak kum dong
definition: Fermented vegetable 

label: Pak Sean dong
definition: Fermented vegetable 

label: Pak Sean and Hua plee dong
definition: Fermented vegetable 

label: Pak sean and Makhua dong
definition: Fermented vegetable 

label: pla-chom
definition: Fermented fish

label: Pla-jaw
definition: Fermented fish

label: Pla-jom
definiton: Fermented fish

label: Pla-ra
definition: Pla ra is a traditional Thai seasoning produced by fermenting fish with rice bran or roasted rice powder and salt fermented in a closed container for at least six months.
	xdbref: https://en.wikipedia.org/wiki/Pla_ra

label: Pla-ra sub
definition: Chili paste made from fermented fish and seasoning

label: Pla-ra-taung
definition: Fermented fish with seasoning

label: Pla-som
definition: Fermented fish

label: Pu dong
definition: fermented crab

label: Som-khai-pla
definition: Fermented fish roe 

label: tai-pla
definition: fermented fish entrails

label: Tuaw jaew
definition: Fermented soy beans 
```

**Comment by Public-Health-Bioinformatics** [comment]
Questions:
label: Ma kham dong
definition: Fermented fruit

label: Ma yom dong
definition: Fermented fruit 

Are these general terms or is there a specific fruit or vegetable we need to add to the definition?

I need to know which fish are involved, otherwise the following are synonyms?

label: pla-chom
definition: Fermented fish

label: Pla-jaw
definition: Fermented fish

label: Pla-jom
definiton: Fermented fish

**Comment by suzuki-shm** [comment]
Thank you for checking issue.

As I wrote above, we are not familiar with the definition of food above. So, I will only describe some information that I searched for and estimated.

> Are these general terms or is there a specific fruit or vegetable we need to add to the definition?

Perhaps it is a word about a particular fruit. [This web](http://www.eugenegoesthailand.com/?p=1492) page has a description about Ma-yom. It seems to be a fruit similar to mango. So Ma yom dong may be a fermented food using this fruit, I guess Ma kham dong also has similar definition. But I can not find a detailed description.

> I need to know which fish are involved, otherwise the following are synonyms?

For pla-chom, I found definitions from [this article](http://docsdrive.com/pdfs/academicjournals/jm/0000/38032-38032.pdf). It says "Pla-chom is most popular in the north-eastern part of Thailand. It is produced from small raw fish mixed with ground roasted gelatinous rice(khaao khuaa), salt and garlic. Pla-chom is typically fermented at room temperature between 28-30C for 3days."

Detailed definition of Pla jom and Pla jaw was not found. According to [this page](http://gcm.wfcc.info/NameListDisplayInServlet?name=Lactobacillus%20farciminis&displayin=table&strain_number=&advanced=null&namelist_collection=&namelist_temperature=&namelist_organismtype=&namelist_isolatedfrom=) Pla jom uses mixed fish and Pla jaw seems to use Pangasianodon hypophthalmus. At least, in [this article](http://www.jsmrs.jp/journal/No28_1/No28_1_1.pdf) pla-jaw and pla-jom are described side by side, I think that it is not a synonym.

**Comment by Public-Health-Bioinformatics** [comment]
I like that FoodOn is growing its international vocabulary here.  Another question: can I assume that all the above non-english names from the database are Thai (and that being the official language of Thailand?)

**Comment by Public-Health-Bioinformatics** [comment]
I will add these terms as is later this week, referencing the NBRC catalogue, so no need to delve further for definitions.  But I hope subsequently we can get better definitions for some terms that determine if they are generic, i.e if pla-chom | Pla-jaw| Pla-jom apply to all fermented fish in Thailand, or are particular to some kinds of fish.

**Comment by suzuki-shm** [comment]
>can I assume that all the above non-english names from the database are Thai (and that being the official language of Thailand?)

Probably it is. For example, as we can see in [Kaeng tai pla's wikipedia page](https://en.wikipedia.org/wiki/Kaeng_tai_pla), original tai-pla character in Thailand is "แกงไตปลา". This is pronounced as  [kɛ̄ːŋ tāj plāː]. So these names would be originated by its sounds. I think that there is no problem in dealing with these as a official language.

The words I mentioned in this issue are derived from Thailand, except shrimp paste. 
Interestingly, this dish is not limited to Thailand but it seems to be made in East Asian countries (Thailand, Vietnam, China, Indonesia and Malaysia). In Thailand it seems to be called "kapi". Japan and Korea also have similar dishes, that are fermented mysidacea (Japan: "Tsukeami" or "salted guts of mysidacea", Korea: "Saeu-jeot"). However, because it was mentioned that it is different in leaving the shape of shrimp, it is not included in synonym. Please see the [wikipedia page of shrimp paste](https://en.wikipedia.org/wiki/Shrimp_paste) and wikipedia page of [Saeu-jeot](https://en.wikipedia.org/wiki/Saeu-jeot) for details.

**Comment by Public-Health-Bioinformatics** [comment]
Here's the list of new ids.  I've stated most of them as having "countryOfOrigin' some Thailand.  I've listed them via @en name below though it raises question for me - can these names be listed as @th thai as well as english or do we reserve Thai characters for that?

'ma kham dong' | <http://purl.obolibrary.org/obo/FOODON_00001307>
'ma yom dong' | <http://purl.obolibrary.org/obo/FOODON_00001308>
'noa mai dong' | <http://purl.obolibrary.org/obo/FOODON_00001318>
'noa mai' | <http://purl.obolibrary.org/obo/FOODON_00001317>
'pak kard dong' | <http://purl.obolibrary.org/obo/FOODON_00001319>
'pak kum dong' | <http://purl.obolibrary.org/obo/FOODON_00001320>
'pak sean and hua plee dong' | <http://purl.obolibrary.org/obo/FOODON_00001322>
'pak sean and makhua dong' | <http://purl.obolibrary.org/obo/FOODON_00001323>
'pak sean dong' | <http://purl.obolibrary.org/obo/FOODON_00001321>
'pu dong' | <http://purl.obolibrary.org/obo/FOODON_00001327>
'shrimp paste' | <http://purl.obolibrary.org/obo/FOODON_03309823>
'tuaw jaew' | <http://purl.obolibrary.org/obo/FOODON_00001330>
bu-du | <http://purl.obolibrary.org/obo/FOODON_00001263>
hoi-dong | <http://purl.obolibrary.org/obo/FOODON_00001305>
mum | <http://purl.obolibrary.org/obo/FOODON_00001310>
mum-khai-pla | <http://purl.obolibrary.org/obo/FOODON_00001311>
mum-sai-pla | <http://purl.obolibrary.org/obo/FOODON_00001312>
nam-budu | <http://purl.obolibrary.org/obo/FOODON_00001313>
nham | <http://purl.obolibrary.org/obo/FOODON_00001315>
nham-pla | <http://purl.obolibrary.org/obo/FOODON_00001316>
pla-chom | <http://purl.obolibrary.org/obo/FOODON_00001324>
pla-jaw | <http://purl.obolibrary.org/obo/FOODON_00001325>
pla-som | <http://purl.obolibrary.org/obo/FOODON_00001326>
som-khai-pla | <http://purl.obolibrary.org/obo/FOODON_00001328>
tai-pla | <http://purl.obolibrary.org/obo/FOODON_00001329>

**Comment by suzuki-shm** [comment]
Nice jobs!

>can these names be listed as @th thai as well as english or do we reserve Thai characters for that?

In my personal opinion, I agree with using @en annotation.  Because the semantics of @en in English seems to be the same as that of @th expressed in Thai characters.  I think the same can be said for the word tsunami; the origin of this word is Japanese, but it seems to be used in English as well.
There is no other word with equivalent semantics in English this time, I agree to use @en as it is.

Perhaps not applicable to such a case is probably the word "マンション" in Japanese. "マンション" is pronounced as mˈænʃən, same with "mansion". Of course, the origin of this word comes from English. However the definition is completely different from English, it means condominium or apartment[[1](https://www.thejapanguy.com/what’s-the-difference-between-a-japanese-mansion-and-a-japanese-apartment/)] .

**Comment by Public-Health-Bioinformatics** [comment]
Ah, homonyms strike again, across languages!
