### ISSUE TITLE
New Term request and coordination

### ISSUE THREAD

**Issue by diatomsRcool** [FoodOntology/foodon#37]
I'm working on an ontology of core ecological terms (ecocore). I need a "food resource" class that would be a subclass of resource in SDGIO. Any preferences for how I do this?
https://github.com/EcologicalSemantics/ecocore

**Comment by Public-Health-Bioinformatics** [comment]
Hi @diatomsRcool ,
I just noticed this; somehow notification got lost in Nov, sorry!  I took a peek to see what "resource" category you have there. I see it is defined as "A material or immaterial entity which may confer benefit to its user or consumer."  So I could see how "food resource" could fit under there. I'll say that I found we needed a "food material" defined in foodon, and so placed it under ENVO "environmental material".  I suppose it has some roll-play as food.  At any rate, I'm just wondering about the difference between a "food material" and a "food resource"?

**Comment by diatomsRcool** [comment]
Actually, I think food material would work just fine. I'll use that. Thanks!

**Comment by Public-Health-Bioinformatics** [comment]
Great!  And @pbuttigieg I should double check - right now "food material" has a FoodOn id. Did you want that to be an ENVO minted term?

**Comment by diatomsRcool** [comment]
Is there a way to include an axiom in FOODON food material to say that it has role some 'resource role' (SDGIO_00010017)?

**Comment by Public-Health-Bioinformatics** [comment]
I'm happy to accommodate, but curious what adding that role accomplishes. There's discussion on OBI at moment about what roles do (https://github.com/obi-ontology/obi/issues/890) and actually how to avoid them in the future. On a philosophical note, I've grudgingly accepted roles due to the momentum of their usage.  My own take is that naming that something has a role (visa vis something else, implicitly) is a shorthand for saying that something has such and such a functional capability. So I've been friendly to defining that a material / class of material has some capability (functionality), e.g. to provide nourishment (to object classes XYZ?), instead. (The other use of "role" is more human-centric - the granting by some authoritative agency the right to offer some service, like being a doctor; that too also entails the capability of performing some functionality (and malpractice insurance!) ).

**Comment by Public-Health-Bioinformatics** [comment]
@diatomsRcool any update on this needed?

**Comment by diatomsRcool** [comment]
Thanks for checking in. I agree that what I am really asking for is that a thing has a functional capability. So, if I wanted to say that FOODON food material has the function to provide nourishment or to address some essential need (which is what I assume a 'resource role' is), how would that work? Is that possible?

**Comment by pbuttigieg** [comment]
@Public-Health-Bioinformatics either way is fine I think, as long as it's aligned to environmental material

**Comment by pbuttigieg** [comment]
@diatomsRcool @Public-Health-Bioinformatics.

Functions and roles are distinct, but both are realisable entities. 

Roles are more externally grounded. Functions are the result of evolution or design. It feels a bit strange to say that the providing food is a function of an organism (one would evolve away from that in most cases, unless being eaten is adaptive) . It's also a bit odd to say that foodness is a role.

In SDGIO, I think role makes sense for resources, as humans assign resourceness to things for economic reasons. There's nothing about materials like bauxite that inherently disposes them to aluminum production (i.e. along some sort of "natural " thermodynamic landscape) .

 In ecology, this seems more like a disposition (more internally grounded) . Organisms realise their disposition to nourish other organisms when consumed. This doesn't hold for some things considered "food" in the vocabs FOODON works with, which could be nutritionless but which have been assigned a food role by humans. 

Perhaps we need "disposition to provide nourishment to an organism " and related classes under disposition to satisfy raw (hehe) ecology semantics. We would also have "food role " for things that wouldn't be food in the biological sense, but are in the regulatory sense.

But the question is, what do we need it for in ECOCORE? I can imagine these realisables being useful for inference. Chris often suggests to focus on the process semantics (inputs outputs etc; e.g. heterotrophy has_input some "organic material") first. Those axioms often provide enough to build equivalence axioms for inference without resorting to realisables. Would that be reasonable @diatomsRcool ?

**Comment by Public-Health-Bioinformatics** [comment]
Thanks Pier for the distinction between externally grounded roles and functions as result of evolution/design, that helps. (Humans do intervene in evolution to promote food production in organisms, even to the point where such orgs. can't reproduce naturally, but lets skirt that for now.)

I like that idea of focusing on process semantics, then possibly finding abstractions. If I grok, it allows us to avoid the problematic combination bomb of A 'has food role with respect to' B by instead focusing on:

* what processes can be applied to A (material separation - milking, picking fruit, harvesting, cutting, preserving, fermenting, external storage, external digestion) to output material entities of certain kinds. (A "preprocessing" of food where it isn't consumed directly?)
* what processes (functions) can B invoke (mastication, osmosis, internal storage, digestion ...) for consuming (taking as input) food materials of certain kinds (fats, carbohydrates, nutrients, ... ). These could be organized by trophic consumer type?! (any biologists out there know way more than I do about this!)

**Comment by diatomsRcool** [comment]
OK. Makes sense. I think.
