### ISSUE TITLE
Consider a different name/acronym

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#4]
Possible confusion between foodo/foodon

OntoFood suggested by @mateolan

Not entirely serious suggestions:
- chow
- grubbo

Add any suggestions or votes below

**Comment by Public-Health-Bioinformatics** [comment]
I mentioned this to the group here this morning (at our weekly ontology meeting: Fiona, Emma, and Damion-myself, Will away) and we felt that since the [pref]food[suf] namespace is pretty packed, it is a bit arbitrary what one chooses in the end - except for the metric of fewer syllables.  We wanted to stick with FoodOn.  It would probably take some show and dance to be seduced by some other option!  Let us know if others are voicing the same concern though.

**Comment by cmungall** [comment]
Thanks Damion.

I'll leave this open for another week to give others a chance to comment. I have no strong prefs myself

**Comment by pbuttigieg** [comment]
Looks like we're sticking with FOODON, closing this for now. 
The logo should contain three round objects in the Os: I vote for a pizza, a watermelon, and a durian. :pizza: :watermelon: <durian emoji>

**Comment by Public-Health-Bioinformatics** [comment]
Or maybe three packman chasing each other?! Heh!

D.

**Comment by mark-jensen** [comment]
Pac Man chasing a beer?

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.6.23&pv=9.2&source=email_footer_2]
On Wed, May 25, 2016 at 1:05 PM, Damion Dooley notifications@github.com wrote:
Or maybe three packman chasing each other?! Heh!

D.

**Comment by Public-Health-Bioinformatics** [comment]
Well if its one pacman, one beer, and one piece of pizza, its sounding rather couch potato.  Packman needs a head band and running shoes to suggest healthy lifestyle :)

D.

**Comment by mellybelly** [comment]
I recommended FOODIE for a prefix ;-), but methinks too late!

**Comment by Public-Health-Bioinformatics** [comment]
Thanks for your input.  That would have been sweet, and I regret not thinking of that a year ago!  However, there is another project I discovered a few months ago: http://foodie-project.eu/

And they've started their OWL 2 application ontology as FOODIE"
https://git.man.poznan.pl/stash/projects/FOOD/repos/model/browse/

Its NOT designed to be compatible with OBOFoundry however, and is focused on agri-sector data gathering as far as I can tell, so we shall persevere with our pure OBOFoundry effort!

D.

**Comment by cmungall** [comment]
We should still attempt to collaborate, align and leverage. I'll start a ticket

**Comment by Public-Health-Bioinformatics** [comment]
Yes, that would be good.  It looks not so easy to reuse terms right off the bat though since they aren't using the [ONTO_NAME]_[INTEGER] format.  But I will crack open their ontology to see what may be attractive organization-wise.

D.
