### ISSUE TITLE
Equiv axiom for purified drinking water has no genus

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#44]
http://purl.obolibrary.org/obo/FOODON_03301647
`EquivalentTo 'derives from' some 'drinking water'`

In general logical defs lacking a genus are a red flag. In this case it could be argued that the derives from relation implies the genus. 

But even then this is wrong. If I add poison to drinking water, the result is not purified drinking water.

purified drinking water is drinking water that is the output of a purification process

**Comment by cmungall** [comment]
__UPDATED COMMENT__

**Comment by Public-Health-Bioinformatics** [comment]
Looks like a conversion script I did last year created 105 items of this pattern "Equivalent to 'derives from' some [ingredient]" .  Am converting these to the proper subClassOf (as a necessary but not sufficient condition). Thanks for spotting this.

**Comment by Public-Health-Bioinformatics** [comment]
This is fixed and will be released shortly to github.
