### ISSUE TITLE
FOODON uses a PATO class as an object property

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#45]
http://www.ontobee.org/ontology/FOODON?iri=http://purl.obolibrary.org/obo/PATO_0005016

this is punning on the class, technically valid OWL but this is not what you want

**Comment by Public-Health-Bioinformatics** [comment]
Not sure how that happened.  That's supposed to be RO "surrounded by" - "http://purl.obolibrary.org/obo/RO_0002219" .  Will fix now.

**Comment by Public-Health-Bioinformatics** [comment]
Thanks for spotting.  Fixed.
