### ISSUE TITLE
dubious property chain for has-ingredient

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#46]
http://purl.obolibrary.org/obo/FOODON_00002420

`(has part o derives from) subPropertyOf has ingredient`

This means

 * human has-ingredient some embryo
 * human has-ingredient some neural tube
 * plant food has-ingredient some seed
 * bicycle has-ingredient some rubber tree

etc

**Comment by Public-Health-Bioinformatics** [comment]
So this would need to be limited to entities in the food domain - more specifically a domain and a range of "food product type".  Is that a solution that works for you?  The semantics of "ingredient" as a subcategory of parthood.

**Comment by Public-Health-Bioinformatics** [comment]
I've placed 'foodon product type' in domain and codomain of relationship. If that satisfies, I will close this ...

**Comment by Public-Health-Bioinformatics** [comment]
Also I dropped the property chain. Not quite sure why but it was leading to a conflict with ECOCORE trophic interaction
