### ISSUE TITLE
170 new food product classes

### ISSUE THREAD

**Issue by janelomax** [FoodOntology/foodon#53]
Add the attached food product classes from SciBite.

Also one duplicate found: Blue cheese 03301128, Blue cheese 00001065

[new food terms.txt](https://github.com/FoodOntology/foodon/files/2698418/new.food.terms.txt)

**Comment by ddooley** [comment]
We'll be able to review and import these terms in early January.  And I'll resolve the duplicate shortly!

Thanks!

Damion

**Comment by ddooley** [comment]
I've created a google doc to track curation progress on these terms. Starting work on it now.

https://docs.google.com/spreadsheets/d/10kXG3Bnv-yZJJ2grycVnLpRj9rBk27qZVCVLY55LGYI/edit?usp=sharing

**Comment by ddooley** [comment]
Question for you: should "navel orange" be entered into FoodON as a reference to the organism as a whole, i.e. what FoodOn would label "navel orange tree", or do you want it to point to what is basically the most primitive food product, i.e. "navel orange (whole, raw)" ? This distinction exists for most plant food products. Semantically, usually the latter is intended I think.

p.s. blue cheese duplicate resolve in current foodon draft.

**Comment by ddooley** [comment]
About dairy cattle, dairy cow: FoodOn would have separate entries for each of these, especially if "dairy cattle" is meant to include bulls.  If "dairy cattle" is all female then it would be listed as a plural synonym of dairy cow. So are bulls part of the picture? Otherwise we should indicate "all female dairy cattle" in term synonym label? I'm checking with the LanguaL folks about what they intended for "Cow" as well which is a subclass of cattle at moment.

**Comment by ddooley** [comment]
About "darkling beetle": Is this general category edible or just subspecies? I see https://en.wikipedia.org/wiki/Mealworm#As_food , which is listed as a subspecies of darkling beetle.

Also, there's the question about larvae - is it really for example mealworm larvae that need referencing, or a compound term of say "(mealworm and `insect larvae`)"? I'm reading https://en.wikipedia.org/wiki/Entomophagy which is certainly a direction FoodOn should detail.

**Comment by AnneliK** [comment]
Hello and thanks for looking in to adding some of our suggested novel entries.

1) For navel orange, I think it could be treated as for example valencia oranges (they both belong to Citrus sinensis group/species), so
"orange plant (food source)-----"navel orange plant (food source)"
 orange (whole, raw) ----- "navel orange (whole, raw)"

2) To me, it makes more sense to restrict "dairy cattle" to female animals only. So happy to exclude "bulls" from this. Unlikely anybody would search for bulls in this category or? So yes, indication of "all female dairy cattle and/or added as a synonym to cow makes sense. 

3) About the beetle, it is really the larvae (mealworms) that is used for food (except some subspecies are eaten for medicinal purposes like Ulomoides dermestoides) so maybe you are right in that referencing the larvae for some subspecies is better. And the creation of a entomophagy category with species that are consumed would be great. Especially as adding insects like crickets to bread is becoming popular (not for me.....)

Happy to discuss more about the above terms or anything else that pops up. 
Kind regards
Anneli

**Comment by ddooley** [comment]
One issue with: Cherrios: So far foodon has avoided branded food products.  On the other hand I go to the store and see generic O's - so I'll approach it that way I think, and then have dbxrefs or synonyms for them for Cherrios etc.  See https://www.mercurynews.com/2016/01/13/taste-off-the-best-os-cereal-is-it-cheerios/

**Comment by ddooley** [comment]
So first 30 terms are complete and in new FoodOn version online.  I think we can get the pastas and wines done next month.  One note, new FoodOn has dropped the "(food source)" and "(whole, raw)" text from the term labels, as they were largely unnecessary.  The raw fruit axioms have been relaxed slightly so that e.g. "orange" no longer mentions "fruit (fresh)" in its axiomatization.  This allows for fruits and vegetables to be referenced without requiring that they are in a "fresh" state.

**Comment by ddooley** [comment]
p.s. check the docs spreadsheet for new term ids and other notes.

**Comment by ddooley** [comment]
Going through the wine items now.  A detail is that for many wines there is a varietal grape - so I'm separating that onto its own product line.

**Comment by ddooley** [comment]
Also, the USDA ARS is about to launch their FDC Food Data Central website, which has a large section of branded, barcoded products. They'll be issuing a unique FDC id to each product, and so we recommend using their FDC id's for all branded products in your list rather than creating ontology terms for them per-se.  We're helping consult on their ontology future but can't say just yet whether they'll have their own OWL ontology that captures such IDs in URI's or not.  But regardless, they have URI's (and barcodes) that point to database records for products, including Wheatena and Zevia lines.

**Comment by ddooley** [comment]
The wine and pasta items are in https://docs.google.com/spreadsheets/d/1jcZtqoN-C75d4OCPUomtp5xNbqjLweoooSVqpK3XHSY/edit#gid=0 and are now incorporated into FoodOn via ROBOT templates, detailed on http://foodon.org/design/robot-managed-vocabularies/

**Comment by ddooley** [comment]
I have completed adding definitions (to draft FoodOn) for all but a few items which were branded foods and food colours.  I think the food colour chemicals should be submitted to CHEBI, and can be imported from there?

**Comment by janelomax** [comment]
Thanks Damion, that's great! Would you mind posting the list of classes that weren't added please?

**Comment by ddooley** [comment]
Here are the brand products that are not in FoodOn. To recap, we've backed off trying to curate brand products for now as it would be a whole other effort.

NEWFOOD0029 | ovaltine | Ovomaltine
NEWFOOD0047 | Wheatena | Wheatena breakfast cereal
NEWFOOD0049 | Zevia | zevia \| zevia drink \| zevia zero-calorie drink \| zevia zero calorie soda
NEWFOOD0113 | Grape-Nuts | Grape Nut \| Grape-Nuts cereal | branded food product. Use https://fdc.nal.usda.gov/fdc-app.html#/food-details/340616
NEWFOOD0116 | monster cereals | monster cereals \| boo berry \| Count Chocula \| Franken Berry \| frankenberry \| Fruit Brute \| Fruity Yummy Mummy | Brand name product - See USDA ARS FDC
NEWFOOD0128 | golden grahams | golden grahams \| Golden Grahams Cereal
NEWFOOD0129 | Golden Puffs Cereal | Golden Puffs Cereal\|Golden Puffs

The problem at moment with USDA FDC site is they can't guarantee the persistence of FDC ids for a given product.  We have raised this as an issue with them but it is still being discussed.

Possibly FoodOn could accept longstanding "household name" brand products, but what would the timeframe be. Ovaltine comes to mind in that category. 

Here are the food colours:

NEWFOOD0158 | Scarlet GN | Scarlet GN \| FD&C Red No. 4 \| C.I. Food Red 1 \| Ponceau SX \| C.I. 14700 \| Purple 4R\| E125\| Crimson 4R
NEWFOOD0159 | Fast Yellow AB | Fast Yellow AB \| Acid Yellow \| Food Yellow 2 \| C.I. 13015 \| E105
NEWFOOD0161 | brilliant blue | FD&C Blue No. 1 \| FD&C Blue No. 1 \| E133
NEWFOOD0162 | Fast Green FCF | FD&C Green No. 3 \| FD&C Green No. 3 \| Green 1724 \| Solid Green FCF \| E143
NEWFOOD0163 | orange B | orange B\|C.I. Acid Orange 137
NEWFOOD0164 | FD&C Yellow No. 6 | FD&C Yellow No. 6 \| E110 \| Orange Yellow S \| C.I. 15985
NEWFOOD0165 | yellow 2G | lissamine fast yellow 2g \| yellow 2g \| 1-(2,5- dichloro-4-sulfophenyl)-5-hydroxy-3-methyl-4- (p-sulfophenylazo)pyrazole disodium salt \| c.i. acid yellow 17, disodium salt \| yellow 2g, disodium salt \| 1-(2,5- dichloro-4-sulphophenyl)-5-hydroxy-3-methyl-4- (p-sulfophenylazo)pyrazole disodium salt \| 1-(2,5- dichloro-4-sulphophenyl)-5-hydroxy-3-methyl-4- (p-sulphophenylazo)pyrazole disodium salt \| 1-(2,5- dichloro-4-sulfophenyl)-5-hydroxy-3-methyl-4- (p-sulphophenylazo)pyrazole disodium salt\|E107 \| Lissamine Fast Yellow \| C.I. Acid Yellow 17 \| C.I. 18965 \| Light Fast Yellow 2G \| C.I. Food Yellow 5 \| Acid Leather Yellow 2GL \| Erio Flavine SX \| Fenalan Yellow G \| Erio Flavine 3G \| Kayacyl Yellow GG
NEWFOOD0166 | E 111 | e 111 \| e-111 \| c.i. food orange 2 \| orange ggn \| orange no.1 \| c.i. 15980 \| l-orange 1\|alpha-naphthol orange\|E111
NEWFOOD0167 | Acid Red 27 | FD&C Red 2 \| FD & C Red Dye No. 2 \| E123 \| Amaranth \| C.I. Food Red 9 \| Azorubin S \| C.I. 16185
NEWFOOD0168 | ponceau 6R | 1-(4-sulfo-1-naphthylazo)-2-naphthol-3,6,8- trisulfonic acid, tetrasodium salt \| ponceau 6r \| 1-(4-sulpho-1-naphthylazo)-2-naphthol-3,6,8- trisulfonic acid, tetrasodium salt \| 1-(4-sulpho-1-naphthylazo)-2-naphthol-3,6,8- trisulphonic acid, tetrasodium salt \| 1-(4-sulfo-1-naphthylazo)-2-naphthol-3,6,8- trisulphonic acid, tetrasodium salt\|Crystal ponceau 6R \| Crystal scarlet \| Brilliant crystal scarlet 6R \| Acid Red 44 \| C.I. 16250 \| E126
NEWFOOD0169 | C.I. Vat Blue 4 | c.i. vat blue 4 \| navinone blue \| anthraquinone vat blue 4 \| 6,15-dihydroanthrazine-5,9,14,18-terone\|Indanthrone blue \| indanthrene \| E130 \| carbon paper blue \| monolite fast blue 3R \| C.I. 69800 \| pigment blue 60
NEWFOOD0170 | alkannin | C.I. Natural red 20 \| Alkanet extract \| Anchusaic acid \| Anchusin
NEWFOOD0171 | citrus red No. 2 | citrus Red No. 2 \| Citrus Red 2 \| C.I. Solvent Red 80 \| C.I.12156 \| E121

**Comment by ddooley** [comment]
I can say USDA ARS discussion is continuing about how to offer brand name products permanent ids.
Any further comment on this thread?  Otherwise I will close it. We can open a separate food color thread if desired.

**Comment by janelomax** [comment]
Yep, fine to close this one out. Thanks for all the new terms!
