### ISSUE TITLE
Chicken Meat Food Product changes

### ISSUE THREAD

**Issue by griffie** [FoodOntology/foodon#59]
Hi Damion,
As discussed, a few paltry poultry (ha!) issues for correction please.
1) Chicken Meat Food Product (FOODON_00001040) should have axiom "_part_of_ Broiler Food Product" as broilers are types of chickens (on same level as layers, breeders). 
2) Deprecate FOODON_00001667 Broiler or fryer chicken meat food product. Reorganize everything currently underneath FOODON_00001667 by placing them under Chicken Meat Food Product (FOODON_00001040).
3) Make Fryer synonym of Broiler chicken (not further specified) (FOODON:03311753). Can we remove the "not further specified" bit?

Thanks!
Emma Griffiths

**Comment by ddooley** [comment]
I agree, so many of those products that are siblings to 'broiler or fryer chicken meat food product' that the broiler product category seems un-useful in the general context, but might remain important to some curators in the specific case where some distinction about the age of chicken meat product needs to be made.  Mulling that over.  I left 'broiler or fryer chicken meat food product' in place for now with no children, having moved them all up to chicken meat food product.

I've deprecated FOODON:03311753 Broiler chicken (not further specified) as the 'broiler or fryer chicken' (http://purl.obolibrary.org/obo/FOODON_03411198) food source term already exists.  I've added the fryer synonym to that term.
