### ISSUE TITLE
Term request for Diet and Human Diet in Ecocore

### ISSUE THREAD

**Issue by Mttbnchtt** [FoodOntology/foodon#60]
@pbuttigieg 
In issue [108](https://github.com/EcologicalSemantics/ecocore/issues/108) on Ecocore, I requested new terms for Ecocore and I explained that I temporarily introduced those terms in SDGIO.

**Comment by Mttbnchtt** [comment]
In issue on Ecocore, I added a discussion of the axioms to use to link diet and human diet to certain processes.

**Comment by ddooley** [comment]
Thanks for letting us know. I've left a comment in that thread https://github.com/EcologicalSemantics/ecocore/issues/108

**Comment by ddooley** [comment]
I'm moving discussion on this over to: https://github.com/FoodOntology/foodon/issues/74
