### ISSUE TITLE
Labeling food ice

### ISSUE THREAD

**Issue by pbuttigieg** [FoodOntology/foodon#62]
Hi @ddooley 

Would it be possible to relabel [FOODON:ice](http://purl.obolibrary.org/obo/FOODON_03301926) to avoid conflicts with [ENVO:ice](http://purl.obolibrary.org/obo/ENVO_01001125) ?

As FOODON:ice seems more specific ('derives from' some 'drinking water'), perhaps relabelling as "ice (food product)" or "food-grade ice" would work? 

You can add an axiom to ENVO that looks like:
```
'composed primarily of' some ['water ice'](http://purl.obolibrary.org/obo/ENVO_01000277)

```

**Comment by ddooley** [comment]
Good idea, we'll implement that shortly.  We'll do a relabel.  Indeed, the accent is often on "food-grade" things.  I'll just check to see what axiom fussiness might be needed to distinguish from ice that is somehow not food grade, if such a thing exists.

**Comment by ddooley** [comment]
completed rename.
