### ISSUE TITLE
import for wine_pasta.owl seems to break XML parsing

### ISSUE THREAD

**Issue by saramsey** [FoodOntology/foodon#66]
This imports statement in `foodon.owl` seems to break XML parsing:
```
<owl:imports rdf:resource="http://purl.obolibrary.org/foodon/imports/wine_pasta.owl"/>
```
On June 1, it was changed to
```
 <owl:imports rdf:resource="&obo;foodon/imports/wine_pasta.owl"/>
```
but it was for some reason reverted on July 1. Is there any way it can be fixed? 

I've tried parsing the `foodon.owl` (the master branch version) using `robot` and `owltools`, and both fail.

**Comment by ddooley** [comment]
Thanks for bringing that to my attention.  I can see the import file was missing an /obo/ path in file which was manually adjusted but not in the instructions for redoing it which happened last month.  I've fixed that now, so let me know if you have issues parsing it again...

**Comment by ddooley** [comment]
I presume this is resolved now?

**Comment by ddooley** [comment]
Closing unless further comment.

**Comment by saramsey** [comment]
Thanks, I will test it tonight in our workflow:

https://github.com/RTXteam/RTX/tree/master/code/kg2

**Comment by saramsey** [comment]
Confirmed, it is working now.  Thank you.

<img width="809" alt="Screen Shot 2019-09-17 at 10 34 17 PM" src="https://user-images.githubusercontent.com/5562107/65114356-56be9680-d99b-11e9-8b38-b3c3370a7063.png">
