### ISSUE TITLE
'O's cerial' typo

### ISSUE THREAD

**Issue by jshima-january** [FoodOntology/foodon#67]
Hi,

In the latest version of FoodOn, there looks to be a typo in one class related to a cereal. Specifically, "O's cerial" should likely be spelled as "O's cereal".  This relates to FoodOn id 00002520

**Comment by ddooley** [comment]
Thanks very much for that catch.  It is corrected now in the draft and will be uploaded this week.

**Comment by jshima-january** [comment]
@ddooley 
Great!  Thanks!
