### ISSUE TITLE
Species conflation in some cheese product classes

### ISSUE THREAD

**Issue by jshima-january** [FoodOntology/foodon#68]
Hi,

I observed a relationship in the latest version of FoodOn that is puzzling.  Specifically, "ovine cheese food product", which relates to sheep, and "caprine cheese food product", relating to goats are both subclassed from "bovine cheese food product", which of course relates to cows.   

My feeling is that these should be separated out into sibling classes under the "cheese food product" class rather than introducing an incorrect species based path.  This would also necessitate changes to the classing of specific food products such as "halloumi cheese food product" which can be made from sheep, goat, and/or cow's milk; currently this would be evaluated correctly but in other use cases, such as determining if a recipe has cow-based cheese in it or not, could be evaluated incorrectly given a traditionally sheep or goat cheese product.

**Comment by ddooley** [comment]
Thanks for that catch too. I've made the changes and they will be uploaded this week.  I've switched the halloumi definition to match Wikipedia's as current one doesn't allow for cow's milk.

**Comment by jshima-january** [comment]
@ddooley 
Thanks for this too.  Fair enough re: the Wikipedia definition.

I'm digging deep into FoodOn (amazing by the way!) for a project and will report anything else I might find :) 
Thanks for being so responsive with these too 💯

**Comment by ddooley** [comment]
Happy to have your critique.  Can I invite you to the https://groups.google.com/forum/#!forum/foodon-consortium group where we announce new changes and solicit feedback?  Specifically in the next week we will be offering up a better model for single component/multi-component foods that we want to curate our current content towards.

**Comment by jshima-january** [comment]
Absolutely...would love to be better informed.  Thanks!

**Comment by ddooley** [comment]
You can sign up here: https://groups.google.com/forum/#!forum/foodon-consortium/join
