### ISSUE TITLE
Nut or seed added defined to be product

### ISSUE THREAD

**Issue by matentzn** [FoodOntology/foodon#69]
Food added classes, such as `nut or seed added`, are defined as BFO:process; However, in its current form, `nut or seed added` is also logically defined as `'nut food product' or 'plant seed food product'`. This creates the implication that `nut or seed added` is a `plant food product` - which is a BFO:continuant. Currently some of our pipelines are breaking because of this.. Would you consider to change it? To fix this, we need to be sure that `nut or seed added` is neither equivalent to nor subclass of any kind of `food product` classes. Thank you!

@cmungall FYI

**Comment by ddooley** [comment]
Hmm, which FoodOn source URL are you using?  I have eliminated all of the "food added" classes, which were an artifact of the LanguaL import but aren't useful as we have the ingredients themselves.

**Comment by matentzn** [comment]
Weird; this just recently showed up in our pipeline which dynamically imports external ontologies. Must have been a glitch, you are right, this is not a problem in current FOODON. Sorry!
