### ISSUE TITLE
Miscategorized crustacean and mollusc seafoods

### ISSUE THREAD

**Issue by jshima-january** [FoodOntology/foodon#75]
Hi,

In the current FoodOn release, I see some food items belonging to the mollusc or crustacean families that appear to be miscategorized.  Specific cases, both current class-subclass relationships and proposed based on their label, are included below and attempt to align both branches of the FoodOn model and align with common vernacular (https://en.wikipedia.org/wiki/Shellfish)

| Concept      | Current Parent Class | Proposed New Parent Class |
| ----------- | ----------- | ----------- |
| abalone food product      | seafood product       | mollusc food product       |
| cockle food product   | seafood product        | mollusc food product       |
| mussel food product   | seafood product        | mollusc food product       |
| surfclam food product   | seafood product        | mollusc food product       |
| mollusc food product   | seafood product        | shellfish food product       |
| cephalopod food product   | shellfish product        | mollusc food product       |
| clam food product   | shellfish product        | mollusc food product       |
| oyster food product   | shellfish product        | mollusc food product       |
| crustacean food product   | seafood product        | shellfish food product       |
| shellfish   | invertebrate animal      | aquatic invertebrate      |
| crustacean   | aquatic invertebrate        | shellfish      |
| echinoderm   | aquatic invertebrate        | shellfish      |

**Comment by ddooley** [comment]
Ok, thanks for this review, much appreciated!  In draft FoodOn I've made the mollusc corrections in the FoodOn draft, as well as moving shellfish under "aquatic invertebrate".  I added a new echinoderm food product category.  And moved "crustacean" under shellfish.  This should help with allergy related axioms.  I cleaned up a few other seafood product items too.

But echinoderm doesn't have a shell - should we really make it subclass of shellfish?

**Comment by jshima-january** [comment]
@ddooley 
Perfect!  Thank you!  Exactly my thought as well re: allergies.

Ahh...but echinoderms do have a 'shell', its just internalized: https://en.wikipedia.org/wiki/Echinoderm#Skin_and_skeleton
https://www.britannica.com/animal/shellfish-animal

So I think we should make the change as described since they are colloquially and taxonomically a type of shellfish.

**Comment by ddooley** [comment]
Ok, thanks for clarifying. I learn something every day.  Changes implemented in draft; will upload to live later today.

**Comment by jshima-january** [comment]
Thanks!  Always a pleasure @ddooley
