### ISSUE TITLE
Orphan NCBITaxon classes after latest release

### ISSUE THREAD

**Issue by jshima-january** [FoodOntology/foodon#77]
Hi,

After pulling the latest release (2020-01-08), there are a non-trivial number of orphan NCBITaxon classes at the root level of FoodOn when opened in Protege (latest version of Protege).  These were not present in the prior release from November, 2019.

A sample list of these are shown in the screenshot below.

Is NCBI Taxon still used?  Or is this a bug?

<img width="192" alt="Screen Shot 2020-01-20 at 10 58 13 PM" src="https://user-images.githubusercontent.com/49459075/72782439-8e06b380-3bd8-11ea-869e-cd08299f39e7.png">

**Comment by ddooley** [comment]
Arg.  The owl import file for taxonomy was disconnected,.  Not sure how that happened.  I've reconnected it and refetched taxonomy. Seems ok now.
