### ISSUE TITLE
Additional shellfish food product miscategorization

### ISSUE THREAD

**Issue by jshima-january** [FoodOntology/foodon#78]
Hi,

Upon review, there appear to be a couple additional shellfish miscategorizations, similar to the issue described in https://github.com/FoodOntology/foodon/issues/75

| Class      | Current Parent Class | Proposed New Parent Class |
| ----------- | ----------- | ----------- |
| langostino food product     | fish food product       | crustacean food product       |
| cuttlefish food product     | fish food product       | mollusc food product       |
| limpet fish food product     | fish food product       | mollusc food product       |
| cockle (spiny, raw)     | crustacean food product       | cockle food product       |
| conch (raw)     | crustacean food product       | mollusc food product       |
| american razor clam (raw)   | crustacean food product       | clam food product       |

**Comment by ddooley** [comment]
Ok, thanks. I will remedy these in the next day or so.

**Comment by ddooley** [comment]
langostino is turning out to require more work as it is one of those terms that means different things to different speech communities!

**Comment by ddooley** [comment]
Done.  I also revised "limpet fish food product" to be just "limpet food product". Updates are in  /src/ontology/foodon.owl and foodon-merged.owl

**Comment by jshima-january** [comment]
@ddooley 
Thanks for the thorough and timely work as always!
