### ISSUE TITLE
Why is FOODON not importing PO classes

### ISSUE THREAD

**Issue by ramonawalls** [FoodOntology/foodon#79]
I do not understand why FOODON creates new classes like  http://purl.obolibrary.org/obo/FOODON_03411347 instead of importing http://purl.obolibrary.org/obo/PO_0000003. This seems like a pretty serious flaw. I need to create new ENVO classes that use plants as food, and I don't want to use the FOODON classes that ENVO is currently importing, because it will ruin the interoperability with PO.

**Comment by ddooley** [comment]
Actually, good catch Ramona. I am fine with deprecating that in favour of PO.  We brought much of foodon in from LanguaL, but had tried to do a round of replacement for PO and UBERON terms before significantly launching it over a year ago.  Still more work to do there.  I was deliberately trying to keep FoodOn plants and animals separate from direct reference to NCBITaxon.  But I was mulling reusing NCIT thesaurus terms.  But happy to switch to PO for plant.

**Comment by ddooley** [comment]
P.s. I'll remove many of the less informative "Uses in this ontology" axioms that are artifacts from the LanguaL import.

**Comment by ramonawalls** [comment]
That would be really great,  @ddooley! As a former PO curator, I could not help but notice it.

FYI, I am working with @lilyandres who is building a crop nutrition ontology,  to support database work by her advisor Graham King.  She is having a hard time reusing FOODON classes directly, but I think if we can clarify some of the definitions, she will be able to. They are particularly interested in distinguishing between things like a seed (from PO) versus a grain (which has been harvested), or a leaf that is part of a plant, versus a leaf that was harvested for food. FOODON has a start on these terms, but we want to make sure they are connected to PO, because we want to be able to also link to gene expression data in the PO.

**Comment by ddooley** [comment]
Perfect.  Those are exactly the kind of distinctions I want to see in FoodOn too, and I will appreciate the guidance in making that right.  This could even extend to FoodOn curation editing rights for those who want to go that far.

**Comment by ramonawalls** [comment]
> I was deliberately trying to keep FoodOn plants and animals separate from direct reference to NCBITaxon. But I was mulling reusing NCIT thesaurus terms. But happy to switch to PO for plant.

One could argue that http://purl.obolibrary.org/obo/PO_0000003 (whole plant) and http://purl.obolibrary.org/obo/NCBITaxon_33090 (Viridiplantae) are equivalant classes, if you want to use both.

But I would suggest using the PO class as primary.

**Comment by ddooley** [comment]
Happy to do that.  I will likely be switching to 'has taxon' and  'has only taxon' (from current 'has taxonomic identifier' relation) to relate somewhat more common name and grouping plant and animal entities to their taxonomic classification - which has a propensity to change in a number of cases.  I.e. will treat NCBITaxon as a separate hierarchy one can navigate by if desired.

**Comment by ddooley** [comment]
Deprecation of 'plant' done on foodon-edit.  It will be released soon. Note I left old term in hierarchy in case other user interfaces/databases still using it.  It may take a while to move out of there safely.

**Comment by ramonawalls** [comment]
Wonderful! Thanks fo the quick turnaround.
------------------------------------------------------
Ramona L. Walls, Ph.D.
Assistant Research Professor, Bio5 Institute, University of Arizona
Senior Scientific Analyst, CyVerse, University of Arizona
Part-time artist

**Comment by cmungall** [comment]
Reopening but ok to close and open a new ticket

http://purl.obolibrary.org/obo/FOODON_03420279 pollen

![image](https://user-images.githubusercontent.com/50745/121066143-6b018300-c77e-11eb-85ce-f57d7bfada8f.png)


everything below plant structure has FOODON IRIs, but should have PO IRIs

**Comment by ddooley** [comment]
pollen and stamen have recently been updated to a PO term so that will be published in the next week.  There are maybe a dozen remaining FoodOn plant anatomy terms that we are unsure of the mapping to PO so we'll add that to the to-do list and get PO help on them.

There are a number of FoodOn terms relating to plant anatomy which originated in LanguaL food composition database terms but which likely won't ever have anatomical names per se. because they arise from processing plants some way into parts, or make generalizations across disparate clades or are organizational or legacy disjunction terms:  "root, stem, leaf or flower", husk, "root, tuber, or bulb, without peel" etc. Plus a few BTO terms.

**Comment by ddooley** [comment]
BTW, the bulk of non-inferred terms under PO "plant structure" are from PO.  FoodOn food products are increasingly being inferred under this branch as with "vegetable (whole)" and "garlic scape" below.

![image](https://user-images.githubusercontent.com/4000582/121078967-6c3aac00-c78e-11eb-94b3-5ea7dd1769c4.png)

**Comment by ddooley** [comment]
Closing this now, will address any remaining Foodon to PO replacements on a term by term basis.
