### ISSUE TITLE
Unexpected synonym values via hasExactSynonym property

### ISSUE THREAD

**Issue by jshima-january** [FoodOntology/foodon#81]
Hi,

There are a handful of exact synonyms in FoodOn that do not seem correct; they appear to be either a definition or a URI reference.  Suggest that these be recategorized using a more appropriate annotation property.

| URI      | Synonym |
| ----------- | ----------- | 
|http://purl.obolibrary.org/obo/FOODON_00003090 |http://purl.obolibrary.org/obo/IAO_0000122|
|http://purl.obolibrary.org/obo/FOODON_00002998 |The ivy gourd (Coccinia grandis) is a tropical vine that grows primarily in tropical climates and is commonly found in the southern Indian states, where it forms a part of the local cuisine. Coccinia grandis is cooked as a vegetable.|
|http://purl.obolibrary.org/obo/FOODON_00002968 |Okazi leaves, often referred to as spinach, are used as a leafy vegetable for soups and stews, commonly called eru soup or afang soup, or eaten raw. The leaves may further be used as a remedy for nausea, sore throats, or as a dressing for warts.|
|http://purl.obolibrary.org/obo/FOODON_00003071 |http://purl.obolibrary.org/obo/IAO_0000428|
|http://purl.obolibrary.org/obo/FOODON_00002000 |A lima bean vegetable food product is any food product derived primarily from lima beans.|
|http://purl.obolibrary.org/obo/FOODON_00002448 |A zucchini food product is a food product deriving from either golden or green zucchini plant cultivars.|
|http://purl.obolibrary.org/obo/FOODON_00003266 |The fruit of a fig plant|

**Comment by ddooley** [comment]
good catch, thanks.  most are supposed to be definitions.  Will revise in the next week.
d.

**Comment by ddooley** [comment]
Revised.  Now in GitHub repo.

**Comment by jshima-january** [comment]
Great!  Thanks!
