### ISSUE TITLE
Bug: maybe duplicated definitions

### ISSUE THREAD

**Issue by kgv** [FoodOntology/foodon#82]
The query (http://www.ontobee.org/sparql):
```sparql
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT *
WHERE {
    ?s rdfs:subClassOf <http://purl.obolibrary.org/obo/FOODON_03460238>.
    OPTIONAL { ?s obo:IAO_0000115 ?definition. }
}
```

Return duplicate records differing only first letter in definition:
```text
http://purl.obolibrary.org/obo/FOODON_03470121 "preservation by filtering out yeasts and molds, generally followed by aseptic packaging. FDA CFSAN 1995]"@en
http://purl.obolibrary.org/obo/FOODON_03470121 "Preservation by filtering out yeasts and molds, generally followed by aseptic packaging. FDA CFSAN 1995]"@en
...
```

**Comment by ddooley** [comment]
That is an odd one.  I checked the foodon-edit.owl file and there is no duplicate there.  The only entry is the Caps one.  I suspect problem is in Ontobee end.  I'll see if they can identify an include file that hasn't been refreshed perhaps. I did take trailing bracket off, and will move that change to GitHub repo shortly ...

**Comment by ddooley** [comment]
I think this is resolved now in latest FoodOn GitHub master.  Not quite sure how though.  The query returns unique lines as far as I can see.
