### ISSUE TITLE
foodon.owl does not parse due to cutlassfish

### ISSUE THREAD

**Issue by cmungall** [FoodOntology/foodon#96]
```
    <owl:Class rdf:about="&obo;FOODON_03414026">
        <rdfs:subClassOf rdf:resource="&obo;FOODON_03411581"/>
        <obo:IAO_0000114 rdf:resource="&obo;IAO_0000428"/>
        <obo:IAO_0000115 xml:lang="en">The cutlassfishes are about 40 species of predatory fish in the family *Trichiuridae* (order Perciformes) found in seas throughout the world
. Fish of this family are long, slender, and generally steely blue or silver in colour, giving rise to their name. They have reduced or absent pelvic and caudal fins, giving them 
an eel-like appearance, and large fang-like teeth. Some of the species are known as scabbardfishes or hairtails; others are called frostfishes because they appear in late autumn a
nd early winter, around the time of the first frosts.</obo:IAO_0000115>
        <obo:IAO_0000119 rdf:resource=" https://en.wikipedia.org/wiki/Cutlassfish"/>
  ```

Note the whitespace preceding the URL

I recommend adding more tests to your Makefile to catch these

Aside: I have a suspicion this may be responsible for this "Very strange - As of 2018/11/28, unless this annotation on the subClassOf relation exists, with Makefile, the relation is removed from foodon.owl output and 'food transformation process' becomes parentless. Related to robot "WARNING: An illegal reflective access operation has occurred"???" due to oddities of owlapi parser chaining

**Comment by ddooley** [comment]
What is the validation tool you are using?  That would be handy.  So far I've just been using robot to convert protege-saved files and hadn't seen any errors that way.  But am running into problems the last 4 days with attempts to save from protege but owl:Class are being rewritten as rdf:Description and rdf:nodeid which is horrible (for communal editing at least).

**Comment by ddooley** [comment]
I've fixed the space issue. Looking into the "illegal reflective access operation" error again.
